AntelopeIO/leap

- libraries/state_history/include/eosio/state_history/log.hpp
The ancient boost version in pinned builds has a broken boost::thread when building on Ubuntu 22.04. This is not terribly surprising, we've seen such problems before and it's why we've tried to move away from some of these boost libraries.
Remove the boost thread header; it's not being used except for the `catch(boost::thread_interrupted)` which is unnecessary since we're using std::thread here anyways.
Resolves #32
> remove boost::thread usage, fixing pinned builds

- tests/cli_test.py
Fixes multiple issues I've encountered with cli_test:
* don't assume builddir is a subdirectory of sourcedir, resolves #30. All the needed files are already in the builddir so this is literally just removing a needless `..`
* remove a deceptive `print()` of an error. It's always an error and it's intended to be an error
* use `makedirs()` to ensure all parent directories are created. This is needed when the test if the first (or only) test to run, such as when running all the tests in parallel. Otherwise the `var/` directory doesn't exist and the test errors out.
> fix multiple problems in cli_test

- README.md
When a user has more than one LLVM installed, cmake picks the version.. somehow :shrug:.. maybe highest version? This ends up being a problem on Ubuntu 22.04 where if a user
```
apt-get install llvm-dev llvm-11-dev
```
they end up with both 11 & 14 installed and Leap's cmake without any hints finds LLVM 14 thus fails configuration.
In the README instructions, let's adjust the command for cmake to explicitly search the llvm-11 directory first. This allows building properly when LLVM 11 & 14 are installed.
> [3.1] explictly reference llvm11 in README's build documentation cmake command

- .github/workflows/build.yaml
Currently PRs can't be merged because they aren't satisfying branch protection rules. Turns out that a branch protection rule specifying, for example, "Tests" doesn't satisfy the matrix of tests such as "Tests (ubuntu18)", "Tests (ubuntu20)", etc
Making the branch protection rule specify all matrix'ed jobs is too brittle: the names of jobs will change overtime as we add and remove new tests, such as an upcoming test that checks the native contract unit tests.
Instead, let's create a final job in the workflow that only passes if all dependent jobs pass -- where all dependent jobs are all the test jobs. That way the branch protection rule can simply check that "All Required Tests Passed" passed and the workflow can evolve over time without needing to touch the branch protection rule.
> [3.1] add a final job that passes if all tests pass making it easier to branch protect on checks

- plugins/http_plugin/http_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/48 and https://github.com/AntelopeIO/leap/issues/47
- allow `http-max-bytes-in-flight-mb` bigger than 4GB
- make `-1` indicate unlimited
- validate value of `http-max-bytes-in-flight-mb`
- correct `http-max-bytes-in-flight-mb` description (changing `503 error response when exceeded` to `429 error response when exceeded`
> [3.1] fix a number of issues with http-max-bytes-in-flight-mb configuration

- plugins/http_plugin/http_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/48
- allow `http-max-bytes-in-flight-mb` bigger than 4GB
- make `-1` indicate unlimited
- validate value of `http-max-bytes-in-flight-mb`
> [3.1 -> main] fix a number of issues with http-max-bytes-in-flight-mb configuration

- plugins/signature_provider_plugin/CMakeLists.txt
- plugins/signature_provider_plugin/signature_provider_plugin.cpp
This came along for the ride on eosnetworkfoundation/mandel#541. But it relies on `se-helpers` library which was never ported from 2.1. Remove it.
> remove nonworking Secure Enclave support from signature_provider_plugin

- .github/workflows/build.yaml
- testnet.template
- tests/Cluster.py
- tests/WalletMgr.py
Python regression test failed because a debug log statement caused a python exception. The debug log statement format string was malformed. 
Also include some better capturing of test log output to more easily debug test failures in the future. 
* Rename `eosio-ignition-wd` to `leap-ignition-wd` directory used by tests.
* Add `leap-ignition-wd` directory to captured log directories on test failures. 
* Move `keosd` test logs into `var/` directory so they are captured on test failures.
Resolves #62
> [3.1] Fix python format issue that caused test to fail

- .github/workflows/build.yaml
- testnet.template
- tests/TestHarness/Cluster.py
- tests/TestHarness/WalletMgr.py
Python regression test failed because a debug log statement caused a python exception. The debug log statement format string was malformed. 
Also include some better capturing of test log output to more easily debug test failures in the future. 
* Rename `eosio-ignition-wd` to `leap-ignition-wd` directory used by tests.
* Add `leap-ignition-wd` directory to captured log directories on test failures. 
* Move `keosd` test logs into `var/` directory so they are captured on test failures.
Resolves #62
> [3.1 -> main] Fix python format issue that caused test to fail

- plugins/net_plugin/net_plugin.cpp
- tests/nodeos_startup_catchup.py
3.1.0-rc3 included https://github.com/eosnetworkfoundation/mandel/pull/627 which attempted to fix a producer stuck in a coma state. However, the fix was a bit too aggressive and introduced a race-condition on startup syncing.
This PR reverts the aggressive reset of syncing from LIB instead of HEAD for every call to `start_sync`. Instead it restarts syncing from LIB only when unlinkable blocks causes a connection to be closed. This should still fix the issue of https://github.com/eosnetworkfoundation/mandel/issues/623 without causing the problem seen in #49.
Resolves #49
> [3.1] Fix failure to sync on startup

- CMakeLists.txt
use an `install(DIRECTORY` here to reduce the amount of copying. Also we don't need all those `CMAKE_SOURCE_DIR` & `CMAKE_BINARY_DIR` since that's the default for `configure_file()` anyways. (some day we should take a pass through all the cmake files and remove those redundancies as I've seen them in quite a few places)
> [3.2] cleanup & simplify license file handling

- plugins/net_plugin/net_plugin.cpp
- tests/nodeos_startup_catchup.py
3.1.0-rc3 included https://github.com/eosnetworkfoundation/mandel/pull/627 which attempted to fix a producer stuck in a coma state. However, the fix was a bit too aggressive and introduced a race-condition on startup syncing.
This PR reverts the aggressive reset of syncing from LIB instead of HEAD for every call to `start_sync`. Instead it restarts syncing from LIB only when unlinkable blocks causes a connection to be closed. This should still fix the issue of https://github.com/eosnetworkfoundation/mandel/issues/623 without causing the problem seen in #49.
Resolves #49
> [3.1 -> main] Fix failure to sync on startup

- plugins/net_plugin/net_plugin.cpp
Do not throw exception in posted lambdas to main thread as this causes non-joined threads to terminate. Instead report error and quit the application.
```
error 2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3747           operator()           ] net_plugin::plugin_startup failed to bind to port 9876, bind: Address already in use
info  2022-08-30T13:15:52.885 nodeos    resource_monitor_plugi:122    plugin_shutdown      ] shutdown...
info  2022-08-30T13:15:52.885 nodeos    resource_monitor_plugi:129    plugin_shutdown      ] exit shutdown
info  2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3776           plugin_shutdown      ] shutdown..
info  2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3793           plugin_shutdown      ] close 0 connections
info  2022-08-30T13:15:52.885 nodeos …
```
> [3.1] Fix crash on startup if port already in use

- plugins/net_plugin/net_plugin.cpp
Do not throw exception in posted lambdas to main thread as this causes non-joined threads to terminate. Instead report error and quit the application.
```
error 2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3747           operator()           ] net_plugin::plugin_startup failed to bind to port 9876, bind: Address already in use
info  2022-08-30T13:15:52.885 nodeos    resource_monitor_plugi:122    plugin_shutdown      ] shutdown...
info  2022-08-30T13:15:52.885 nodeos    resource_monitor_plugi:129    plugin_shutdown      ] exit shutdown
info  2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3776           plugin_shutdown      ] shutdown..
info  2022-08-30T13:15:52.885 nodeos    net_plugin.cpp:3793           plugin_shutdown      ] close 0 connections
info  2022-08-30T13:15:52.885 nodeos …
```
> [3.1 -> main] Fix crash on startup if port already in use

- libraries/version/include/eosio/version/version.hpp
- libraries/version/src/version.cpp
- libraries/version/src/version_impl.cpp.in
- libraries/version/src/version_impl.hpp
- programs/eosio-launcher/CMakeLists.txt
- programs/eosio-launcher/config.hpp.in
- programs/eosio-launcher/main.cpp
- programs/nodeos/CMakeLists.txt
- programs/nodeos/config.hpp.in
- programs/nodeos/main.cpp
libversion is the canonical method by which components should be retrieving the build version. But both nodeos' & eosio-launcher's CMakeLists were running git to retrieve a version. Remove that and replace with libversion usage instead. libversion needed a method added to retrieve the git hash as nodeos' get_info server_version returns the first 4 bytes of the git hash.
> [3.2] replace git commands from nodeos' & launcher's cmake with libversion usage

- .github/workflows/build.yaml
This improves CICD build time by about 20% (reducing the build stage from ~5m to ~4m) by two improvements:
* Use new [upload-artifact-large-chunks-action](https://github.com/AntelopeIO/upload-artifact-large-chunks-action) which substantially increases the artifact upload performance for large files (like the builddir each build uploads). The improvement approaches 5x for these large 150MB files.
* Build the `leap-dev` package in parallel while the tests run. It's not unusual for building the packages to take 30 seconds, so kicking that task over to a slow GitHub runner to be done in parallel while tests are running saves some time.
Some slight whitespace adjustments came along for the ride.
In retrospect I should have called "All Required Tests Passed" something like "All Required Jobs …
> [3.2] improve CICD build time via faster artifact upload & parallel leap-dev creation

- plugins/chain_api_plugin/chain.swagger.yaml
Rename `get_scheduled_transaction` to `get_scheduled_transactions` (notice the trailing "s") as `get_scheduled_transaction` does not exist.
Also fix the description.
> [3.2] Fix documentation for get_scheduled_transactions in plugins/chain_api_plugin/chain.swagger.yaml

- .github/workflows/build.yaml
- tests/CMakeLists.txt
Move tests that execute in less than 3 minutes out of the `long_running_tests` bucket and in to the `nonparallelizable_tests` bucket.
Long running tests are also moved to a new runner type, `enf-x86-lowtier`. This is an 8vCPU 16GB instance. Similar to NP tests, most of these long running tests idle around so I am "over subscribing" them for now. We can always bump up the resources on this runner type if needed. Like midtier, `enf-x86-lowtier` is running on the "give me whatever you got tier" which seems to be getting rather old Broadwell CPUs.
🚨 This completely removes `nodeos_sanity_lr_test`. afaict it's the exact same test as the non-lr test; am I missing something? 🚨
```
add_test(NAME nodeos_sanity_test COMMAND tests/nodeos_run_test.py -v --sanity-test --clean-run --dump-error-detail …
```
> move tests that are sub 3 minutes out of long running classification

- scripts/0001-beast-fix-moved-from-executor.patch
- scripts/pinned_build.sh
Our pinned builds will use boost 1.70 for the entirety of 3.x's lifecycle. boost 1.70 shipped with a defect in beast's websocket implementation that can lead to crashes. Can read more here,
```
https://github.com/boostorg/beast/issues/1599
```
The patch included with this PR to fix the issue is linked directly from boost's release notes for 1.70 so it seems to be a well supported fix
https://www.boost.org/users/history/version_1_70_0.html
The only component in Leap that uses websockets is the state history plugin and we caution users to only expose that websocket endpoint to internal trusted clients, so this fix isn't being fast tracked.
Resolves eosnetworkfoundation/mandel#816
> [3.1] patch pinned build's boost 1.70 to fix websocket defect

- tests/ship_client.cpp
Similar tweak to what already exists in state_history_plugin
> [3.2] fix ship_client test on boost 1.67-1.69

- tests/trx_finality_status_test.py
It is possible for a trx to arrive at the BP node a few milliseconds before block signing which results in an almost immediate inclusion in the block. The test was not expecting the trx to make it to a block so quickly.
Resolves #105 
Resolves https://github.com/eosnetworkfoundation/mandel/issues/488
> [3.1] Fix test failure due to trx hitting near end of block production time

- tests/trx_finality_status_test.py
It is possible for a trx to arrive at the BP node a few milliseconds before block signing which results in an almost immediate inclusion in the block. The test was not expecting the trx to make it to a block so quickly.
Resolves #105 
Resolves https://github.com/eosnetworkfoundation/mandel/issues/488
> [3.1 -> main] Fix test failure due to trx hitting near end of block production time

- tests/trx_generator/CMakeLists.txt
- tests/trx_generator/trx_generator_tests.cpp
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
Added a tps_performance_monitor that shutdowns the test if the sent transactions falls below a specified threshold for a specified amount of time.  A spin up time can also be specified.
> Added tps_performance_monitor

- plugins/producer_plugin/producer_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/86
Add input validation for `set_whitelist_blacklist`, `add_greylist_accounts` and `remove_greylist_accounts` by ensuring at least one optional parameter is present in a RPC call.
Previously,
```
curl -d '{"foo":["bar"]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
{"result":"ok"}
```
Now,
```
curl -d '{"foo":["bar"]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
{"code":400,"message":"Invalid Request","error":{"code":3200006,"name":"invalid_http_request","what":"invalid http request","details":[{"message":"At least one of actor_whitelist, actor_blacklist, contract_whitelist, contract_blacklist, action_blacklist, and key_blacklist is required","file":"producer_plugin.cpp","line_number":1382,"method":"set_whitelist …
```
> [3.1] validate input of set_whitelist_blacklist, add_greylist_accounts and remove_greylist_accounts

- plugins/producer_plugin/producer_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/86
Merge https://github.com/AntelopeIO/leap/pull/113 from `release/3.1` to `main`
Add input validation for `set_whitelist_blacklist`, `add_greylist_accounts` and `remove_greylist_accounts` by ensuring at least one optional parameter is present in a RPC call.
Previously,
```
curl -d '{"foo":["bar"]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
{"result":"ok"}
```
Now,
```
curl -d '{"foo":["bar"]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
{"code":400,"message":"Invalid Request","error":{"code":3200006,"name":"invalid_http_request","what":"invalid http request","details":[{"message":"At least one of actor_whitelist, actor_blacklist, contract_whitelist, contract_blacklist, action_blacklist, and key_blacklist is …
```
> [3.1 -> main] Validate set whitelist blacklist input main

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
`uint32_t` for microseconds of subjective billing only allows for 1.2hrs before wrapping. Use `int64_t` instead which matches type used for objective billing.
Resolves #123
> [3.1] Allow for larger subjective CPU billing amounts

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
`uint32_t` for microseconds of subjective billing only allows for 1.2hrs before wrapping. Use `int64_t` instead which matches type used for objective billing.
Resolves #123 
Merges #124 into `main`.
> [3.1 -> main] Allow for larger subjective CPU billing amounts

- tests/trx_finality_status_forked_test.py
The `trx_finality_status_forked_test.py` test purposely introduces a fork to verify trx is forked out and reports the correct state. The failure was for a case when another fork happened after the first fork delaying the time for the trx to reach irreversible.
Add verification to the test that the trx is on the expected fork before verifying it is irreversible.
Resolves #127
> [3.1] Test: verify on the correct fork before verifying trx status

- tests/trx_finality_status_forked_test.py
The `trx_finality_status_forked_test.py` test purposely introduces a fork to verify trx is forked out and reports the correct state. The failure was for a case when another fork happened after the first fork delaying the time for the trx to reach irreversible.
Add verification to the test that the trx is on the expected fork before verifying it is irreversible.
Resolves #127 
Merges #128 into `main`
> [3.1 -> main] Test: verify on the correct fork before verifying trx status

- .cicd/platforms/ubuntu18.Dockerfile
- .cicd/platforms/ubuntu20.Dockerfile
- .cicd/platforms/ubuntu22.Dockerfile
- .gitmodules
- CMakeLists.txt
- README.md
- docs/03_keosd/10_usage.md
- docs/03_keosd/30_how-to-guides/how-to-attach-a-yubihsm-hard-wallet.md
- docs/03_keosd/30_how-to-guides/index.md
- libraries/CMakeLists.txt
- plugins/wallet_plugin/CMakeLists.txt
- plugins/wallet_plugin/include/eosio/wallet_plugin/yubihsm_wallet.hpp
- plugins/wallet_plugin/wallet_plugin.cpp
- plugins/wallet_plugin/yubihsm_wallet.cpp
- scripts/install_deps.sh
Reverts the removal of YubiHSM support performed in #66. Since it seems like a 3.2 will happen off of `main` at some point, hold off breaking changes in `main` for now.
> [3.2] Revert "remove YubiHSM support from keosd" (#66); restore this functionality for now

- libraries/testing/include/eosio/testing/snapshot_suites.hpp
- unittests/snapshot_tests.cpp
The Snapshot test had a periodic failure due to a race condition involving "BinSnapshot" "JsonSnapshot" and "BinFromJsonSnapshot" when running multithreaded. This PR fixes that by changing the names to include the PID, so that collision does not occur.
Also included is a change to use `/` overload to have temp_file() be more portable in snapshot_suites.
Resolves #134
> [3.2] Fix multithreaded Snapshot test Failure

- plugins/net_plugin/net_plugin.cpp
Test failure of #115 caused by peer not requesting blocks when no blocks where received from the sync source peer.
Two things contributed to this.
1. The node was expecting blocks from a different source than the tracked `sync_source` because the `sync_source` was set to a different connection but no new request was sent. When the connection was closed that this node was expecting blocks from it did not request from a different connection because the `sync_source` indicated it was already syncing from a different connection. This caused it not to try a different connection on the close of the sync source connection.
2. This should have timed out, but since no blocks were ever received it never sent a new handshake.
Changed to keep `sync_source` up to date with with the connection actually …
> [3.1] net_plugin fix startup issue when peer does not have requested blocks

- plugins/net_plugin/net_plugin.cpp
Test failure of #115 caused by peer not requesting blocks when no blocks where received from the sync source peer.
Two things contributed to this.
1. The node was expecting blocks from a different source than the tracked `sync_source` because the `sync_source` was set to a different connection but no new request was sent. When the connection was closed that this node was expecting blocks from it did not request from a different connection because the `sync_source` indicated it was already syncing from a different connection. This caused it not to try a different connection on the close of the sync source connection.
2. This should have timed out, but since no blocks were ever received it never sent a new handshake.
Changed to keep `sync_source` up to date with with the connection actually …
> [3.1 -> main] net_plugin fix startup issue when peer does not have requested blocks

- tutorials/bios-boot-tutorial/genesis.json
`initial_chain_id` is a remnant of long ago...
> [3.2] Remove initial_chain_id in genesis.json as it is not supported.

- tests/release-build.sh
Running the release-build test causes creation of config.ini in the default location. I'm treating any tests that touch the default config and data directories as a defect since we've seen problems before when they do that. This particular case is probably ultimately benign but eh it's also straightforward to fix.
Resolves #157
> [3.1] use a temp dir for release-build test as it can leak creation of config.ini in to default location

- tests/release-build.sh
main merge of #165 that resolves #157. Makes release-build test use a tempdir so it doesn't pollute (and potentially conflict) with default nodeos' config location
> [3.1 -> main] use a temp dir for release-build test as it can leak creation of config.ini in to default location

- programs/cleos/main.cpp
- tests/nodeos_run_test.py
Backport of https://github.com/EOSIO/eos/pull/8676 via https://github.com/eosnetworkfoundation/mandel/pull/580 causes issue with action data of `eosio.msig`. See #118 for details.
Added new `cleos` option `-u, --unpack-action-data` which can be used with `--dont-broadcast` for expanding transaction action data section of JSON. The default now produces the same format as v3.1.0 which is what is expected by `eosio.msig` contract.
Resolves #118
> [3.2] cleos: only unpack action data when explicitly asked

- plugins/producer_plugin/producer_plugin.cpp
#151 Added 3-strike rule to subjective blocks. However, the 3-strike rule is supposed to be disabled for read-only transactions and when subjective billing is disabled. 
Disable 3-strike rule when subjective billing is disabled or if transaction is read-only.
Resolves #174
> [3.2] Do not apply 3-strike rule when subjective billing is disabled

- .github/workflows/build.yaml
This is a cost/efficiency change in preparation for more tests to be run in CI shortly (such as pinned builds & ARM builds). The parallel tests will now run on the lesser "hightier" runner which doesn't slow down total test time at all because even with the reduced number of CPUs we have to wait around for the `test_monitor_loop` test which is a minute longer than anything else.
The current configuration, always subject to change if need be,
* **beefy**: 224 "CPUs", 896GB¹
* **hightier**: 96 "CPUs", 48GB
* **midtier**: 16 "CPUs", 24GB
* **lowtier**: 8 "CPUs", 16GB
1: This was 224GB until very recently. Last couple days started to see some runs exhaust memory so was bumped up.
> [3.2] switch parallel tests to new runner type

- plugins/producer_api_plugin/producer.swagger.yaml
Complete update of plugin_producer HTTP protocol documentation. One file changed. 
resolved #87 
- corrected return codes, filling in 400 errors when missing 
- corrected schemas both provided and returned 
- updated descriptions
- added get_account_ram_corrections which was missing from docs
> Docs:  http protocol spec for producer plugin

- scripts/pinned_build.sh
`main` branch merge of https://github.com/AntelopeIO/leap/pull/179.
Resolve https://github.com/AntelopeIO/leap/issues/130.
Two issues prevents relative paths from working:
1. `if [[ ${D} != ${EXPECTED} ]]; then` does string comparison. `../lib` != `/home/lib` even though they refer to the same directory.
2. After the first problem was fixed, a second error occurred in `cmake`:
```
The CMAKE_C_COMPILER:
../lib/clang-11.0.1/bin/clang
is not a full path and was not found in the PATH.
```
After the fix, 
`./scripts/pinned_build.sh ../lib ./build 6` produces
```
...
CPackDeb: - Generating dependency list
.----------------.  .----------------.  .----------------.  .----------------.
| .--------------. || .--------------. || .--------------. || .--------------. |
| |   _____      | || | …
```
> [3.1 -> main] pinned_build.sh: make relative path work

- .github/workflows/label_new_issues.yaml
Make use of a new reusable workflow to label all new issues with the _triage_ label, and add them to the _Team Backlog_ project with the _Status_ field set to _Todo_.
The one aspect that I'm not too happy with here is that modifying the project requires a token with rather broad permissions (`repo` & `project` scopes). Remember that PRs from forks don't have access to secrets, and this workflow doesn't consume any user controlled input, so in general this secret ought to be well protected against any abuse.
> [3.2] label new issues with 'triage' label and add them to the Team Backlog project as Todo

- tests/performance_tests/performance_test_basic.py
- tests/trx_generator/main.cpp
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
Added a new return value (TERMINATED_EARLY -3) for trx_generator to indicate that the test terminated early.
> [PH] Added early termination status

- tests/trx_finality_status_forked_test.py
Test failed #178 because the fork took longer to resolve than the default 60 seconds on the test run. Increase timeout for fork resolution to 120 seconds.
Resolves #178
> [3.1] trx_finality_status_forked_test fix

- tests/trx_finality_status_forked_test.py
Test failed #178 because the fork took longer to resolve than the default 60 seconds on the test run. Increase timeout for fork resolution to 120 seconds.
Resolves #178
> [3.1 -> main] trx_finality_status_forked_test fix

- libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
- plugins/producer_api_plugin/producer.swagger.yaml
- plugins/producer_api_plugin/producer_api_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/plugin_http_api_test.py
- unittests/unapplied_transaction_queue_tests.cpp
Add `/v1/chain/get_unapplied_transactions` to `producer_api_plugin`
Interface:
```
get_unapplied_transactions_params {
string                lower_bound;  /// transaction id
optional<uint32_t>    limit = 100;
optional<uint32_t>    time_limit_ms; // defaults to 10ms
};
unapplied_trx {
transaction_id_type       trx_id;
time_point_sec            expiration;
string                    trx_type; // eosio::chain::trx_enum_type values or "read_only"
account_name              first_auth;
account_name              first_receiver;
action_name               first_action;
uint16_t                  total_actions = 0;
uint32_t                  billed_cpu_time_us = 0;
size_t                    size = 0;
};
get_unapplied_transactions_result {
size_t                     size = 0;
size_t …
```
> [3.2] Add /v1/chain/get_unapplied_transactions to producer_api_plugin

- plugins/chain_api_plugin/chain.swagger.yaml
- plugins/net_api_plugin/net.swagger.yaml
- plugins/producer_api_plugin/producer.swagger.yaml
- plugins/test_control_api_plugin/test_control.swagger.yaml
- plugins/trace_api_plugin/trace_api.swagger.yaml
The OpenAPI files had http references to an out of date location for schema items. Updated to use new host name/path.
Example of updated path
https://eosio.github.io/schemata/v2.1/oas/BlockInfo.yaml
> [3.2] updated schema references to eosnetwork host

- libraries/state_history/include/eosio/state_history/log.hpp
Recovering the logs is a very time intensive operation, but `dlog` isn't enabled by default. Promote these to `ilog`
> [3.1] promote ship log recovery logging from dlog to ilog

- libraries/state_history/include/eosio/state_history/log.hpp
main merge of #194
> Recovering the logs is a very time intensive operation, but `dlog` isn't enabled by default. Promote these to `ilog`
> [3.1 -> main] promote ship log recovery logging from dlog to ilog

- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- programs/cleos/main.cpp
- tests/Node.py
- tests/prod_preactivation_test.py
- tests/testUtils.py
Leap 3.1 returns transaction failure traces by default. `EOSIO/eos 2.0` would instead throw an exception. 
The [3.1 release notes](https://github.com/AntelopeIO/leap/releases/tag/v3.1.0) included the following:
> New command line options for cleos:
> - `--use-old-send-rpc`
>   - "Use old RPC `/v1/chain/send_transaction`, rather than new RPC `/v1/chain/send_transaction2`"
> - `-t,--return-failure-trace` defaults to `true` use `-t false` for previous behavior
>   - "Return partial traces on failed transactions"
>   - Note: Automation which depends on `cleos` to return a non-zero value on transaction failure will instead need to parse the traces or use option `-t false`.
This PR addresses the cleos non-zero return values for failed transaction execution. With this PR, cleos will parse the …
> [3.1] Update cleos to return an error code on failed trx processing

- libraries/state_history/include/eosio/state_history/log.hpp
This `elog` is resulting in red error log prints during the course of normal shut down. It def shouldn't be an error, but I'm not seeing much utility in logging it at all?
> [3.2] remove elog when ship thread exits normally

- plugins/producer_plugin/producer_plugin.cpp
This was generating a compiler warning that a value was not handled.
> [3.2] add missing incoming_persisted in unapplied transaction queue's get_trx_type

- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- programs/cleos/main.cpp
- tests/TestHarness/Node.py
- tests/TestHarness/testUtils.py
- tests/prod_preactivation_test.py
Leap 3.1 returns transaction failure traces by default. `EOSIO/eos 2.0` would instead throw an exception. 
The [3.1 release notes](https://github.com/AntelopeIO/leap/releases/tag/v3.1.0) included the following:
> New command line options for cleos:
> - `--use-old-send-rpc`
>   - "Use old RPC `/v1/chain/send_transaction`, rather than new RPC `/v1/chain/send_transaction2`"
> - `-t,--return-failure-trace` defaults to `true` use `-t false` for previous behavior
>   - "Return partial traces on failed transactions"
>   - Note: Automation which depends on `cleos` to return a non-zero value on transaction failure will instead need to parse the traces or use option `-t false`.
This PR addresses the cleos non-zero return values for failed transaction execution. With this PR, cleos will parse the …
> [3.1 -> main] Update cleos to return an error code on failed trx processing

- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/TestHarness/WalletMgr.py
- tests/TestHarness/testUtils.py
- tests/cli_test.py
Use Python 3.5+ feature of capturing stderr in CalledProcessError.
Also remove "debug" ERROR print statement which was causing log spam.
Cleanup related to #139
> [3.2] Cleanup regression python test handling of CalledProcessError

- tests/nodeos_retry_transaction_test.py
- tests/testUtils.py
`nodeos_retry_transaction_test.py` was created after default of `--return-failure-trace=true`. PR #139 changed `cleos` to return an error now when a transaction trace has an exception indicating the trx failed. Update test to expect this `cleos` error return code.
Also remove a debug `ERROR:` print that was causing confusing output in the tests.
Run of test here: https://github.com/AntelopeIO/leap/actions/runs/3112753652
Resolves #217
> [3.1] Fix nodeos_retry_transaction_test.py

- plugins/http_plugin/http_plugin.cpp
Log all `std::exception` raised during API calls at `debug` level to reduce log spam when running in default `info` level log mode. This is the same level `fc::exception` is already logged.
Resolves #186
> [3.2] Log std::exception while handling API calls at debug level

- tests/nodeos_retry_transaction_test.py
`nodeos_retry_transaction_test.py` was created after default of `--return-failure-trace=true`. PR #212 changed `cleos` to return an error now when a transaction trace has an exception indicating the trx failed. Update test to expect this `cleos` error return code.
Also remove a debug `ERROR:` print that was causing confusing output in the tests.
Run of test here: https://github.com/AntelopeIO/leap/actions/runs/3113504045
Resolves #217 
Merges #218 into `main`.
> [3.1 -> main] Fix nodeos_retry_transaction_test.py

- .github/workflows/build.yaml
https://github.com/AntelopeIO/leap/actions/runs/3107049183/jobs/5034762683 mentioned in #210 didn't upload failure logs because one of the files listed on tar's command line wasn't created in that particular test. `tar --ignore-failed-read` to fix this case and ensure all the other existing files do get uploaded.
> [3.1] when uploading failure logs, ignore missing files

- .github/workflows/build.yaml
Currently we only run LR tests for merges to main or release branches, as well as when manually requested. Due to our usage of the "All Required Tests Passed" test as a branch protect rule we can go ahead and enable these LR tests to always run and still not block merging should a PR be approved and need to merge before LR tests complete.
Based on some experimentation:
* If the PR is approved before "All Required Tests Passed" completes successfully, the merge button remains disabled (with an admin override option for some of us).
* If a PR is approved before or after "All Required Tests Passed" completes successfully, but before LR tests complete, the merge button is "white" -- this still allows merging.
* Once LR tests complete successfully the merge button additionally goes green.
* If …
> [3.2] always run the long running tests, including for pull requests

- tests/Cluster.py
- tests/nodeos_contrl_c_test.py
Test failure due to attempt to use system contract to create an account before the system contract `init` transaction executed. Add a wait to the test for the system `init` contract to make it into a block before continuing the test.
Also fix `nodeos_contrl_c_test.py` to not log "Test succeeded" when the test fails.
Resolves #223
> [3.1] Test fix: wait for system init to be in block

- tests/TestHarness/Cluster.py
- tests/nodeos_contrl_c_test.py
Test failure due to attempt to use system contract to create an account before the system contract `init` transaction executed. Add a wait to the test for the system `init` contract to make it into a block before continuing the test.
Also fix `nodeos_contrl_c_test.py` to not log "Test succeeded" when the test fails.
Resolves #223 
Merges #226 into `main`.
> [3.1 -> main] Test fix: wait for system init to be in block

- .cicd/platforms/ubuntu18.Dockerfile
- .cicd/platforms/ubuntu20.Dockerfile
- .cicd/platforms/ubuntu22.Dockerfile
Use Ubuntu python3-numpy package instead of installing through pip
> [PH] Migrate numpy to ubuntu pkg

- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
- Causes trx_generators to be killed upon sigint.
- Outputs to console upon sigint.
- Reports in JSON whether a run was canceled early.
- Moves analysis to finally, so it is still run when sigint is invoked.
> [PH] Performance harness graceful shutdown

- plugins/trace_api_plugin/trace_api.swagger.yaml
- added trace_transcation method
- updated return schema for both get_block and get_transaction_trace
- New v2 schema for BLockTrace added to options for returned schema
- New v2 and v3 schema for TransactionTrace added to options for returned schema
- New sub-schemas ActionTraceV2 and BlockTRaceV2
- added new component types
- ERROR_DETAILS
> [3.1] updated trace_api openapi documentation

- plugins/trace_api_plugin/trace_api.swagger.yaml
sibling of #224
- added trace_transaction method
- updated return schema for both get_block and get_transaction_trace
- New v2 schema for BLockTrace added to options for returned schema
- New v2 and v3 schema for TransactionTrace added to options for returned schema
- New sub-schemas ActionTraceV2 and BlockTRaceV2
- added new component types
- ERROR_DETAILS
> [3.1 -> main] updated trace_api openapi documentation

- libraries/libfc/CMakeLists.txt
See comment in change. Restores easy macOS building after changes in fc post-desubmod.
> [3.2] "null out" iostream's library dependencies on macOS

- libraries/libfc/src/crypto/city.cpp
- libraries/libfc/src/crypto/crc.cpp
Defining our own `_mm_crc32_u64` implementation can clash with some compilers. Not too surprising since that's a reserved name in global scope. In particular, AppleClang will give an error:
```
error: always_inline function '_mm_crc32_u64' requires target feature 'sse4.2', but would be inlined into function 'CityHashCrc256Long' that is compiled without support for 'sse4.2'
```
Rename our impl to just `mm_crc32_u64` and redirect to either `mm_crc32_u64` or `_mm_crc32_u64` via a new macro.
> [3.2] avoid redefining _mm_crc32_u64 which can lead to compile errors

- libraries/chain/apply_context.cpp
- libraries/chain/controller.cpp
- libraries/chain/eosio_contract.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/config.hpp
- libraries/chain/webassembly/softfloat.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/net_plugin/net_plugin.cpp
- plugins/trace_api_plugin/store_provider.cpp
- plugins/trace_api_plugin/test/test_extraction.cpp
- plugins/trace_api_plugin/test/test_trace_file.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
- plugins/txn_test_gen_plugin/txn_test_gen_plugin.cpp
- programs/cleos/main.cpp
- programs/eosio-launcher/main.cpp
- unittests/abi_tests.cpp
- unittests/api_tests.cpp
- unittests/auth_tests.cpp
- unittests/bootseq_tests.cpp
- unittests/deep_mind_tests.cpp
- unittests/delay_tests.cpp
- unittests/snapshot_tests.cpp
- unittests/wasm_config_tests.cpp
- unittests/wasm_tests.cpp
- Most of the changes are from the removal of ignoring unused-variables from `chain/config.hpp`
- Removed pragma to ignore `strict-aliasing` from `chain_plugin` which is the main reason for the changes.
- Didn't need any code changes as this did not generate any warnings (at least on clang).
- [ Will see what GCC does with it in cicd. ]
Resolves #229
> [3.1] Remove #pragma(s) to ignore warnings

- tests/WalletMgr.py
- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
#228 Failed due to keosd default 30ms timeout for `http-max-response-time-ms`. Increase the time out as there is no reason to limit this for `keosd`. 
Related #230 
Resolves #228
> [3.1] Increase keosd http-max-response-time-ms for tests

- libraries/libfc/secp256k1/CMakeLists.txt
Resolve https://github.com/AntelopeIO/leap/issues/19
`secp256k1` produced over 190 warnings in the form of
```
/home/lh/work/leap-main/libraries/libfc/secp256k1/secp256k1/src/field.h:44:13: warning: ‘secp256k1_fe_normalize’   declared ‘static’ but never defined [-Wunused-function]
44 | static void secp256k1_fe_normalize(secp256k1_fe *r);
|             ^~~~~~~~~~~~~~~~~~~~~~
/home/lh/work/leap-main/libraries/libfc/secp256k1/secp256k1/src/field.h:47:13: warning:                            ‘secp256k1_fe_normalize_weak’ declared ‘static’ but never defined [-Wunused-function]
47 | static void secp256k1_fe_normalize_weak(secp256k1_fe *r);
.../home/lh/work/leap-main/libraries/libfc/secp256k1/secp256k1/src/field.h:44:13: warning: ‘secp256k1_fe_normalize’   declared ‘static’ but never defined …
```
> [3.2] disable unused-function warning in secp256k1

- libraries/libfc/include/fc/exception/exception.hpp
- libraries/libfc/src/crypto/elliptic_webauthn.cpp
- plugins/chain_plugin/chain_plugin.cpp
- unittests/api_tests.cpp
- unittests/eosio.token_tests.cpp
- unittests/wasm_tests.cpp
Partially resolve https://github.com/AntelopeIO/leap/issues/254
After this PR, only 4 warnings remain in submodules `abieos` and `libfc/libraries/ff/libff`.
Most of the changes are straightforward. The following two need to be noted.
1. For #warning directives in `wasm_tests.cpp` and `api_tests.cpp`, I created issues for them https://github.com/AntelopeIO/leap/issues/259 and https://github.com/AntelopeIO/leap/issues/260. I think this is a better way to handle TODOs. Leaving them in #warning will not get them to be done. I kept them as comments for easier identification if we decide to work on them.
2. To resolve the warning in `chain_plugin.cpp`, I need to introduce a new macro `FC_LOG_AND_DROP_NO_INTERPROCESS_BAD_ALLOC`. The warning was
```
In file included from …
```
> [3.2] more compiler warnings cleanup

- libraries/chain/controller.cpp
When replaying a block log, the transactions with expirations equal to the last irreversible block time were not added to the trx de-dup list. This creates a difference in the de-dup list vs starting from state or a snapshot. Note transactions are cleared from the de-dup list at the start of a block according to if they are less than (not less than or equal) the pending block time.
Regression test will come in a different PR. See https://github.com/AntelopeIO/leap/pull/268.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/301
> [3.1] Fix replay to correctly add trxs into the de-dup list

- plugins/producer_plugin/producer_plugin.cpp
The logging of duplicate transactions is confusing as it looks like a transaction failure case. However, duplicate transactions are expected and do not indicate any sort of error condition. The most common cause of duplicate transaction is receiving a transaction in a block before receiving it over P2P for speculative execution. All transactions received via a block before being received by P2P are duplicate.
Also do not subjectively bill for duplicate trxs. We have never subjectively billed for duplicate transactions, but the unreleased refactor #29 mistakenly subjectively billed for some duplicate transactions.
Resolves #231
> [3.2] Do not log or subjective bill for duplicate trxs

- plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp
The lack of an initializer for `version` was leading to a use before set warning in the trace_api_plugin tests
https://github.com/AntelopeIO/leap/blob/631b3bf914afb279097f39702a5ed5c7b9d1f712/plugins/trace_api_plugin/test/test_trace_file.cpp#L436-L437
Our general practice is to initialize PODs in structs, so let's do that here.
> [3.2] initialize slice_directory::index_header::version

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/testing/tester.cpp
- plugins/producer_plugin/producer_plugin.cpp
Added total block elapsed time and total block time to `Produced block` log output. Updated scheduled transaction trace `elapsed` to include more of the execution time. Renamed `Received block` log output `conf:` to `confirmed:` to match `Produced block` log output. Includes a bit of refactoring for calculation of cpu/elapsed/time since these are now calculated for produced blocks where the time is spread out over block production time.
```
info  2022-10-11T15:53:27.917 nodeos    producer_plugin.cpp:502       on_incoming_block    ] Received block 9668c6a107d78117... #18 @ 2022-10-11T15:53:28.000 signed by eosio [trxs: 11, lib: 17, confirmed: 0, net: 8304, cpu: 5711, elapsed: 3853, time: 8394, latency: -82 ms]
```
Resolves #312
> [3.2] Update produced block log output.

- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Revert to `3.1` behavior of always returning `application/json` for all http responses including errors. The non-JSON responses came in as part of the boost beast backport https://github.com/AntelopeIO/leap/pull/22.
Example:
```
curl -v http://localhost:8888/hi
*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /hi HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Server: Boost.Beast/266
< Access-Control-Allow-Origin: *
< Content-Length: 212
<
* Connection #0 to host localhost left intact
{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown …
```
> [3.2] Return application/json for all http responses including errors

- unittests/api_tests.cpp
Allow 10ms instead of 2ms for checktime to trigger and trace to be created. The 2ms time was too tight for some runs.
Resolves #252
> [3.1] Test fix: api_tests checktime_pause_block_deadline_not_extended_test

- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Revert to `3.1` behavior of always returning `application/json` for all http responses including errors. The non-JSON responses came in as part of the boost beast backport https://github.com/AntelopeIO/leap/pull/22.
Example:
```
curl -v http://localhost:8888/hi
*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /hi HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Server: Boost.Beast/266
< Access-Control-Allow-Origin: *
< Content-Length: 212
<
* Connection #0 to host localhost left intact
{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown …
```
> [3.2 -> main] Return application/json for all http responses including errors

- unittests/api_tests.cpp
Allow 10ms instead of 2ms for checktime to trigger and trace to be created. The 2ms time was too tight for some runs.
Resolves #252 
Merges #322 into `release/3.2`
> [3.1 -> 3.2] Test fix: api_tests checktime_pause_block_deadline_not_extended_test

- unittests/api_tests.cpp
Allow 10ms instead of 2ms for checktime to trigger and trace to be created. The 2ms time was too tight for some runs.
Resolves #252 
Merges #322 & #338 into `release/3.2`
> [3.2 -> main] Test fix: api_tests checktime_pause_block_deadline_not_extended_test

- libraries/state_history/include/eosio/state_history/log.hpp
Fix log statement so output includes value of `remaining`.
Resolves #346
> [3.1] SHiP Fix log output

- libraries/state_history/include/eosio/state_history/log.hpp
Fix log statement so output includes value of `remaining`.
Resolves #346 
Merges #347 into `release/3.2`
> [3.1 -> 3.2] SHiP Fix log output

- libraries/state_history/include/eosio/state_history/log.hpp
Fix log statement so output includes value of `remaining`.
Resolves #346 
Merges #347 & #348 into `main`
> [3.2 -> main] SHiP Fix log output

- tests/performance_tests/CMakeLists.txt
- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
Create script and adapt existing scripts to do a binary search of tps range at low test duration with primitive scoring algorithm to find where Transfer Transactions Per Second (TPS) seems to be topping out.  Then do a longer duration run at the discovered TPS.
Performance Test Results Report reports the results of the initial short duration test binary search to zero in on max TPS as well as the follow-on longer running tests to determine if the max TPS was sustainable and zero in on the true max.
**New** Arguments for control of `performance_test`:
- `--max-tps-to-test` - The max target transfers realistic as ceiling of test range, default=50000
- `--test-iteration-duration-sec` - The duration of transfer trx generation for each iteration of the test during the initial search (seconds), …
> [PH] TPS Scenario Runner

- plugins/state_history_plugin/state_history_plugin.cpp
Store initial chain state on startup if `state_history_plugin` chain state log is empty. For example, if starting from a snapshot or if first time started with ` --chain-state-history` option. This storage will happen in `state_history_plugin` `plugin_startup` before `net_plugin` `plugin_startup` posted started runs. This will result in the complete storage of chain state in SHiP state log before any `net_plugin` connections are attempted.
Note this changes the behavior of SHiP storage of initial chain state deltas. The chain state deltas are stored in the chain state log associated with the head block at startup instead of the first received block after startup.
Example result from starting from a snapshot:
```
{ "get_status_result_v0":
{
"head": {
"block_num": 267988579,
"block_id": …
```
> [4.0] SHiP: Store initial chain state on startup if state_history_plugin chain state log is empty

- programs/leap-util/actions/blocklog.cpp
- programs/leap-util/actions/blocklog.hpp
This PR addresses following issues:
- flags and options made applicable to actual subcommands using them
- "default" behavior of printing log changed to a subcommand print-log. Default handler of parent subcommand "block-log" eliminated
- simplified and unified callbacks and error handling for return codes and exceptions
- re-enabled (and tested) smoke-test subcommand
- few other minor fixes
> [3.2] Block-log leap-util subcommand refactoring

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
Remove `skip_recording` optimization of transactions in dedup list when replaying. The optimization provides little real-world measurable difference, see #297, but can cause differences if replay is interrupted, see #291 for details.
Resolves #291
> [3.1] Remove replay optimization that skips recording transactions in dedup list

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
Remove `skip_recording` optimization of transactions in dedup list when replaying. The optimization provides little real-world measurable difference, see #297, but can cause differences if replay is interrupted, see #291 for details.
Resolves #291 
Merges #356 into `release/3.2`
> [3.1 -> 3.2] Remove replay optimization that skips recording transactions in dedup list

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
Remove `skip_recording` optimization of transactions in dedup list when replaying. The optimization provides little real-world measurable difference, see #297, but can cause differences if replay is interrupted, see #291 for details.
Resolves #291 
Merges #356 & #365 into `main`
> [3.2 -> main] Remove replay optimization that skips recording transactions in dedup list

- .gitignore
- README.md
- docs/00_install/01_build-from-source/index.md
- docs/00_install/index.md
From [issue 132](https://github.com/AntelopeIO/leap/issues/132), this pull request updates the build instructions in the `README.md` to be more approachable to new users or novices who wish to build from source without much Linux or BASH experience. [Here](https://github.com/AntelopeIO/leap/blob/13863af69f02d685d82a08a2e198e16fd6d8839e/README.md) is what it looks like now. It may be easier to look over the new document than to try to look through the pull request diff.
I felt motivated so I also improved grammar and readability of the `README.md` overall, simplified the section headers, expanded the explanation of pinned vs. unpinned builds, expanded the section explaining the test suites, and various other things. I was careful to preserve the specific recommendations and commands added …
> 3.2 - Complete Build Instructions + Other README Updates

- CMakeModules/EosioTesterBuild.cmake.in
Resolve https://github.com/AntelopeIO/leap/issues/370.
Update `libfc` path in `CMakeModules/EosioTesterBuild.cmake.in` to match the new location after FC demodulation.
This is required for CDT and System Contracts to build integration tests.
Before the fix, building CDT' integration_tests had following error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libfc
linked by target "integration_tests" in directory /Users/lh/work/cdt-fc-test/tests/integration
```
> [ main ] update libfc path in EosioTesterBuild.cmake.in for building integration tests in CDT and System Contracts

- .gitignore
- README.md
- docs/00_install/01_build-from-source/index.md
- docs/00_install/index.md
From [issue 132](https://github.com/AntelopeIO/leap/issues/132), this pull request updates the build instructions in the `README.md` to be more approachable to new users or novices who wish to build from source without much Linux or BASH experience. [Here](https://github.com/AntelopeIO/leap/blob/d45e97b5d1d7640ab5ca45c05daa763c64e08a1f/README.md) is what it looks like now. It may be easier to look over the new document than to try to look through the pull request diff.
I felt motivated so I also improved grammar and readability of the `README.md` overall, simplified the section headers, expanded the explanation of pinned vs. unpinned builds, expanded the section explaining the test suites, and various other things. I was careful to preserve the specific recommendations and commands added …
> Complete Build Instructions + Other README Updates

- plugins/net_plugin/net_plugin.cpp
Currently when a transaction is rejected due to too many transactions in progress, that message only gets logged in a "debug" logging level. Rather than spamming that message at a higher level, instead add a new message which will periodically be printed as long as transactions are being rejected.
In this implementation that is the first time a transaction is rejected due to too many transactions, and every time it happens at an interval of 1 second or more.
Resolves: https://github.com/AntelopeIO/leap/issues/351
> [3.1] Dropped trxs when overloaded logged as warning in nodeos

- tests/performance_tests/README.md
- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
Add start and end times to test reports.
Updated report examples to include start and end times. Cleaned up some of the report formatting.
Updated timestamped log directories to be in UTC so that all timestamps are easier to trace back to log files and timestamps therein.
> [PH] Report start end times for tests

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- unittests/snapshot_tests.cpp
Clear expired transactions before generating a snapshot or creating an integrity hash. The clear of expired transactions is limited to a deadline during block production, so it is possible there are uncleared transactions because the deadline was hit on the last call to clear. See #290 for more details.
Resolves #290 
Merges #366 into `release/3.2`
> [3.1 -> 3.2] Clear expired transactions before snapshot and integrity hash

- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test.py
This avoids a problem where the long running test max is outside the window previously dictated for binary search and incorrectly reporting `LongRunningMaxTpsAchieved` = 0.  Long Running max TPS should always be <= short running max tps, thus linearly decrementing search works well for this case.
In the general case, where `--max-tps-to-test` has been set well above achievable, this change adds one `--test-iteration-duration-sec` of time to the overarching test. In the case where it is successful it could save many cycles of time.  It also puts one data point in the results summary that is basically an optimistic execution showing at potential overload what the avg tps looks like.
Now that reports aren't always explicitly reordered to be alphabetical, put them in a general logical order …
> [PH] Performance Test - Long running Tests to use linear search

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- unittests/snapshot_tests.cpp
Clear expired transactions before generating a snapshot or creating an integrity hash. The clear of expired transactions is limited to a deadline during block production, so it is possible there are uncleared transactions because the deadline was hit on the last call to clear. See #290 for more details.
Resolves #290 
Merges #366 & #389 into `main`
> [3.2 -> main] Clear expired transactions before snapshot and integrity hash

- programs/cleos/main.cpp
- programs/leap-util/main.cpp
This addresses issue when cli command (such as leap-util or cleos) is being executed with missing/incorrect parameters. Prior behavior displayed error message and exited. This is changed to automatic display of help in a context of existing command/subcommand
Example:
```
bin/cleos system 
ERROR: RequiredError: A subcommand is required
Send eosio.system contract action to the blockchain.
Usage: bin/cleos system [OPTIONS] SUBCOMMAND
Options:
-h,--help                   Print this help message and exit
--help-all                  Show all help
Subcommands:
newaccount                  Create a new account on the blockchain with initial resources
regproducer                 Register a new producer
unregprod                   Unregister an existing producer
voteproducer                Vote for …
```
> [3.2] Changed default error handler to print help in cli apps by default

- tests/TestHarness/Node.py
- tests/performance_tests/performance_test_basic.py
Rather than waiting on empty blocks, instead wait for all transactions to appear in blocks. The number to determine is based on total transactions, with a fudge factor of 0.05 * TargetTPS additional blocks.
> [PH] Perf harness wait for transactions in block

- plugins/resource_monitor_plugin/include/eosio/resource_monitor_plugin/file_space_handler.hpp
When the resource monitor exceeds its configured threshold, log an error instead of a warning so it is clear that action is needed by the operator.
Resolves #235
> [3.1] Use error log instead of warning log when resource_monitor exceeds threshold

- plugins/resource_monitor_plugin/include/eosio/resource_monitor_plugin/file_space_handler.hpp
When the resource monitor exceeds its configured threshold, log an error instead of a warning so it is clear that action is needed by the operator.
Resolves #235 
Merges #400 into `release/3.1`
> [3.1 -> 3.2] Use error log instead of warning log when resource_monitor exceeds threshold

- programs/cleos/main.cpp
- programs/leap-util/main.cpp
This addresses issue when cli command (such as leap-util or cleos) is being executed with missing/incorrect parameters. Prior behavior displayed error message and exited. This is changed to automatic display of help in a context of existing command/subcommand
Example:
```
bin/cleos system 
ERROR: RequiredError: A subcommand is required
Send eosio.system contract action to the blockchain.
Usage: bin/cleos system [OPTIONS] SUBCOMMAND
Options:
-h,--help                   Print this help message and exit
--help-all                  Show all help
Subcommands:
newaccount                  Create a new account on the blockchain with initial resources
regproducer                 Register a new producer
unregprod                   Unregister an existing producer
voteproducer                Vote for …
```
> [3.2 -> main] Changed default error handler to print help in cli apps by default

- .github/workflows/label_new_issues.yaml
When a new issue is created and it's already assigned to a project, skip the triage action which labels the new issue and adds it to a project. The heuristic here is that if an issue is created already assigned to a project it likely means it has been dispositioned appropriately already.
Requires AntelopeIO/issue-project-labeler-workflow#2
Resolves #294
> don't triage new issues if they're already assigned to a project

- plugins/state_history_plugin/state_history_plugin.cpp
The call to a `session::close()` here leads to a threading violation: ship's network thread is still running at this time (i.e. `async_read()`/`async_write()` could be outstanding for a socket), and a `session::close()` will lead to a `socket::close()` which then could potentially access the socket simultaneously from two threads.
At first I was planning to wrap this one line in a `my->ctx.post()` but this call seems unnecessary: we can simply let the various dtors fire in their proper order. Once `state_history_plugin::plugin_shutdown()` returns there is no separate thread running thus no handlers are outstanding. Then `state_history_plugin` dtor will be fired which will destroy `sessions`, which then destroys the `session_set` which then destroys all the `session`s. This will cause the …
> [3.2] fix threading on state_history shutdown leading to hung nodeos shutdown

- package.cmake
Packages in the `CPACK_DEBIAN_DEV_PACKAGE_DEPENDS` variable should be separated by commas and not semicolon.
> CPack: fix separator in depends field of debian dev pacakge.

- package.cmake
This is a backport to 3.1 of #379. leap-dev.deb is only semi-supported and thus was only being tested in CI on Ubuntu 20.04. Turns out the older cmake in Ubuntu 18.04 did not handle the syntax being used for generating leap-dev.deb's dependencies. This change resolves the syntax to be more in alignment with documented cmake behavior.
Since the original defect was classified as a bug, this change is being backported to stable releases.
> [3.1] CPack: fix separator in depends field of debian dev pacakge

- package.cmake
This is a backport to 3.1 of #379. leap-dev.deb is only semi-supported and thus was only being tested in CI on Ubuntu 20.04. Turns out the older cmake in Ubuntu 18.04 did not handle the syntax being used for generating leap-dev.deb's dependencies. This change resolves the syntax to be more in alignment with documented cmake behavior.
Since the original defect was classified as a bug, this change is being backported to stable releases.
> [3.1] CPack: fix separator in depends field of debian dev pacakge 

- package.cmake
This is a backport to 3.2 of #379 via 3.1 merge of #428. leap-dev.deb is only semi-supported and thus was only being tested in CI on Ubuntu 20.04. Turns out the older cmake in Ubuntu 18.04 did not handle the syntax being used for generating leap-dev.deb's dependencies. This change resolves the syntax to be more in alignment with documented cmake behavior.
Since the original defect was classified as a bug, this change is being backported to stable releases.
> [3.1 -> 3.2] CPack: fix separator in depends field of debian dev pacakge

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- programs/keosd/main.cpp
- programs/nodeos/main.cpp
Prior to Leap 3.2, the HTTP server would respond with `Server: WebSocket++/0.7.0`. In 3.2, the response became `Server: Boost.Beast/330` (or potentially some other number based on boost version being used).
Instead, we can set this to the nodeos version, so the response is something like `Server: nodeos/v3.2.0-rc2`. Besides being more accurate, this may help troubleshoot issues when a user isn't sure what nodeos version they are communicating with. But there is also a school of thought that a server shouldn't reveal too much about itself for security reasons.
Would resolve #378
> [3.2] change the HTTP Server header to be nodeos/keosd version

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- programs/keosd/main.cpp
- programs/nodeos/main.cpp
This the main merge of #438
> Prior to Leap 3.2, the HTTP server would respond with `Server: WebSocket++/0.7.0`. In 3.2, the response became `Server: Boost.Beast/330` (or potentially some other number based on boost version being used).
> 
> Instead, we can set this to the nodeos version, so the response is something like `Server: nodeos/v3.2.0-rc2`. Besides being more accurate, this may help troubleshoot issues when a user isn't sure what nodeos version they are communicating with.
Resolves #378
> [3.2 -> main] change the HTTP Server header to be nodeos/keosd version

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
Add arguments to allow perf harness to control whether it deletes logs from the test scenarios (since default will be to generate and keep logs)
Performance Harness should simply implement its own command line argument for keeping logs of the test rather than overload the Regression Test `--keep-logs` flag like it is doing now.
Also save off low level artifacts sitting in `var/` and `etc/` from each test run for debugging purposes.
> [PH] Default perf harness to saving logs

- tests/performance_tests/launch_transaction_generators.py
- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
Updates to `launch_transaction_generators.py`:
1.  Support dynamic lists for account names and account private keys in similar fashion to how `trx_generator` is handling currently for extensibility.
2. Refactor to support use as an import module. This will allow returning configuration items back to caller.
3. Refactor to provide calculated configuration items to be passed back to the caller (num generators it will instantiate and list of TPS each generator will send) to allow validation in report as well as remove duplication of calculation.
> [PH] Launch Trx Generators updates

- tests/trx_finality_status_test.py
The fix #106 did not update the `present` flag to `validateTrxState` function for the new state when hitting the condition of #106.
The tag of #419 in the commit messages was a typo, should be #409.
Resolves #409 
Merges #441 into `release/3.2`
> [3.1 -> 3.2] Fix test failure due to trx hitting near end of block production time

- tests/performance_tests/README.md
- tests/performance_tests/launch_transaction_generators.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
For single producer nodes, need to override defaults either dynamically or hard-coded for the following features:
- last-block-cpu-effort-percent → 100
- cpu-effort-percent → 100
- last-block-time-offset-us → 0 
- produce-time-offset-us → 0
- signature-cpu-billable-pct → 0
Also, update docs for launch_transaction_generators.py changes that were missed in earlier revisions.
> [PH] Update producer node configurations for performance

- programs/leap-util/CMakeLists.txt
- programs/leap-util/actions/blocklog.cpp
- programs/leap-util/actions/blocklog.hpp
- programs/leap-util/actions/snapshot.cpp
- programs/leap-util/actions/snapshot.hpp
- programs/leap-util/actions/subcommand.cpp
- programs/leap-util/actions/subcommand.hpp
- programs/leap-util/main.cpp
This PR adds the following subcommand:
```
bin/leap-util snapshot to-json --help
convert snapshot file to json format
Usage: bin/leap-util snapshot to-json [OPTIONS]
Options:
-h,--help              Print this help message and exit
--help-all             Show all help
-i,--input-file TEXT REQUIRED
snapshot file to convert to json format, writes to <file>.json if output file not specified (tmp state dir used), and exit.
-o,--output-file TEXT  the file to write the output to (absolute or relative path).  if not specified then output is to stdout.
```
> [4.0] Added snapshot to-json subcommand to leap-util

- tests/performance_tests/CMakeLists.txt
Remove --dump-error-detail arg now that logs are automatically collected during CICD runs.  Keeps the output in CICD from being unmanageable.
> [PH] Remove --dump-error-detail test arg

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
`boost::beast::string_view`'s underlying implementation seems to have changed in boost 1.81. It is now `boost::core::string_view` where as previously it was a `boost::string_view` (in the `utility` directory). This new impl doesn't have `to_string()` so refactor this code to do the conversion to `std::string` differently. This seems to work due to both impls have something like
```c++
//boost::string_view
template<typename Allocator>
explicit operator std::basic_string<charT, traits, Allocator>() const {
return std::basic_string<charT, traits, Allocator>(begin(), end());
}
```
and
```c++
//boost::core::string_view
template<class A> operator std::basic_string<Ch, std::char_traits<Ch>, A>() const
{
return std::basic_string<Ch, std::char_traits<Ch>, A>( data(), size() );
}
```
It'd be nice …
> [4.0] refactor `boost::beast::string_view` to `std::string` conversion for changes in boost 1.81

- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Provide the ability to configure:
* `--chain-threads CHAIN_THREADS` Number of worker threads in controller thread pool (default: 2)
* `--net-threads NET_THREADS` Number of worker threads in net_plugin thread pool (default: 2)
* `--producer-threads PRODUCER_THREADS` Number of worker threads in producer thread pool (default: 2)
> [PH] Add support for thread configs

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Provide the ability to configure:
* `--chain-state-db-size-mb CHAIN_STATE_DB_SIZE_MB`
Maximum size (in MiB) of the chain state database (default: 10240)
> [PH] Add argument to configure --chain-state-db-size-mb and default to 10GB

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Provide the ability to configure:
* `--database-map-mode {mapped,heap,locked}`
Database map mode ("mapped", "heap", or "locked").
In "mapped" mode database is memory mapped as a file.
In "heap" mode database is preloaded in to swappable memory and will use huge pages if available.
In "locked" mode database is preloaded, locked in to memory, and will use huge pages if available. (default: mapped)
Added logical cpu count to top level `performance_test.py` report.
> [PH] add database map mode

- programs/cleos/main.cpp
- tests/compute_transaction_test.py
This PR is created in anticipation of possible inclusion into `release/3.2`; it will not be merged into `release/3.2` unless it is decided to do so later today. If it is decided not to put into `release/3.2`, the PR will be discarded and the same changes will be put into `main` directly.
Resolve https://github.com/AntelopeIO/leap/issues/482
Currently `cleos push transaction --read-only` is used to send transactions to `compute_transaction` endpoint.  Those are not true read-only transactions. To avoid confusions when true read-only transactions are introduced, we plan to use `--read` for true read-only transaction endpoint, deprecate `--read-only`, and use `--dry-run` to send transactions to `compute_transaction` endpoint.
In addition, to prevent dry-run transactions from accidentally …
> [3.2] compute_transaction: add --dry-run, deprecate --read-only, and sign a transaction only when explicitly requested 

- programs/cleos/main.cpp
- tests/compute_transaction_test.py
This is a merge of https://github.com/AntelopeIO/leap/pull/483 from `release/3.2` to `main`.
Resolve https://github.com/AntelopeIO/leap/issues/482
Currently `cleos push transaction --read-only` is used to send transactions to `compute_transaction` endpoint.  Those are not true read-only transactions. To avoid confusions when true read-only transactions are introduced, we plan to use `--read` for true read-only transaction endpoint, deprecate `--read-only`, and use `--dry-run` to send transactions to `compute_transaction` endpoint.
In addition, to prevent dry-run transactions from accidentally being included in a block, `cleos` will change to not sign dry-run transactions by default, unless explicitly requested with `--sign-with` option. Behavior of transactions by `--read-only` is not …
> [3.2->main] compute_transaction: add --dry-run, deprecate --read-only, and sign a transaction only when explicitly requested

- plugins/net_plugin/net_plugin.cpp
Use correct logger for log of too many trxs in progress in net_plugin.
Resolves #485
> [3.1] Use net_plugin_impl logger instead of default logger

- plugins/net_plugin/net_plugin.cpp
Use correct logger for log of too many trxs in progress in net_plugin.
Resolves #485 
Merges #486 into `release/3.2`
> [3.1 -> 3.2] Use net_plugin_impl logger instead of default logger

- plugins/net_plugin/net_plugin.cpp
Use correct logger for log of too many trxs in progress in net_plugin.
Resolves #485 
Merges #486 & #490 into `main`
> [3.2 -> main] Use net_plugin_impl logger instead of default logger

- tests/performance_tests/CMakeLists.txt
- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test_basic.py
Trx generator can fail to keep up with configured tps generation rate. Detect that failure case and report it as test failure.
Move transaction recvd and expected check to similar location and handling.
Rename launcherExitCodes to trxGenExitCodes for clarity.
> [PH] fix trx gen err detection

- tests/performance_tests/performance_test_basic.py
Add target tps number to test log dir name for ease of locating specific run.
currently log directories are timestamp only:
* `performance_test_basic/2022-11-16_22_26_48`
proposing the addition of the tps target to the dir name to make finding a specific run easier:
* `performance_test_basic/2022-11-16_22_26_48-50000`
* `performance_test_basic/2022-11-16_22_28_25-25000`
> [PH] log dir add tps target

- plugins/chain_plugin/chain_plugin.cpp
This PR adds validation of plugin configuration for deep-mind and will throw an exception if the plugin is not configured properly
Resolves #286
> [3.1] Added validation of plugin configuration for deep-mind

- plugins/chain_plugin/chain_plugin.cpp
This PR adds validation of plugin configuration for deep-mind and will throw an exception if the plugin is not configured properly
Thanks @systemzax for #503 
Resolves #286 
Merges #503 into `release/3.2`
> [3.1 -> 3.2] Added validation of plugin configuration for deep-mind

- plugins/chain_plugin/chain_plugin.cpp
This PR adds validation of plugin configuration for deep-mind and will throw an exception if the plugin is not configured properly
Thanks @systemzax for #503 
Resolves #286 
Merges #503 & #504 into `main`
> [3.2 -> main] Added validation of plugin configuration for deep-mind

- programs/cleos/do_http_post_libcurl.cpp
Resolved https://github.com/AntelopeIO/leap/issues/511
`cleos` recently switched from openssl to libcurl. Any command requiring keys stopped working due to that. For example,
```
cleos create account eosio hello EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV -p eosio@active
Error 3110001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration!
Error Details:
Chain API plugin is not enabled
```
In `determine_required_keys` in `cleos/main.cpp` which has two curl calls
```
...
const auto& public_keys = call(wallet_url, wallet_public_keys);
...
const auto& required_keys = call(get_required_keys, get_arg);
```
Those two calls go to the same local host but with different ports (80 and 8888). But somehow libcurl uses the same port for both …
> Fixed broken cleos due to reuse of curl handle

- tests/TestHarness/Node.py
The payload object can be extremely long when printing out during verbose logging.  Rarely is the entire response needed for debugging.  However, the code is often useful when something goes wrong.  Reverse the order of code and payload so that, when trunctating printed responsed, the return code is always available.  Truncate the response to 1024 characters.
> [PH] Update response order and truncate when printing.

- tests/performance_tests/README.md
- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Add options to calculate recommended producer, chain, and net worker thread pool size.
Each plugin's option determines whether to calculate number of worker threads to use in the thread pool with options of: `none`, `lmax`, or `full`. In `none` mode, the default, no calculation will be attempted and default configured thread count will be used. In `lmax` mode, thread count will incrementally be tested until the performance rate ceases to increase with the addition of subsequent threads. In `full` mode thread count will incrementally be tested from 2..num logical processors, recording each performance and choosing the local max performance (same value as would be discovered in `lmax` mode). Useful for graphing the full performance impact of each available thread.
* `--calc-producer-threads …
> [PH] thread count recommendation tests

- tests/TestHarness/TestHelper.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Make use of ArgumentParser parents and groups.
This will greatly reduce work to bubble up arguments between scripts/modules.  Also brings clarity and grouping of arguments by use with group titles and descriptions.
Test Helper arguments can now be bubbled up to user scripts via direct access to the ArgumentParser.  Performance Test Basic makes use of Test Helper arguments.  Perfomance Test makes use of both Performance Test Basic and Test Helper arguments as well.
`./build/tests/performance_tests/performance_test.py -?` now prints:
```
usage: performance_test.py [-?] [-p P] [-n N] [-d D] [--nodes-file NODES_FILE]
[-s {mesh}] [--dump-error-details] [-v]
[--leave-running] [--clean-run]
[--tps-limit-per-generator TPS_LIMIT_PER_GENERATOR]
[--genesis GENESIS]
[--num-blocks-to-prune …
```
> [PH] argparse.ArgumentParser usage updates

- tests/nodeos_snapshot_diff_test.py
- tests/nodeos_startup_catchup.py
Fix calculation of avg transactions occurring during the steady state window to compare against min expected.
Resolves: https://github.com/AntelopeIO/leap/issues/523
> [4.0] nodeos_snapshot_diff_test fix

- tests/TestHarness/Node.py
Resolved https://github.com/AntelopeIO/leap/issues/529.
When an assert occurred in a transaction, `action_traces` could be empty in the transaction response. Test harness will crash if `action_traces` is accessed.
An example empty `action_traces` transaction response is
`{'transaction_id':  '3190cf67d3044a4e0043998d0c82f61cd57f430e5a3232154a295a72d7b0464e',                  'processed': {'id':  '3190cf67d3044a4e0043998d0c82f61cd57f430e5a3232154a295a72d7b0464e',                  'block_num': 246, 'block_time': '2022-12-01T19:52:43.500', 'producer_block_id':  None, 'receipt': None, 'elapsed': 161, 'net_usage': 0, 'scheduled': False,  'action_traces': [], 'account_ram_delta': None, 'except': {'code': 3040000,  'name': 'transaction_exception', 'message': 'Transaction exception', 'stack': …
> Fixed test harness crash when actiob_traces is empty

- tests/nodeos_forked_chain_test.py
There was a race condition on the kill of the bridge node at `defproducerk`. If `defproducerk` had just started producing then there was not enough time given for it to produce again. Add check if at `defproducerk` or `defproducerj` and wait for `defproduceri` before sending the shutdown which give it plenty of time before the `defproducerk` round.
Also removed a couple of waits that were not needed.
Resolves #430 
Merges #533 & #534 into ` main`
> [3.2 -> main] Test nodeos_forked_chain_test: Fix race on kill of bridge node

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
Added the ability to set a content type for an api in the http plugin.  The default is application/json, but now text/plain is also available.  
Changed prometheus_plugin api to be text/plain.
> Add text/plain content type to http_plugin

- plugins/http_plugin/http_plugin.cpp
Cleaner handling of shutdown in http_plugin.
Inspired by @spoonincode comment: https://github.com/AntelopeIO/leap/pull/537#discussion_r1039871174
> Handle shutdown of http_plugin lifetime

- plugins/http_plugin/http_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/trace_api_plugin/store_provider.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
There is no need to run the `trace_api_plugin` on shutdown.
Add logging of exit from `http_plugin`, `producer_plugin`, and `trace_api_plugin` to help debug #535.
Resolves #535 (This likely does not actually resolve the issue, but unless it happens again having this issue open is not helpful.)
> [3.1] Do not run maintenance task on shutdown

- plugins/http_plugin/http_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/trace_api_plugin/store_provider.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
There is no need to run the `trace_api_plugin` on shutdown.
Add logging of exit from `http_plugin`, `producer_plugin`, and `trace_api_plugin` to help debug #535.
Resolves #535 (This likely does not actually resolve the issue, but unless it happens again having this issue open is not helpful.)
Merges #541 into `release/3.2`
> [3.1 -> 3.2] Do not run maintenance task on shutdown

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/wallet_api_plugin/wallet_api_plugin.cpp
Users sometimes hit the default 30ms issue with timeouts when using `keosd` due to the default `http-max-response-time-ms` 30ms. Setting contracts or ABI can often take longer than 30ms to parse in `keosd`. This error is confusing to users and often hard to track down what is going wrong. Also `keosd` is meant to only be run locally and not provided as a service.
This PR makes `http-max-response-time-ms` unlimited for `keosd`.
Also includes a bit of cleanup around exception handling in `beast_http_session`.
Resolves #230
> Set keosd max http response time to unlimited

- plugins/http_plugin/http_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/trace_api_plugin/store_provider.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
There is no need to run the `trace_api_plugin` on shutdown.
Add logging of exit from `http_plugin`, `producer_plugin`, and `trace_api_plugin` to help debug #535.
Resolves #535 (This likely does not actually resolve the issue, but unless it happens again having this issue open is not helpful.)
Merges #541 & #559 into `main`
> [3.1 -> main] Do not run maintenance task on shutdown

- tests/TestHarness/Node.py
#96 Introduced a new `--time-limit` to `/v1/chain/get_table_rows` and defaulted it to 10ms. The `restart-scenarios-test-hard_replay.py` test failed because the get table call exceeded 10ms. Modified the test code to pass in a very large limit so that tests do not hit the 10ms limit.
Resolves #561
> [3.2] Fix Test: Specify a large time limit for cleos get table

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/http_plugin/include/eosio/http_plugin/common.hpp
This PR resolves #488.
Management of maximum `in_flight` bytes is updated:
- we remove the overly complicated `in_flight` struct which was not necessary. As a consequence we also don't allocate memory for it via make_shared.
- we make the `verify_max_bytes_in_flight` and `verify_max_requests_in_flight` pure verification functions, returning an error string in case of excess, and add a `send_busy_response` function to send the error response.
- when `max_bytes_in_flight` is exceeded, it means that we are processing incoming requests and enqueuing them via `http::async_write` faster than they can be written. As a result we want to stop enqueuing new writes using `send_response`. 
I have checked that the two http unit tests pass (see below), and also some basic calls using curl:
```
ctest -R …
```
> Update management of `in_flight` bytes in http_plugin

- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
Add a base set of metrics for to publish to Prometheus to the producer_plugin.
> Instrument producer_plugin for Prometheus

- libraries/chain/transaction_context.cpp
Modified the transaction deadline timer to include `subjective_cpu_bill_us` for cases where subjective CPU would limit the transaction deadline timer.
Resolves #329
> Include subjective cpu limit in trx deadline

- plugins/producer_api_plugin/producer.swagger.yaml
- spelling fixes
- added `subjective_cpu_leeway_us` to runtime options 
- added `more` option array returned from `get_account_ram_corrections`
- added return boolean to `paused`
- correct `201` return codes 
- `create_snapshot` has return schema previous was *Returns Nothing*
- corrected description for `get_whitelist_blacklist` `set_whitelist_blacklist`
- consolidates to `components` removed hanging `component` section
- moved common schemas to `components` section 
- removed empty `requestBody` 
- added `400` return codes as required by `redocly` linter
- Added version tags to clarify protocol version 
**NOTE** issue #547 will be closed after patching and updating openapi docs in 3.2 and main branches 
Related PR #572 - 3.2 release
> [3.1] Fixes Producer Plugin Schema Fixes and Better Alignment with OpenAPI spec

- programs/eosio-launcher/main.cpp
- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
In an effort to benchmark 2.0 and 2.1 nodeos some changes had to be made to accommodate the differences such as history_api_plugin being removed.
> [4.0] [PH] enable compatibility for 2.0 and 2.1 nodeos on performance tests.

- plugins/producer_api_plugin/producer.swagger.yaml
- spelling fixes
- added subjective_cpu_leeway_us to runtime options
- added more option array returned from get_account_ram_corrections
- added return boolean to paused
- set text/plain return type for paused return code
- correct 201 return codes
- create_snapshot has return schema previous was Returns Nothing
- corrected description for get_whitelist_blacklist set_whitelist_blacklist
- consolidates to components removed hanging component section
- moved common schemas to components section
- removed empty requestBody
- added 400 return codes as required by redocly linter
- Added version tags to clarify protocol version
**NOTE** issue https://github.com/AntelopeIO/leap/issues/547 will be closed after patching and updating openapi docs in 3.2 and main branches
Related PR …
> [3.2] Fixes Producer Plugin Schema Fixes and Better Alignment with OpenAPI spec

- tests/TestHarness/Node.py
- tests/TestHarness/WalletMgr.py
- Adds better error output on failures.
- Adds `-f` force option to `pushMessage`
- Sets `keosd` to have very large timeout so when `--keep-running` is used the wallet doesn't auto-lock.
> Small Misc python test improvements

- tests/TestHarness/Cluster.py
Running `./tests/performance_tests/performance_test.py -p 5` with multiple producers causes Cluster.py to not launch. Indicate which node is running the trace_api_plugin so that account creation can be verified.
> Fix for mulit-producer run of performance test

- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/resource_limits.cpp
- libraries/chain/transaction_context.cpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- unittests/api_tests.cpp
- unittests/wasm_tests.cpp
Include in `tx_cpu_usage_exceeded` exception message information on which trx cpu limit was hit.
Includes #562 which should be merged first.
Resolves #330
> Include additional info in tx_cpu_usage_exceeded exceptions

- libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp
- libraries/libfc/test/network/test_message_buffer.cpp
- libraries/wasm-jit/Include/IR/Operators.h
- libraries/wasm-jit/Source/WASM/WASMSerialization.cpp
Fixing https://github.com/AntelopeIO/leap/issues/493.
Fixed undefined behavior revealed by valgrind. After fixes all mentioned issues are cleared out:
1.
```
valgrind nodeos -e -p eosio --data-dir /home/mikel/app/nodeos --plugin eosio::producer_plugin --plugin eosio::producer_api_plugin --plugin eosio::chain_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::state_history_plugin --contracts-console --disable-replay-opts --access-control-allow-origin=* --http-validate-host=false --verbose-http-errors --trace-history --chain-state-history --delete-all-blocks
(...)
==46508== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
2.
`valgrind /home/mikel/repo/leap/debug/plugins/chain_plugin/test/test_account_query_db`
Valgrind reports only issues …
> Fix undefined behavior - uninitialized variables revealed by valgrind

- tests/performance_tests/log_reader.py
- tests/performance_tests/log_reader_tests.py
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
- tests/performance_tests/read_log_data.py
Replaces instances of os.path with corresponding Path and PurePath. str conversion is necessary for use with sys.path
> [PH] Replace usage of os.path with Path and PurePath

- plugins/net_plugin/net_plugin.cpp
The fix https://github.com/eosnetworkfoundation/mandel/pull/756 did not address that `no_retry` is also redundantly checked in `connect`. This PR removes the duplicate check since `connect` is only called from `resolve_and_connect` where the `no_retry` is already verified.
Resolves #605
Merges #606 into `release/3.2`
> [3.1 -> 3.2] Attempt connection retry for duplicate connections

- plugins/net_plugin/net_plugin.cpp
The fix https://github.com/eosnetworkfoundation/mandel/pull/756 did not address that `no_retry` is also redundantly checked in `connect`. This PR removes the duplicate check since `connect` is only called from `resolve_and_connect` where the `no_retry` is already verified.
Resolves #605
Merges #606 & #615 into `main`
> [3.2 -> main] Attempt connection retry for duplicate connections

- libraries/chain/include/eosio/chain/wasm_interface.hpp
- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- libraries/chain/wasm_interface.cpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- unittests/api_tests.cpp
Adds new `is_code_cached` method to `wasm_interface` for use by tests to check if the code for a given account has been cached. 
Resolves #260
> Tests: Add is_code_cached and use in tests to verify

- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_subjective_billing.cpp
Subjectively bill for failed transactions during block production since failed transaction time not part of objective account cpu billing.
Includes removal of dead-code in `subjective_billing` that should have been removed as part of #414.
Resolves #551 
Related #414
> Subjectively bill for failed transactions during block production

- libraries/chain/include/eosio/chain/thread_utils.hpp
- libraries/chain/thread_utils.cpp
- plugins/state_history_plugin/state_history_plugin.cpp
Backport of `state_history_plugin` fixes: https://github.com/EOSIO/eos/pull/10608
From the backport:
- Create an additional thread for all ship network communication. This thread already existed in release/3.2 but was not used. See https://github.com/AntelopeIO/leap/issues/593.
- Fix bug where state history plugin would send blocks with block_num smaller than the client requests when the state history block head is behind the block head of the client.
Additional changes:
- Remove `session_manager_t` and use post to main thread so `session_set` is only accessed from main thread.
- Use `named_thread_pool` to simplify SHiP thread. Older versions of boost do not provide an `acceptor` that takes a `strand` in constructor, so rely on implicit strand of single thread running `io_context` which …
> [3.2] Backport SHiP fixes from eosio/eos release/2.2.x

- libraries/chain/include/eosio/chain/thread_utils.hpp
- libraries/chain/thread_utils.cpp
- plugins/state_history_plugin/state_history_plugin.cpp
Backport of `state_history_plugin` fixes: https://github.com/EOSIO/eos/pull/10608
From the backport:
- Create an additional thread for all ship network communication. This thread already existed in release/3.2 but was not used. See https://github.com/AntelopeIO/leap/issues/593.
- Fix bug where state history plugin would send blocks with block_num smaller than the client requests when the state history block head is behind the block head of the client.
Additional changes:
- Remove `session_manager_t` and use post to main thread so `session_set` is only accessed from main thread.
- Use `named_thread_pool` to simplify SHiP thread. Older versions of boost do not provide an `acceptor` that takes a `strand` in constructor, so rely on implicit strand of single thread running `io_context` which …
> [3.2 -> main] Backport SHiP fixes from eosio/eos release/2.2.x

- libraries/chain/controller.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_subjective_billing.cpp
- unittests/block_tests.cpp
- unittests/forked_tests.cpp
- unittests/unapplied_transaction_queue_tests.cpp
Interrupt speculative `start_block` when a block is received, after the block header has been validated, so it can be immediately processed even when there is a backlog of pending transactions.
- Forkdb made thread-safe.
- Block header validation now done on net threads instead of producer threads when previous block already processed.
Resolves #525 
Resolves #517 
Merges #543 into `release/3.2`
> [3.1 -> 3.2] Interrupt speculative start_block when a block is received

- libraries/chain/controller.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_subjective_billing.cpp
- unittests/block_tests.cpp
- unittests/forked_tests.cpp
- unittests/unapplied_transaction_queue_tests.cpp
Interrupt speculative `start_block` when a block is received, after the block header has been validated, so it can be immediately processed even when there is a backlog of pending transactions.
- Forkdb made thread-safe.
- Block header validation now done on net threads instead of producer threads when previous block already processed.
Resolves #525 
Resolves #517 
Merges #543 & #648 into `main`
> [3.2 -> main] Interrupt speculative start_block when a block is received

- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/nodeos_contrl_c_test.py
- tests/nodeos_snapshot_diff_test.py
- tests/nodeos_startup_catchup.py
- tests/trx_generator/trx_generator.cpp
Refactor - move `launchTrxGenerators` from `Node.py` to `Cluster.py` where it fits better.
Add `waitForTrxGeneratorsSpinup` function which allows tests to wait for initial trx from each generator to appear in a block.  This allows the tests to sync on the trx generators spinning up and knowing that trxs are flowing before proceeding with tests.
Update tests that used `launchTrxGenerators` for the refactor and to use the `waitForTrxGeneratorsSpinup` function.
`trx_generator` now logs first transaction it is preparing to send right before sending it to allow synchronization by tests without influencing its generation rate since it occurs prior only on initial trx and prior to initial trx send.
Resolves: #637
> Working to fix nodeos_snapshot_diff_test by sync on trx gen startup

- libraries/chain/include/eosio/chain/wast_to_wasm.hpp
Some fixes when compiling with gcc13 (really libstdc++13 I take it). Seems stdint.h is no longer being included in some standard header, and these files missed including it as they should.
Needs AntelopeIO/abieos#17
> add missing include statements for gcc13 (libstdc++13)

- tests/nodeos_forked_chain_test.py
Fix #533 should have updated `preKillBlockNum` & `preKillBlockProducer` as these are used in the validation calculation.
Ran 20 times without error in CI/CD:
https://github.com/AntelopeIO/leap/actions/runs/4016264242
https://github.com/AntelopeIO/leap/actions/runs/4016267469
Resolves #631
> [3.1] Test fix: nodeos_forked_chain_lr_test

- tests/nodeos_forked_chain_test.py
Fix #533 should have updated `preKillBlockNum` & `preKillBlockProducer` as these are used in the validation calculation.
Ran 20 times without error in CI/CD:
https://github.com/AntelopeIO/leap/actions/runs/4016264242
https://github.com/AntelopeIO/leap/actions/runs/4016267469
Merges #677 into `release/3.2` via merge of `release/3.1`
Resolves #631
> [3.1 -> 3.2] Test fix: nodeos_forked_chain_lr_test

- tests/nodeos_forked_chain_test.py
Fix #533 should have updated `preKillBlockNum` & `preKillBlockProducer` as these are used in the validation calculation.
Ran 20 times without error in CI/CD:
https://github.com/AntelopeIO/leap/actions/runs/4016264242
https://github.com/AntelopeIO/leap/actions/runs/4016267469
Merges #677 & #670 into `main` via merge of `release/3.2`
Resolves #631
> [3.2 -> main] Test fix: nodeos_forked_chain_lr_test

- tests/performance_tests/log_reader.py
- tests/performance_tests/performance_test_basic.py
Adds some additional tracking of block time, and stores it and latency inside as CSV for later consumption.
> [PH] Performance Harness csv improvements

- plugins/net_plugin/net_plugin.cpp
Remove the +1 to the block latency calculation otherwise even 0ms latency indicates 1 block latency instead of 0. The +1 makes the comparisons of `head` and `msg.head` in the `if-else` off by 1 when there is no latency. 
Added additional logging so that issues like #588 are easier to debug.
Before:
```
debug 2022-12-21T21:54:29.938 net-3     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 43 127.0.0.1:52370] Network latency is 0ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
```
After:
```
debug 2023-01-31T00:27:27.386 net-0     net_plugin.cpp:1795           recv_handshake       ] ["localhost:9878 - 978ab39" - 1 127.0.0.1:54362] Network latency is 0ms, 0 blocks discrepancy by network latency, 0 blocks …
```
> [3.1] net_plugin improve block latency calculation

- plugins/net_plugin/net_plugin.cpp
Remove the +1 to the block latency calculation otherwise even 0ms latency indicates 1 block latency instead of 0. The +1 makes the comparisons of `head` and `msg.head` in the `if-else` off by 1 when there is no latency. 
Added additional logging so that issues like #588 are easier to debug.
Before:
```
debug 2022-12-21T21:54:29.938 net-3     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 43 127.0.0.1:52370] Network latency is 0ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
```
After:
```
debug 2023-01-31T00:27:27.386 net-0     net_plugin.cpp:1795           recv_handshake       ] ["localhost:9878 - 978ab39" - 1 127.0.0.1:54362] Network latency is 0ms, 0 blocks discrepancy by network latency, 0 blocks …
```
> [3.1 -> 3.2] net_plugin improve block latency calculation

- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/http_plugin/include/eosio/http_plugin/macros.hpp
- plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
New interface between prometheus and instrumented plugins.  
Now, prometheus will register a listener with instrumented plugins.  Instrumented plugins will 'batch' updates and call back the prometheus listener.  
The listener that prometheus passes to the instrumented plugins is a lambda that posts another lambda to a prometheus strand.  The lambda that is posted to the prometheus strand will update the prometheus data model.  The updating of the data model is not implemented in this PR.
One open issue is where can we use 'move' rather than 'copy' semantics.
> First cut at a more message based interface between prometheus and instrumented plugins

- libraries/libfc/include/fc/exception/exception.hpp
- plugins/producer_plugin/producer_plugin.cpp
Log failed transaction exception details:
For example:
```
debug 2023-02-03T20:52:13.122 nodeos    producer_plugin.cpp:2037      push_transaction     ] Failed 3040000 trx, auth: eosio.wrap, prev billed: 0us, ran: 274us, id: 84ff2165389f800d26f5f47117ed494d30d6e4ebf797edd7ffdda80c07bcaf35, except: {"code":3040000,"name":"transaction_exception","message":"Transaction exception","stack":[{"context":{"level":"error","file":"transaction_context.cpp","line":796,"method":"validate_referenced_accounts","hostname":"","thread_name":"nodeos","timestamp":"2023-02-03T20:52:13.122"},"format":"action's authorizing actor '${account}' does not exist","data":{"account":"eosio.wrap"}}]}
```
Resolves #548
> Log exception details for failed transactions

- plugins/producer_plugin/producer_plugin.cpp
This makes importing the log message into external systems (like elasticsearch for example) alot easier :)
> Producer Plugin: Add block number to account_failures::report()

- libraries/chain/controller.cpp
Fix issue with dirty db being reported as genesis not found instead of dirty db.
3.1 version of this includes a back-port of https://github.com/eosnetworkfoundation/mandel/pull/647 which didn't make it into 3.1.
Resolves #695 
Resolves #565
> [3.1] Fix reporting of dirty db

- libraries/chain/controller.cpp
Fix issue with dirty db being reported as genesis not found instead of dirty db.
Merges `release/3.1` into `release/3.2` including #700.
Resolves #695 
Resolves #565
> [3.1 -> 3.2] Fix reporting of dirty db

- libraries/chain/controller.cpp
Fix issue with dirty db being reported as genesis not found instead of dirty db.
Merges `release/3.2` into `main` including #700 & #708
Resolves #695 
Resolves #565
> [3.2 -> main] Fix reporting of dirty db

- README.md
- scripts/install_deps.sh
Was already in unpinned build instructions but missing for pinned builds and overarching requirements in readme.
Fixes: #711
> GH-711 Update dependencies to include numpy.

- plugins/resource_monitor_plugin/include/eosio/resource_monitor_plugin/file_space_handler.hpp
- plugins/resource_monitor_plugin/resource_monitor_plugin.cpp
- plugins/resource_monitor_plugin/test/CMakeLists.txt
- plugins/resource_monitor_plugin/test/test_add_file_system.cpp
- plugins/resource_monitor_plugin/test/test_monitor_loop.cpp
- plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp
- plugins/resource_monitor_plugin/test/test_threshold.cpp
Add new option to `resource_monitor_plugin`
* `--resource-monitor-space-absolute-gb` - "Absolute threshold in gibibytes of remaining space; applied to each monitored directory. If remaining space is less than value for any monitored directories then threshold is considered exceeded. Overrides resource-monitor-space-threshold value."
* Log space threshold warning on shutdown when exceeded.
```
error 2023-02-10T15:23:54.009 resmon    file_space_handler.hpp:74     is_threshold_exceede ] Space usage warning: /home/heifner/ext/leap/cmake-build-debug/bin/t/blocks's file system exceeded threshold 240 GiB, available: 237 GiB, Capacity: 1006 GiB, shutdown_available: 240 GiB
error 2023-02-10T15:23:54.010 resmon    file_space_handler.hpp:135    space_monitor_loop   ] Gracefully shutting down, …
```
> Add absolute value threshold to resource monitor

- libraries/chain/abi_serializer.cpp
- libraries/chain/include/eosio/chain/abi_serializer.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- plugins/trace_api_plugin/abi_data_handler.cpp
- plugins/trace_api_plugin/include/eosio/trace_api/abi_data_handler.hpp
- plugins/trace_api_plugin/test/test_data_handlers.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
- tests/chain_plugin_tests.cpp
- tests/test_chain_plugin.cpp
- unittests/abi_tests.cpp
- unittests/bootseq_tests.cpp
- unittests/delay_tests.cpp
- unittests/eosio.token_tests.cpp
- unittests/eosio_system_tester.hpp
- unittests/wasm_tests.cpp
Move the abi serialization of `signed_block` for `/v1/chain/get_block` off the main thread. Also the abi cache used in this implementation actually provides a nice performance improvement. See comments on #677. 
This PR also uses the min of `--http-max-response-time-ms` &  `--abi-serializer-max-time-ms` for the deadline of `get_block` instead of running for the full `--abi-serializer-max-time-ms` before checking `--http-max-response-time-ms`.
Also includes reduction of string copies in `abi_serializer`.
Resolves #677
> Move get_block abi serialization off the main thread

- plugins/state_history_plugin/state_history_plugin.cpp
Do not reset `socket_stream` in `close` as it can still be in use until completely closed.
Branch tested and verified stable by @cc32d9. 
Merges `release/3.2` into `main` including #714 
Resolves #669
> [3.2 -> main] Fix SHiP stability

- libraries/testing/contracts.cpp.in
Fixes issue 2 from https://github.com/AntelopeIO/leap/issues/494
**Issue 2**: `std::char_traits::length` was looking for null terminator in the abi vector, which wasn't there, causing an invalid read. Switching from INCBIN to INCTXT helped.
**Issue 1**:
I think it is false positive and can be ignored.
What happens in unit test:
1. Blockchain is initialized.
2. It is written to a memory mapped file (shared_memory.bin) and saved.
3. File with blockchain is loaded again (in tester.cpp:283) to a memory mapped file.
4. Exception is thrown because of failed transaction and blockchain is flushed again to shared_memory.bin.
5. At this point valgrind warns there is uninitialized data in the blockchain which is being dumped to a file.
Why I think it is false positive?
Because all the data is …
> Change INCBIN to INCTXT for abi in tests to fix invalid read

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
Log `rawCmdLine ` using `' '.join(sys.argv[0:])` in order to capture the command line used to start the test run
`"rawCmdLine ": "tests/performance_tests/performance_test.py --test-iteration-duration-sec 10 --final-iterations-duration-sec 30 --calc-producer-threads lmax --calc-chain-threads lmax --calc-net-threads lmax"`
> [PH] Capture Full Command Line Argument String in Report

- unittests/api_tests.cpp
Provide more time for the test to cache the contract.  It can fail before it gets to loading the wasm module with the same deadline exception. Other test cases use 10ms instead of 3ms for the tolerance for caching the contract.
Resolves #721
> Test: Provide a bit more time for the contract to be cached.

- libraries/libfc/include/fc/io/json.hpp
- libraries/libfc/src/io/json.cpp
Some low hanging fruit optimizations to JSON parsing until https://github.com/AntelopeIO/leap/issues/299 can be worked.
* Use boost stream and `std::string` instead of `std::stringstream`
* One test case of `setcode` of the `eosio.system` contract time for parsing the incoming JSON went from 3.5ms to 1.4ms.
> Optimize json parsing

- libraries/chain/wasm_interface.cpp
Just including this header on modern boost versions gives a warning
> #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
just remove this include: it's unused.
> remove unused boost/bind.hpp include that generates a warning

- libraries/chain/abi_serializer.cpp
- libraries/chain/include/eosio/chain/abi_serializer.hpp
- plugins/chain_plugin/chain_plugin.cpp
The recent change to `abi_serializer` https://github.com/AntelopeIO/leap/pull/696 Specifically the change https://github.com/AntelopeIO/leap/pull/696/commits/62903c04ab510784e255e4e38d67fd7cb5e27ba6 caused existing test cases that use contract tester to not compile.
This PR reverts the changes to `abi_serializer` deprecated methods and changes `abi_serializer` constructor and `set_abi` to take `abi_def` by value instead of rvalue reference. This should allow existing users of contract tester to not have to update their test code.
Resolves #741
> Revert interface change of abi_serializer for tester

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Resolves #530.
These messages are showing up in leap 3.2 is because the implementation of the http_server changed in leap 3.2, including adding support for HTTP 1.1 Keep-Alive, which allows HTTP connections to persist for more than one request.
As a result, when the client closes the connection, the server is busy performing a read (waiting for the next request) which end with a `Connection reset by peer` error. This was reported as an error by mistake. This PR makes the http_plugin silently close its side of the connection.
> [3.2] Avoid logging errors when client disconnects after request (GH #530)

- libraries/libfc/include/fc/log/logger.hpp
- libraries/libfc/src/log/logger.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/http_plugin/http_plugin.cpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/resource_monitor_plugin/include/eosio/resource_monitor_plugin/file_space_handler.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
- programs/keosd/main.cpp
- programs/nodeos/main.cpp
During work on #659 the log of `EOS_ASSERT`:
```
error 2023-02-22T20:51:14.889 nodeos    state_history_plugin.c:284    on_accepted_block    ] fc::exception: 3110000 plugin_exception: Plugin exception
Existing ship log with 214013 blocks when starting from genesis block 2
{"eb":214013,"b":2}
nodeos  log.hpp:513 write_entry
```
was not logged because it was called before `state_history_plugin::plugin_startup()` where the `state_history` logger is initialized. Some plugins work around this by using the default logger in `plugin_initialize()`. However, there are some logs that never have worked. 
For example, in `net_plugin`:
```
void net_plugin::plugin_initialize( const variables_map& options ) {
fc_ilog( logger, "Initialize net plugin" );
```
This never actually logs because the …
> Move initialization of logging before plugin_initialize

- programs/keosd/main.cpp
Resolves #513.
Add missing return statement when app. initialization fails.
> [3.1] keosd - Exit program if keosd fails to aquire wallet lock (GH #513)

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Resolves #530.
These messages are showing up in leap 3.2 is because the implementation of the http_server changed in leap 3.2, including adding support for HTTP 1.1 Keep-Alive, which allows HTTP connections to persist for more than one request.
As a result, when the client closes the connection, the server is busy performing a read (waiting for the next request) which end with a Connection reset by peer error. This was reported as an error by mistake. This PR makes the http_plugin silently close its side of the connection.
> [3.2 -> main] Avoid logging errors when client disconnects after request (GH #530)

- programs/keosd/main.cpp
Resolves https://github.com/AntelopeIO/leap/issues/513.
Add missing return statement when app. initialization fails.
> [3.1 -> 3.2] keosd - Exit program if keosd fails to aquire wallet lock (GH #513)

- programs/keosd/main.cpp
Resolves https://github.com/AntelopeIO/leap/issues/513.
Add missing return statement when app. initialization fails.
> [3.2 -> main] keosd - Exit program if keosd fails to aquire wallet lock (GH #513)

- libraries/state_history/include/eosio/state_history/log.hpp
- tests/ship_log.cpp
- unittests/restart_chain_tests.cpp
Verify when truncating SHiP logs that truncation is not allowed when starting from genesis.
```
warn  2023-02-22T20:51:14.867 nodeos    controller.cpp:606            startup              ] No existing chain state. Initializing fresh blockchain state.
warn  2023-02-22T20:51:14.867 nodeos    controller.cpp:464            initialize_blockchai ] Initializing new blockchain with genesis state
info  2023-02-22T20:51:14.888 nodeos    controller.cpp:501            replay               ] existing block log, attempting to replay from 2 to 214011 blocks
error 2023-02-22T20:51:14.889 nodeos    state_history_plugin.c:284    on_accepted_block    ] fc::exception: 3110000 plugin_exception: Plugin exception
Existing ship log with 214013 blocks when starting from genesis block 2
{"eb":214013,"b":2}
nodeos …
```
> [3.2] SHiP do not truncate logs when starting from genesis

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
Update the min threads to use when doing the plugin thread optimization calculation.  It now starts at the plugin's default thread configuration and goes up instead of starting at a hard-coded 2 threads.
> [PH] update calc threads min to give to plugins to the plugin default.

- tests/performance_tests/README.md
- tests/performance_tests/performance_test.py
- tests/performance_tests/performance_test_basic.py
The config option `user-trx-data-file` was not properly being exposed to the top level performance test. This PR exposes it and makes a few related fixes.
> [PH] expose --user-trx-data-file to performance test

- tests/performance_tests/performance_test.py
Reverts changes to the Performance Test defaults that came in as part of this merge fix https://github.com/AntelopeIO/leap/pull/685/commits/1ffa26a3df48599ac451b650954e013141f21052#diff-33a866d6785cdbbe658e69c163ef1466a2f0c8adeeac41d81ab8c068fe3c13b8R216
> [TH] Revert Unintentional Change to Performance Test Defaults

- libraries/libfc/include/fc/log/appender.hpp
- libraries/libfc/include/fc/log/console_appender.hpp
- libraries/libfc/include/fc/log/dmlog_appender.hpp
- libraries/libfc/include/fc/log/gelf_appender.hpp
- libraries/libfc/include/fc/log/logger_config.hpp
- libraries/libfc/src/log/dmlog_appender.cpp
- libraries/libfc/src/log/gelf_appender.cpp
- libraries/libfc/src/log/logger_config.cpp
- programs/keosd/main.cpp
- programs/nodeos/main.cpp
This PR address issue #650 to make GELF logging use its own io_context and spawn a separate thread to send GELF logging.
> move gelf logging to another thread

- plugins/producer_plugin/producer_plugin.cpp
Log "Subjective bill" log entries to `producer_plugin` logger at `all` (trace) level.
Resolves #768
> [3.1] Move subjective bill log to `all` level of `producer_plugin` logger.

- programs/keosd/main.cpp
- programs/nodeos/main.cpp
This bumps appbase to https://github.com/AntelopeIO/appbase/pull/11 and fixes the logging.json not working problem. Please see https://github.com/AntelopeIO/appbase/pull/11  for details of the fix.
Resolved https://github.com/AntelopeIO/leap/issues/775
> bump appbase version and fix logging.json not working problem

- libraries/libfc/include/fc/log/logger.hpp
- plugins/producer_plugin/producer_plugin.cpp
Log "Subjective bill" log entries to `producer_plugin` logger at `all` (trace) level.
Merges `release/3.1` into `release/3.2` including #773.
Re-implements functionality since 3.2 is completely different in logging in this area.
Resolves #768
> [3.1 -> 3.2] Move subjective bill log to `all` level of `producer_plugin` logger.

- libraries/libfc/include/fc/log/logger.hpp
- plugins/producer_plugin/producer_plugin.cpp
Log "Subjective bill" log entries to `producer_plugin` logger at `all` (trace) level.
Merges `release/3.2` into `main` including #773 & #779.
Resolves #768
> [3.2 -> main] Move subjective bill log to `all` level of `producer_plugin` logger.

- plugins/producer_plugin/producer_plugin.cpp
This PR adds a new configuration option `--subjective-account-max-failures-window-size` to set the window size in number of blocks for `--subjective-account-max-failures`  option. 
Address IS #760
> [3.1] subjective-account-max-failures-window-size

- plugins/http_plugin/tests/unit_tests.cpp
Fix for clang warning: "suggest braces around initialization of subobject [-Wmissing-braces]" for `BasicProtocol` & `Expect100ContinueProtocol` initialization.
Also some minor cleanup.
> Minor cleanup and fix for clang warning

- plugins/producer_plugin/producer_plugin.cpp
This PR merges PR #785 into main branch with the following changes
- adds a new configuration option --subjective-account-max-failures-window-size to set the window size in number of blocks for --subjective-account-max-failures option.
- extract the block tracking functionality from `account_failures` class into a `block_time_tracker` class.
Resolves #760
> [3.2 -> main] subjective-account-max-failures-window-size

- plugins/chain_api_plugin/chain.swagger.yaml
- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- programs/cleos/help_text.cpp.in
- programs/cleos/httpc.hpp
- tests/plugin_http_api_test.py
- unittests/abi_tests.cpp
See https://github.com/AntelopeIO/leap/wiki/Deprecations-and-Proposed-Deprecations-In-Leap-Software
Remove the deprecated endpoints: 
- `/v1/chain/abi_bin_to_json`
- `/v1/chain/abi_json_to_bin`
Resolves #788
> Remove deprecated `/v1/chain/abi_bin_to_json` and `/v1/chain/abi_json_to_bin`

- plugins/producer_plugin/producer_plugin.cpp
If `producer_plugin` `debug` level is enabled during syncing up to head of chain there was too much logging that is not useful. Reduce the amount of logs during sync.
> Improve logging during syncing when `producer_plugin` `debug` level is enabled

- plugins/state_history_plugin/tests/session_test.cpp
SHIP's session_test is linking to boost unit test library
https://github.com/AntelopeIO/leap/blob/84c48b78e961fcbde24ed54c1097fd8593846f10/plugins/state_history_plugin/tests/CMakeLists.txt#L2
but then was using the header-only variant of boost unit test
https://github.com/AntelopeIO/leap/blob/993bcbae736a0ce8543adf89da30e8492867f644/plugins/state_history_plugin/tests/session_test.cpp#L3
This results in duplicate symbol errors on (at least) gcc12 + boost 1.81. Change to just using the static library. See more information here https://www.boost.org/doc/libs/1_81_0/libs/test/doc/html/boost_test/usage_variants.html
> fix mixed up boost test linkage in ship session_test

- tests/plugin_http_api_test.py
Increase `abi-serializer-max-time-ms` & `http-max-response-time-ms` for `plugin_http_api_test.py`. All other integration tests increase these values via `Cluster.py`. This test does not use `Cluster.py` so they have to be manually increased.
Resolves #808
> Test fix: Increase abi-serializer-max-time-ms & http-max-response-time-ms for test

- tests/performance_tests/performance_test.py
If the `targetTps` is allowed to be 0, there can be a division by 0 error `TpsTrxGensConfig` because the `numGenerators` would be 0 and thus `initialTpsPerGenerator` would be division by 0.  Fix this error through starting search floor at min 1 as well as capping the min to the floor.
When additional command line arguments were added to `performance_test_basic.py`, some were inadvertently missed being passed from `performance_test` down to the `performance_test_basic`.  Update the argument passing to match that in `performance_test_basic.py`.
> [PH] fix bug and arg passing

- libraries/chain/block_log.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_log.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- programs/cleos/httpc.hpp
- programs/cleos/main.cpp
- tests/chain_plugin_tests.cpp
- tests/plugin_http_api_test.py
This PR 
- adds the following API endpoints 
* `/v1/chain/get_raw_block`: returns the raw block content without ABI decoding
* `/v1/chain/get_block_header`: returns the block header with optional block extensions
- Input/output: 
```
struct get_raw_block_header_params {
string block_num_or_id;
bool include_extensions = false; // include block extensions (requires reading entire block off disk)
}; 
struct get_raw_block_header_results {
chain::block_id_type  id;
fc::variant           signed_block_header;
std::optional<chain::extensions_type> block_extensions;
};
```
- add `cleos get block` options for the added API endpoints above
* `--raw`: corresponding to `get_raw_block`
* `--header`: corresponding to `get_block_header` with `include_extensions` set to false
* `--header_with_extensions`: …
> get_raw_block api endpoint

- plugins/producer_plugin/include/eosio/producer_plugin/snapshot_scheduler.hpp
Erasing an element from multi-index while iterating over it caused an abort (core dump) when running `nodeos_snapshot_forked_test.py`. Remove the element at the end instead.
Resolves #838
> Snapshot: fix issue with erasing element while iterating

- docs/01_nodeos/02_usage/03_development-environment/01_local-multi-node-testnet.md
- docs/01_nodeos/03_plugins/producer_plugin/index.md
- plugins/producer_plugin/producer_plugin.cpp
- tests/TestHarness/Cluster.py
- tests/launcher.py
- tests/p2p_tests/dawn_515/test.sh
- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Remove the the long deprecated `--private-key` option.
Use `--signature-provider` instead.
See https://github.com/AntelopeIO/leap/wiki/Deprecations-and-Proposed-Deprecations-In-Leap-Software
For example:
```
--private-key [\"EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg\",\"5JgbL2ZnoEAhTudReWH1RnMuQS6DBeLZt4ucV6t8aymVEuYg7sr\"]
```
Becomes:
```
--signature-provider EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg=KEY:5JgbL2ZnoEAhTudReWH1RnMuQS6DBeLZt4ucV6t8aymVEuYg7sr
```
Resolves #789
> Remove deprecated `--private-key` option from nodeos

- CMakeLists.txt
- README.md
From [issue 735](https://github.com/AntelopeIO/leap/issues/735), this reverts [pull request 799](https://github.com/AntelopeIO/leap/pull/799) (Search for LLVM versions 7-11, prefering latest version) to fix the pinned build on Ubuntu 22.04. There are no other changes in this PR besides the revert.
[Pull request 799](https://github.com/AntelopeIO/leap/pull/799) introduced code that attempts to automagically find the correct version of LLVM for the Leap build on systems that have multiple versions of LLVM installed and available. This code only runs when `cmake` is version 3.19 or newer. Ubuntu 22.04 ships with CMake version 3.22.1, following the new code path, whereas Ubuntu 20.04 ships with version 3.16.3 that does not follow the new code path. This explains why the pinned build only …
> Fix Pinned Build on Ubuntu 22.04

- scripts/install_deps.sh
- scripts/pinned_build.sh
From [issue 735](https://github.com/AntelopeIO/leap/issues/735), I was having trouble running `scripts/pinned_build.sh` in a clean Ubuntu 22.04 container on the `HEAD` of `main`, which is expected to work, so I ran the [bashate](https://github.com/openstack/bashate) and [shellcheck](https://www.shellcheck.net) BASH linters on the script to look for errors.
```bash
bashate -i E006
shellcheck -x -f gcc
```
This pull request is **_only_** linting changes, I have introduced them in a pull request separate from my work to try to make the peer review less painful.
This will probably be easiest to review by ignoring whitespace...
...and/or reviewing the commits individually, instead of as a group. The commits each have one linter rule in them they intend to address, which you can find online …
> Pinned Build Script Linter Changes

- scripts/install_deps.sh
From [issue 735](https://github.com/AntelopeIO/leap/issues/735), this pull request fixes the pinned build by returning the `libcurl4-openssl-dev` dependency.
- [Pull Request 811](https://github.com/AntelopeIO/leap/pull/811) - Pinned Build Script Changes + Restore `libcurl4-openssl-dev`
- [Pull Request 812](https://github.com/AntelopeIO/leap/pull/812) - Pinned Build Script Linter Changes
- [Pull Request 832](https://github.com/AntelopeIO/leap/pull/832) - Roll `install_deps.sh` into `pinned_build.sh`
- [Pull Request 833](https://github.com/AntelopeIO/leap/pull/833) - Fix Pinned Build on Ubuntu 22.04
- Reverts [pull request 799](https://github.com/AntelopeIO/leap/pull/799)
- [Pull Request 835](https://github.com/AntelopeIO/leap/pull/835) - Change ASCII Art Banner in Build Script
> Restore libcurl4-openssl-dev

- README.md
While working on [issue 735](https://github.com/AntelopeIO/leap/issues/735), I found that [commit `06c9e25`](https://github.com/AntelopeIO/leap/commit/06c9e2532775633466e11225071d384de5b626d1) erroneously removed whitespace necessary for the proper formatting of the `README.md`. Usually, this is a "feature" of someone's editor to remove blank space at the end of lines and they don't realize they committed the change. This is desirable in some languages, but markdown uses whitespace at the end of lines to control formatting. This pull request restores that formatting, and pulls in one or two other minor changes to the `README.md` I had made while updating the documentation for [pull request 832](https://github.com/AntelopeIO/leap/pull/832).
- [Pull Request …
> Fix README.md Formatting

- libraries/wasm-jit/Include/IR/Operators.h
There is a noisy warning on at least gcc12,
```
In file included from /home/spoon/f/leap/src/libraries/wasm-jit/Include/Inline/Serialization.h:3,
from /home/spoon/f/leap/src/libraries/wasm-jit/Source/WASM/WASMSerialization.cpp:3:
/home/spoon/f/leap/src/libraries/wasm-jit/Include/IR/Operators.h: In instantiation of ‘struct IR::OpcodeAndImm<IR::ControlStructureImm>’:
/home/spoon/f/leap/src/libraries/wasm-jit/Include/IR/Operators.h:637:4:   required from here
/home/spoon/f/leap/src/libraries/wasm-jit/Include/IR/Operators.h:591:21: warning: ignoring packed attribute because of unpacked non-POD field ‘IR::ControlStructureImm IR::OpcodeAndImm<IR::ControlStructureImm>::imm’
591 |                 Imm imm;
|                     ^~~
/home/spoon/f/leap/src/libraries/wasm-jit/Include/Platform/Platform …
```
> fix noisy `ignoring packed attribute` warning on `IR::ControlStructureImm`

- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
Make sure that SHiP continues to send until the send queue is drained.
Resolves #861
> [4.0] SHiP: Send until queue is empty

- tests/TestHarness/Cluster.py
This PR fixes the import failure for platform which doesn't support `unshare`.
> [4.0] unshare import fix

- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- tests/TestHarness/Cluster.py
* Fixes the import failure for platform which doesn't support unshare.
* Make sure that SHiP continues to send until the send queue is drained.
Resolves https://github.com/AntelopeIO/leap/issues/861
Merges PR #869 & #876 into main
> [4.0->main] unshare import fix & SHiP: Send until queue is empty

- tests/plugin_http_api_test.py
Use `--max-transaction-time -1` to avoid issue with `setcode` timing out.
> [4.0] Test Fix: Use max-transaction-time -1

- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/TestHarness/queries.py
- tests/TestHarness/transactions.py
- tests/nodeos_snapshot_diff_test.py
- tests/nodeos_startup_catchup.py
A number of changes to functions in Node.py were lost as a result of the splitting of Node.py into itself plus 2 additional files.  This PR returns all those lost changes. 
Process for finding missing changes:
Last commit prior to merge was df5ad0c,
First commit prior to branch was bf4267e
Therefore, every change that happened in the diff of the two must be reflected in the current main code.
Diff: https://www.diffchecker.com/dYC5EHTW/
```
getTransBlockNum -> Moved to queries.py
Moved a piece of code
stdinAndCheckOutput still in Node.py, merge caught change
getTransaction -> Moved to queries.py
"get transaction_trace" replaced with lambda call
getBlockNumByTransId -> moved to queries.py
key and refBlockNum both now use a lambda
createInitializeAccount -> Moved to transactions.py …
```
> [4.0 -> main] Restore Node.py Changes that were lost

- libraries/wasm-jit/Include/IR/Operators.h
clang++11 warning:
```
In file included from /home/heifner/ext/leap/libraries/wasm-jit/Source/WASM/WASMSerialization.cpp:7:
/home/heifner/ext/leap/libraries/wasm-jit/Include/IR/Operators.h:682:55: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
static_assert(sizeof(IR::OpcodeAndImm<IR::NoImm>) == 2);
```
> Fix clang warning

- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
Signal received block with the block number so that `start_block` can be interrupted even if the block is received before the start of `start_block`. This is particularly important for #867, but also useful as mitigation against race condition of receiving block right before start of the block in current implementation. See https://github.com/AntelopeIO/leap/pull/648.
Resolves #891
> [3.2] Use block_num for interrupt of start_block

- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
Signal received block with the block number so that `start_block` can be interrupted even if the block is received before the start of `start_block`. This is particularly important for #867, but also useful as mitigation against race condition of receiving block right before start of the block in current implementation. See https://github.com/AntelopeIO/leap/pull/648.
Merges #893 into `release/4.0`. Includes integration into the new ro_trx_queue (see 9e79e82dea51d7c803db889f79c88abac2ed8b1d).
Resolves #891
> [3.2 -> 4.0] Use block_num for interrupt of start_block

- tests/nodeos_snapshot_forked_test.py
- tests/trx_finality_status_forked_test.py
Looks like default 30 sec in this particular cluster config is not sufficient sometimes on a slower gh workers, leading to test to fail
Resolves #906
> [4.0] Adjusted timeout in tests to give better chance on reaching consensus

- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
Resolves https://github.com/AntelopeIO/leap/issues/822.
This PR encapsulate wait and lock operations in the ro transaction queue, and makes the tasks wait on a condition variable while the read window is active, and there are transactions either in the queue or being processed.
It addresses the issue of thread starvation described in issue https://github.com/AntelopeIO/leap/issues/822.
> [4.0 -> main] Cleanup and prevent thread starvation while in the read window.

- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- plugins/http_plugin/include/eosio/http_plugin/macros.hpp
- plugins/producer_api_plugin/producer_api_plugin.cpp
> Replace needless std::map with std::vector, and std::move in capture

- tests/TestHarness/Cluster.py
- tests/launcher.py
Launcher now honors `-k/--kill <signal_number>` argument.  Cluster was updated for the Python launcher but support in the launcher itself was missed.  Resolves #911.
> [4.0] Implement support for -k/--kill in launcher.

- .cicd/platforms/ubuntu20.Dockerfile
- .cicd/platforms/ubuntu22.Dockerfile
- README.md
As of #442 curl is no longer required to run tests. Remove it from docs & CI environment
> curl is no longer a required dependency; remove from docs & CI environment

- libraries/state_history/include/eosio/state_history/log.hpp
Flush the `state_history_plugin` logs to disk at the end of each write to make it more likely that a `kill -9` or crash leaves valid logs.
Resolves #596
> [3.2] SHiP flush logs on write

- libraries/state_history/include/eosio/state_history/log.hpp
Flush the `state_history_plugin` logs to disk at the end of each write to make it more likely that a `kill -9` or crash leaves valid logs.
Merges #928 into `release/4.0`.
Resolves #596
> [3.2 -> 4.0] SHiP flush logs on write

- libraries/state_history/include/eosio/state_history/log.hpp
Flush the `state_history_plugin` logs to disk at the end of each write to make it more likely that a `kill -9` or crash leaves valid logs.
Merges #928 & #935 into `main`.
Resolves #596
> [4.0 -> main] SHiP flush logs on write

- tests/TestHarness/WalletMgr.py
- tests/auto_bp_peering_test.py
- tests/cli_test.py
- tests/nodeos_contrl_c_test.py
- tests/performance_tests/performance_test_basic.py
- tests/plugin_http_api_test.py
- tests/trace_plugin_test.py
- unittests/restart_chain_tests.cpp
- unittests/snapshot_tests.cpp
This PR cleans up a number of tests that have been littering.
`unittests/snapshot_tests.cpp` was leaving tmp files around even on success
These tests were all leaving logs around in TestLogs even on on success:
`tests/auto_bp_peering_test.py`
`tests/cli_test.py`
`tests/nodeos_contrl_c_test.py`
`tests/plugin_http_api_test.py`
`tests/trace_plugin_test.py`
`test/performance_test_basic` (nonbasic also as a result)
`unittests/restart_chain_tests.cpp` had some old code that was unused, which had previously behaved similarly to temp_dir.
Additionally changed `tests/TestHarness/WalletMgr.py` to clean up the test wallets after test success.
Resolves: https://github.com/AntelopeIO/leap/issues/719
> [4.0] Clean tmp and TestLogs after test runs

- libraries/chain/controller.cpp
Fix for replay where `forkdb.root()` is null during the write in SHiP for `on_accepted_block`. 4.0 SHiP calls `chain.last_irreversible_block_id()` in `on_accepted_block` which expects `forkdb.root()` to be valid. 
Merges #936 into `release/4.0`
Resolves #596
> [3.2 -> 4.0] forkdb reset in replay since blocks are signaled

- libraries/chain/controller.cpp
Fix for replay where `forkdb.root()` is null during the write in SHiP for `on_accepted_block`. 4.0 SHiP calls `chain.last_irreversible_block_id()` in `on_accepted_block` which expects `forkdb.root()` to be valid. 
Merges #936 & #938 into `main`
Resolves #596
> [4.0 -> main] forkdb reset in replay since blocks are signaled

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/producer_plugin/producer_plugin.cpp
Resolved https://github.com/AntelopeIO/leap/issues/950
https://github.com/AntelopeIO/leap/pull/776 assumed read-only transactions to only run on read-only threads. https://github.com/AntelopeIO/leap/pull/901 changed that and read-only transactions can run on main thread too.
- Existing calculation of transient trxs time was done on the main thread. This is not correct any more as read-only trxs on the main thread in the read window will be double counted. The solution is to count transient time only in the write window (dry-run trxs only run in write window). This change makes the intention more clearer and safer, as in write window all processing is single threaded and no read-only threads are running.
- Refactored `push_read_only_transaction` for read-only tasks missed idle time …
> [4.0] Correct time summary calculation for transient trxs due to change of read-only trxs windows

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/producer_plugin/producer_plugin.cpp
Merge https://github.com/AntelopeIO/leap/pull/947.
https://github.com/AntelopeIO/leap/pull/776 assumed read-only transactions to only run on read-only threads. https://github.com/AntelopeIO/leap/pull/901 changed that and read-only transactions can run on main thread too.
- Existing calculation of transient trxs time was done on the main thread. This is not correct any more as read-only trxs on the main thread in the read window will be double counted. The solution is to count transient time only in the write window (dry-run trxs only run in write window). This change makes the intention more clearer and safer, as in write window all processing is single threaded and no read-only threads are running.
- Refactored `push_read_only_transaction` for read-only tasks missed idle time accounting. …
> [4.0 -> main] Merge time summary fix to main

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/producer_plugin/producer_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/951.
We used to use `is_main_thread` to determine if it was safe to update eos-vm-cc code cache, as a transaction on the main thread did not run in parallel with read-only threads. Now a read-only transaction on the main thread can run in parallel with read-only threads. It is not safe for a read-only transaction on the main thread to modify code cache data structures. The solution is to use app's execution window. When in write window, all transactions are executed sequentially and no read-only threads are executing transactions.
> [4.0] Use is_write_window in eos-vm-oc main to determine if it is safe to update code cache

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/producer_plugin/producer_plugin.cpp
Merge https://github.com/AntelopeIO/leap/pull/960
Resolve https://github.com/AntelopeIO/leap/issues/951.
We used to use `is_main_thread` to determine if it was safe to update eos-vm-cc code cache, as a transaction on the main thread did not run in parallel with read-only threads. Now a read-only transaction on the main thread can run in parallel with read-only threads. It is not safe for a read-only transaction on the main thread to modify code cache data structures. The solution is to use app's execution window. When in write window, all transactions are executed sequentially and no read-only threads are executing transactions.
> [4.0 -> main] Use is_write_window in eos-vm-oc main to determine if it is safe to update code cache

- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm.hpp
- libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
Resolved https://github.com/AntelopeIO/leap/issues/969
https://github.com/AntelopeIO/leap/issues/969 identified global scoped_skip_checks can be accessible by multiple read-only threads. This variable is not needed in `wasm_interface_impl::get_instantiated_module`. 
Another finding was initial memory argument in `instantiate_module` was not needed in all the  `instantiate_module` methods. I double checked that it was un-named in all the implementations of `instantiate_module`. Safe to remove.
This PR removed both of them.
> [4.0] Remove global WASM::check_limits and initial memory from instantiate_module

- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm.hpp
- libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
Merge https://github.com/AntelopeIO/leap/pull/975 to main.
https://github.com/AntelopeIO/leap/issues/969 identified global scoped_skip_checks can be accessible by multiple read-only threads. This variable is not needed in `wasm_interface_impl::get_instantiated_module`. 
Another finding was initial memory argument in `instantiate_module` was not needed in all the  `instantiate_module` methods. I double checked that it was un-named in all the implementations of `instantiate_module`. Safe to remove.
This PR removed both of them.
> [4.0 -> main] Remove global WASM::check_limits and initial memory from instantiate_module

- libraries/chain/controller.cpp
- libraries/chain/eosio_contract.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- libraries/chain/webassembly/cf_system.cpp
- plugins/producer_plugin/producer_plugin.cpp
Resolve https://github.com/AntelopeIO/leap/issues/963
- Added missing calls to wasmifs on read-only threads
- Removed first_block_num_used from wasm_instantiation_cache.emplace
- Replaced thread_local for wasmifs with a local variable (unordered_map)
> [4.0] Added missing calls to wasmifs on read-only threads

- libraries/chain/controller.cpp
- libraries/chain/eosio_contract.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- plugins/producer_plugin/producer_plugin.cpp
Resolved https://github.com/AntelopeIO/leap/issues/963
Merge https://github.com/AntelopeIO/leap/pull/964 to main.
- Added missing calls to wasmifs on read-only threads
- Removed first_block_num_used from wasm_instantiation_cache.emplace
- Replaced thread_local for wasmifs with a local variable (unordered_map)
> [4.0 -> main] Added missing calls to wasmifs on read-only threads

- libraries/wasm-jit/CMakeLists.txt
This line was hiding in the forest of cmake comments and sprung a surprise via #888. Removing it and allowing the library to compile with c++17 appears to cause no errors nor warnings, soooo, let's do that.
> remove WAVM specific c++11 flag

- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
Protect typical EOS Mainnet capable `nodeos` from running out of RAM by limiting read-only-threads to 8. 8 was chosen as it is the same upper limit for when `eos-vm-oc` is enabled. On a 64GB machine 8 should be conservative limit for now. This limit can be raised once #800 is addressed.
Resolves #978
> [4.0] Set an upper limit on read-only-threads of 8

- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
Protect typical EOS Mainnet capable `nodeos` from running out of RAM by limiting read-only-threads to 8. 8 was chosen as it is the same upper limit for when `eos-vm-oc` is enabled. On a 64GB machine 8 should be conservative limit for now. This limit can be raised once #800 is addressed.
Merges #982 into `main`.
Resolves #978
> [4.0 -> main] Set an upper limit on read-only-threads of 8

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
- plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
- tests/TestHarness/queries.py
- tests/plugin_http_api_test.py
This PR merges PR #939 into main
This PR put prometheus metrics exporter on a different port.
Added option 
- `prometheus-exporter-address` : The local IP and port to listen for incoming prometheus metrics http request.
The API resource name remains to be `/v1/prometheus/metrics`
Resolves #899
> [4.0->main] prometheus on different port

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/chain_plugin/chain_plugin.cpp
- tests/CMakeLists.txt
- tests/distributed-transactions-test.py
- tests/nodeos_irreversible_mode_test.py
- tests/nodeos_read_terminate_at_block_test.py
Restore deprecated `read-mode=speculative` that was removed in #414. `read-mode=head` remains the default.
Although, `read-mode=speculative` can cause confusion to users, this PR restores the option as an alternative non-default `read-mode`. This does not restore persisted trxs. Persisted trxs were API trxs re-applied for each block. This new restored `speculative` mode therefore will not have the state of API trxs auto applied at the start of each speculative block. It is up to the user to re-apply any transactions at each speculative block in order to observe their side-effects.
Also the restored `read-mode=speculative` does not, unlike the old removed `read-mode=speculative`, apply schedule changes, protocol activations, or `onblock` trxs for a speculative mode into the speculative …
> [4.0] Restore read-mode=speculative

- CMakeLists.txt
- README.md
- libraries/libfc/include/fc/log/appender.hpp
- libraries/libfc/test/network/test_message_buffer.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- tests/ship_client.cpp
Updating min Boost version to be in line with `pinned_build.sh` min requirement.
With dropping support for Ubuntu 18.04 and Ubuntu 20.04's min boost version of 1.71, it should be okay to bump `leap`'s min to the pinned build's min required boost version 1.70.
> Update boost version.

- libraries/chain/include/eosio/chain/wasm_interface.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm.hpp
- libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/webassembly/cf_system.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
This is simply a clean up change to try and make it more explicit how `eosio_exit` works by eliminating some needless abstraction that contains a deceptive comment.
When the host function `eosio_exit` is called the contract execution is considered successfully complete immediately.
I don't remember the exact historical reasons the code was written the way it was, so I'll go with a plausible theory.
A reasonable way to accomplish the required behavior is to throw an exception in the `eosio_exit` impl that is caught as a do-nothing in the appropriate location (ideally immediately after the line that 'entered' wasm execution). This catch continues to live on
https://github.com/AntelopeIO/leap/blob/dfe829e7dc0d7420e73905cba7d520a3f8dc8769/libraries/chain/apply_context.cpp#L96-L98
However, at …
> [4.0] make `eosio_exit` impl more direct

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/chain_plugin/chain_plugin.cpp
- tests/CMakeLists.txt
- tests/distributed-transactions-test.py
- tests/nodeos_irreversible_mode_test.py
- tests/nodeos_read_terminate_at_block_test.py
Restore deprecated `read-mode=speculative` that was removed in #414. `read-mode=head` remains the default.
Although, `read-mode=speculative` can cause confusion to users, this PR restores the option as an alternative non-default `read-mode`. This does not restore persisted trxs. Persisted trxs were API trxs re-applied for each block. This new restored `speculative` mode therefore will not have the state of API trxs auto applied at the start of each speculative block. It is up to the user to re-apply any transactions at each speculative block in order to observe their side-effects.
Also the restored `read-mode=speculative` does not, unlike the old removed `read-mode=speculative`, apply schedule changes, protocol activations, or `onblock` trxs for a speculative mode into the speculative …
> [4.0 -> main] Restore read-mode=speculative

- libraries/chain/include/eosio/chain/exceptions.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/producer_plugin/producer_plugin.cpp
Merge https://github.com/AntelopeIO/leap/pull/984.
https://github.com/AntelopeIO/leap/issues/970 identified a problem when `get_descriptor_for_code` failed, the execution will go on the non-thread-safe path.
This PR implements a workaround. `get_descriptor_for_code` returns failure reasons when it fails. Read-only trxs will retry in the future or fail permanently. 
Resolves https://github.com/AntelopeIO/leap/issues/970
> [4.0 -> main] Fix ROtrx dispatched to baseline runtime when compiled code not ready

- plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
- tests/TestHarness/queries.py
- tests/plugin_http_api_test.py
This PR fixes promethues plugin crash problem when the resource path is not exactly "v1/prometheus/metrics".
Resolves [#IS 1002](https://github.com/AntelopeIO/leap/issues/1002)
> [4.0] fix resource not found bug

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- tests/http_plugin_test.py
This PR fixes the problem where HTTP plugin doesn't response to requests with disallowed HTTP HOST header.
Resolve IS #859
> [3.2] response to disallowed host

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Log all http request and response at `debug` log level. Limit output to 1024 characters to avoid excessive logging.
Examples:
```
debug 2023-04-10T22:14:42.274 http-0    beast_http_session.hpp:171    handle_request       ] Request:  127.0.0.1:50544 POST /v1/chain/get_info HTTP/1.1  Host: localhost:8888  content-length: 0  Accept: */*  Connection: close    
debug 2023-04-10T22:14:42.275 http-0    beast_http_session.hpp:399    send_response        ] Response: 127.0.0.1:50544 HTTP/1.1 200 OK  Content-Type: application/json  Connection: close  Server: nodeos/v3.2.2  Content-Length: 903    {"server_version":"061f0102","chain_id":"79148b80a054744b63fb590f38bd9dbaac9386c9c0b779c6bbf9f44f97e85d12","head_block_num":4,"last_irreversible_block_num":3,"last_irreversible_block_id":"00000003c406dfd18775 …
```
> [3.2] Log all http request/response at debug log level

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- tests/http_plugin_test.py
This PR fixes the problem where HTTP plugin doesn't response to requests with disallowed HTTP HOST header.
Merges PR #996 into 4.0
Resolves #859
>  [3.2->4.0] response to disallowed host

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Log all http request and response at `debug` log level. Limit output to 1024 characters to avoid excessive logging.
Examples:
```
debug 2023-04-10T22:14:42.274 http-0    beast_http_session.hpp:171    handle_request       ] Request:  127.0.0.1:50544 POST /v1/chain/get_info HTTP/1.1  Host: localhost:8888  content-length: 0  Accept: */*  Connection: close    
debug 2023-04-10T22:14:42.275 http-0    beast_http_session.hpp:399    send_response        ] Response: 127.0.0.1:50544 HTTP/1.1 200 OK  Content-Type: application/json  Connection: close  Server: nodeos/v3.2.2  Content-Length: 903    {"server_version":"061f0102","chain_id":"79148b80a054744b63fb590f38bd9dbaac9386c9c0b779c6bbf9f44f97e85d12","head_block_num":4,"last_irreversible_block_num":3,"last_irreversible_block_id":"00000003c406dfd18775 …
```
> [4.0 -> main] Log all http request/response at debug log level

- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
Reduce `producer_plugin` `debug` level log spam.
Merges #1010 into `release/4.0`
Resolves #1003
> [3.2 -> 4.0] Reduce producer_plugin debug level log spam

- plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
Reduce `producer_plugin` `debug` level log spam.
Merges #1010 & #1017 into `main`
Resolves #1003
> [4.0 -> main] Reduce producer_plugin debug level log spam

- plugins/net_plugin/net_plugin.cpp
In preparation of #452 work, fix misc clang-tidy warnings in `net_plugin.cpp`.
> P2P: clang-tidy fixes

- libraries/state_history/include/eosio/state_history/types.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/session_test.cpp
Add a unittest for `state_history_plugin` handling of forks and `have_positions` in `get_blocks_request`.
Adds reflection of `get_blocks_result_v0` type used for debugging.
Related to #955
> Test: Add SHiP forking and have_positions unittest

- libraries/chain/include/eosio/chain/abi_serializer.hpp
I believe this is a more correct way to pass the resolver (which includes multiple std::map containers).
In my testing, I did not see any performance improvements. Possibly it is because these calls are inlined by the compiler.
> Pass Resolver as `const &` instead of by value.

- plugins/net_plugin/net_plugin.cpp
In preparation of work for #452 some initial cleanup.
Testing with performance harness when sending more transactions than nodeos can process it fills up the write queue. This is designed to then close the connection. nodeos was generating thousands of write queue full messages (example below) because the posted `close()` call would have to wait until all the currently queued up tasks on the strand finished. This delayed the close for seconds. Added a `closing` flag to stop existing tasks quickly, resulting in only one message instead of thousands and an immediate close.
```
error 2023-04-15T16:46:16.320 net-0     net_plugin.cpp:2494           start_read_message   ] ["localhost:9877 - d7c63c8" - 1 127.0.0.1:37658] write queue full 71936405 bytes, giving up on connection, closing
```
Added …
> P2P: Misc improvements

- libraries/wasm-jit/Include/WAST/WAST.h
At least for some newer libc++ versions, like those in latest XCode, we need to include `string` in this file.
> add needed `string` include for some newer libc++ versions

- plugins/net_plugin/net_plugin.cpp
Keep a small cache of unlinkable blocks to retry. This is mainly to address the issue of blocks coming in on multiple connections and getting processed out of order. On an unlinkable block exception, store the block and retry it if its `previous` block is applied.
Resolves #452
> P2P: Save and retry unlinkable blocks

- programs/cleos/main.cpp
Fix one of the last two warnings in Leap on Ubuntu 20.02:
```
/home/lh/work/leap-main/programs/cleos/main.cpp:527:1: warning: control reaches end of non-void function [-Wreturn-type]
527 | }
```
> Fix control reaches end of non-void function warning

- libraries/libfc/src/log/logger_config.cpp
When compiled not on Linux (BSD here)  FC_USE_PTHREAD_NAME_NP not defined and code for this scenario was missing std:: for string
> Added missing namespace to logger in case of FC_USE_PTHREAD_NAME_NP not defined

- CMakeModules/EosioTester.cmake.in
- CMakeModules/EosioTesterBuild.cmake.in
libssl has been unused since #745 so remove it from libtester cmakes
A contract build with this change is available at
https://github.com/eosnetworkfoundation/eos-system-contracts/actions/runs/4765703258
> remove unused libssl from libtester cmakes

- CMakeModules/EosioTester.cmake.in
- CMakeModules/EosioTesterBuild.cmake.in
This workaround appears to no longer be needed, best I can tell.
A contract build with this change is available at
https://github.com/eosnetworkfoundation/eos-system-contracts/actions/runs/4765705845
> remove boost <1.70 workaround in libtester cmakes

- unittests/api_tests.cpp
When I build in release mode, I have the following tests failing (both gcc-12 and clang-16, no problem in debug) 
```
/home/greg/github/enf/leap/unittests/api_tests.cpp(1078): error: in "api_tests/checktime_pause_max_trx_cpu_extended_test": elapsed 26100us 
/home/greg/github/enf/leap/unittests/api_tests.cpp(1136): error: in "api_tests/checktime_pause_max_trx_extended_test": elapsed 26056us
```
This is the first failure in the code:
```
// This assumes that loading the WASM takes at least 1.5 ms
// If this check fails but duration is >= 24'999 (previous check did not fail), then the check here is likely
// because WASM took less than 1.5 ms to load.
BOOST_CHECK_MESSAGE( dur > 26'500, "elapsed " << dur << "us" );
```
I also have the following failure occasionally when building in release …
> Fix test failure on fast machine (release builds)

- libraries/libfc/test/io/test_json.cpp
On AppleClang 14.0.3 there is an error in test_json,
```
/Users/spoon/leap/libraries/libfc/include/fc/variant.hpp:619:7: error: call to 'to_variant' is ambiguous
to_variant( val, *this );
^~~~~~~~~~
/Users/spoon/leap/libraries/libfc/test/io/test_json.cpp:75:18: note: in instantiation of function template specialization 'fc::variant::variant<long>' requested here
variant v(4294967296); // 0xFFFFFFFF + 1
^
/Users/spoon/leap/libraries/libfc/include/fc/variant.hpp:83:9: note: candidate function
void to_variant( const uint8_t& var,  fc::variant& vo );
^
/Users/spoon/leap/libraries/libfc/include/fc/variant.hpp:85:9: note: candidate function
void to_variant( const int8_t& var,  fc::variant& vo );
^
/Users/spoon/leap/libraries/libfc/include/fc/variant.hpp:88:9: note: candidate function
void …
```
> fix ambiguous to_variant()s in json tests

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/subjective_billing.hpp
- plugins/chain_plugin/CMakeLists.txt
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/CMakeLists.txt
- tests/CMakeLists.txt
- tests/chain_plugin_tests.cpp
- tests/get_producers_tests.cpp
- tests/get_table_seckey_tests.cpp
- tests/get_table_tests.cpp
- tests/test_chain_plugin.cpp
- unittests/subjective_billing_tests.cpp
- unittests/test_subjective_billing.cpp
Break circular dependency between `producer_plugin` and `chain_plugin` by moving `subjective_billing` into the `chain` library and moving ownership of `subjective_billing` object from the `producer_plugin` to `controller`.
Resolves #668
> Refactor: Move subjective_billing to chain library

- libraries/chain/authorization_manager.cpp
In this method, `check_but_dont_fail` is equivalent to whether the transaction is `dry-run`. However, when `dry-run` is `true`, authorization should not be checked. 
Backport of https://github.com/AntelopeIO/leap/pull/1081
Thanks to @PinelliaC for the fix.
> [3.2] fix: not fail on signature checks for dry-run txns

- libraries/chain/authorization_manager.cpp
In this method, `check_but_dont_fail` is equivalent to whether the transaction is `dry-run`. However, when `dry-run` is `true`, authorization should not be checked. 
Backport of https://github.com/AntelopeIO/leap/pull/1081
Merges #1089 of `release/3.2` into `release/4.0`
Thanks to @PinelliaC for the fix.
> [3.2 -> 4.0] fix: not fail on signature checks for dry-run txns

- libraries/chain/apply_context.cpp
- libraries/libfc/include/fc/string.hpp
- libraries/libfc/src/string.cpp
- libraries/libfc/test/CMakeLists.txt
- libraries/libfc/test/test_escape_str.cpp
- plugins/producer_plugin/producer_plugin.cpp
Create a new `escape_str` function for use of sanitizing strings without having to use `format_string` with its overhead of `mutable_variant_object`.
Also optimize `print_debug` used for contract console output.
Resolves #641
> Optimization: New escape_str function for sanitizing strings

- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_plugin/test/test_account_query_db.cpp
- tests/chain_plugin_tests.cpp
- tests/get_table_seckey_tests.cpp
- tests/get_table_tests.cpp
- tests/test_chain_plugin.cpp
- unittests/api_tests.cpp
- unittests/auth_tests.cpp
- unittests/bootseq_tests.cpp
- unittests/currency_tests.cpp
- unittests/database_tests.cpp
- unittests/delay_tests.cpp
- unittests/eosio_system_tester.hpp
- unittests/misc_tests.cpp
- unittests/payloadless_tests.cpp
- unittests/producer_schedule_tests.cpp
- unittests/ram_tests.cpp
- unittests/read_only_trx_tests.cpp
- unittests/wasm-spec-tests/generated-tests/wasm_spec_tests.hpp.in
- unittests/wasm_config_tests.cpp
- unittests/wasm_tests.cpp
- unittests/whitelist_blacklist_tests.cpp
- Remove unused `NON_VALIDATING_TEST` macro.
- Add `operator<<` for `setup_policy` so `setup_policy` can be used with boost data in tests.
- Allow the `setup_policy` to be provided to `validating_tester` instead of being hard-coded to `full`.
- Update wasm tests to use `validating_tester` with different `setup_policy`.
Resolves #259
> Tests: misc cleanup

- plugins/chain_plugin/test/CMakeLists.txt
- plugins/chain_plugin/test/main.cpp
- plugins/chain_plugin/test/test_account_query_db.cpp
- plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
- plugins/chain_plugin/test/test_trx_retry_db.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
- plugins/producer_plugin/test/CMakeLists.txt
- plugins/producer_plugin/test/main.cpp
- plugins/producer_plugin/test/test_block_timing_util.cpp
- plugins/producer_plugin/test/test_options.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
- plugins/producer_plugin/test/test_trx_full.cpp
- plugins/trace_api_plugin/test/CMakeLists.txt
- plugins/trace_api_plugin/test/include/eosio/trace_api/test_common.hpp
- plugins/trace_api_plugin/test/main.cpp
- plugins/trace_api_plugin/test/test_compressed_file.cpp
- plugins/trace_api_plugin/test/test_configuration_utils.cpp
- plugins/trace_api_plugin/test/test_data_handlers.cpp
- plugins/trace_api_plugin/test/test_extraction.cpp
- plugins/trace_api_plugin/test/test_responses.cpp
- plugins/trace_api_plugin/test/test_trace_file.cpp
- tests/test_snapshot_scheduler.cpp
Currently we have different types of tests stored under a test folder for some plugins, e.g. chain_plugin and producer_plugin.
Some of these are proper unit tests of the plugin code in isolation. Those can remain in the folder but we should group them all together in a single executable rather than using different executable for each.
Some of these are bringing in other libraries and/or plugins and really should be considered integration tests (not to be confused with the Python end-to-end tests). These belong somewhere outside of the directories for the plugins. I suggest putting them in a sub-directory within the tests folder. It would also seem appropriate to bundle these tests together into one executable rather than linking separate executable for each test suite.
This PR reorganizes …
> Reorganize tests for plugins

- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
- Currently read-only trx options are checked even if `--read-only-thread` is 0. Changed to validate them only when `--read-only-thread` is greater than 0. 
- Current error message for invalid `-read-only-read-window-time-us` is confusing. Changed to use the same time unit and better error explanation. A sample looks like
```
warn  2023-05-04T00:46:28.397 thread-0  producer_plugin.cpp:1216  plugin_initialize  ] 3110006 plugin_config_exception: Incorrect plugin configuration   --read-only-read-window-time-us (20000 us) must be greater than --max-transaction-time  (10000 us) plus 10000 us, required: 20000 us > (10000 us + 10000 us).
```
Resolved https://github.com/AntelopeIO/leap/issues/1088
> [4.0] Check read-only trx options only when read-only-thread enabled, and present better error message

- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
Merge https://github.com/AntelopeIO/leap/pull/1129
- Currently read-only trx options are checked even if `--read-only-thread` is 0. Changed to validate them only when `--read-only-thread` is greater than 0. 
- Current error message for invalid `-read-only-read-window-time-us` is confusing. Changed to use the same time unit and better error explanation. A sample looks like
```
warn  2023-05-04T17:08:06.246 thread-0  producer_plugin.cpp:1221  plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration   read-only-read-window-time-us (20000 us) must be greater than max-transaction-time (10000 us) plus 10000 us, required: 20000 us > (10000 us + 10000 us).
```
- Reword read-only trx logging messages from the user perspective
Resolved …
> [4.0 -> main] Check read-only trx options only when read-only-thread enabled, and present better error message

- tests/test_snapshot_scheduler.cpp
This PR addresses issue https://github.com/AntelopeIO/leap/issues/1042, in particular:
- Added snapshot request with just a "start", it is valid one time request
- Added snapshot request with just spacing. Start assumed to be ASAP
- Some code cleanup
> Increase test coverage of snapshot-scheduler

- libraries/state_history/include/eosio/state_history/log.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/chain_plugin/test/CMakeLists.txt
- plugins/chain_plugin/test/plugin_config_test.cpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_plugin.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/CMakeLists.txt
- plugins/state_history_plugin/tests/plugin_config_test.cpp
This PR 
- changes the defaults of `max-retained-history-files` to UINT32_MAX when `state-history-retained-dir` is specified,
- adds some unit tests to validate `max-retained-history-files` and `max-retained-block-files`.
Resolves https://github.com/AntelopeIO/leap/issues/1135
> [4.0] change max-retained-history-files default

- tests/TestHarness/testUtils.py
Reopen `checkOutputFilename` (`subprocess_results.log`) in case where file may have been deleted, but attr was already set.
Allows for cases where `Cluster.cleanup` is called initially in tests to remove old test data, which should no longer be a problem, however in doing so it now deletes `subprocess_results.log` while attr for `checkOutputFile` has already been set.  This allows reopening/recreating the file and continuing to log to it to capture all commands after the initial cleanup.
> Keep `subprocess_results.log` around when test fails

- plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
`remote_endpoint()` call was generating error `Transport endpoint is not connected`. This call is only used for logging of the remote endpoint. Ignore the error and log `unknown` for the remote endpoint. This prevents the http thread pool from exiting due to an uncaught exception.
Resolves #1149
> [4.0] Ignore http error on remote_endpoint() causing shutdown

- plugins/net_plugin/net_plugin.cpp
When generating snapshots during syncing, nodeos would timeout a sync and close the connection. The close would cause all queued blocks on that connection to be dropped. Also the `sync_next_expected_num` would not be reset because the `sync_source` had been reset.
Resolves #1170
> [4.0] Correctly handle close while syncing

- plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
`remote_endpoint()` call was generating error `Transport endpoint is not connected`. This call is only used for logging of the remote endpoint. Ignore the error and log `unknown` for the remote endpoint. This prevents the http thread pool from exiting due to an uncaught exception.
Merges #1175 into `main`.
Resolves #1149
> [4.0 -> main] Ignore http error on remote_endpoint() causing shutdown

- plugins/net_plugin/net_plugin.cpp
When generating snapshots during syncing, nodeos would timeout a sync and close the connection. The close would cause all queued blocks on that connection to be dropped. Also the `sync_next_expected_num` would not be reset because the `sync_source` had been reset.
Merges #1171 into `main`. `main` already has the fix for not dropping queued blocks on a closed connection. See https://github.com/AntelopeIO/leap/pull/1040
Resolves #1170
> [4.0 -> main] Correctly handle close while syncing

- plugins/http_plugin/http_plugin.cpp
leap/plugins/http_plugin/http_plugin.cpp:76:4: warning: non-void function does not return a value in all control paths [-Wreturn-type]
> Fix compilation warning (does not return a value in all control paths)

- plugins/state_history_plugin/state_history_plugin.cpp
It was reported that during bloks log replay with a large blocks log nodeos process grows in memory to the point of it's exhaustion.
Resolves https://github.com/AntelopeIO/leap/issues/1130
> [4.0] Fix for nodeos large memory consumption during a blocks log replay

- plugins/state_history_plugin/state_history_plugin.cpp
It was reported that during bloks log replay with a large blocks log nodeos process grows in memory to the point of it's exhaustion.
Resolves https://github.com/AntelopeIO/leap/issues/1130
> [4.0 -> main] Fix for nodeos large memory consumption during a blocks log replay

- libraries/chain/include/eosio/chain/abi_serializer.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/chain_plugin/trx_retry_db.cpp
Resolves #1025.
Introduce a `caching_resolver `class, which provides the same API as a resolver, but which caches `abi_serializers`  as they are retrieved, so we pay the cost of retrieval only once.
> Improve packed_transaction parsing performance

- plugins/chain_api_plugin/chain.swagger.yaml
release 4.0 add docs/yaml content for missing chain api endpoints:
- /get_code_hash
- /get_producer_schedule
- /get_transaction_id
- /send_read_only_transaction
- /push_block
#fixes https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=26546756
> [4.0] add docs/yaml content for missing chain api endpoints

- tests/TestHarness/queries.py
When debugging a failed test, the default truncation limit of 1024 can conceal important information returned from `nodeos` when using the Test Harness `processUrllibRequest` method.  In addition, the result is logged on a single line, which is seldom readable.
This PR adds two arguments to ` processUrllibRequest` to allow testers to override the limit and enable pretty printing.  Pass `None` as the limit to have it print all of the output (unlimited).
> Add prettyPrint and printReturnLimit to processUrllibRequest()

- docs/01_nodeos/03_plugins/producer_plugin/index.md
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_options.cpp
- plugins/producer_plugin/test/test_read_only_trx.cpp
- plugins/producer_plugin/test/test_trx_full.cpp
- tests/performance_tests/performance_test_basic.py
- tests/test_snapshot_scheduler.cpp
The options `disable-subjective-p2p-billing` and `disable-subjective-api-billing` cover the same functionality as `disable-subjective-billing`. `disable-subjective-billing` simply set the other two options to `true`. Simplify options by removing this redundant option.
Resolves #1173
> Remove disable-subjective-billing option

- plugins/producer_plugin/producer_plugin.cpp
> [4.0 -> main] remove innocuous stray `}` in log statement

- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
Normally, for the pimpl idiom, the implementation resides in the `private` class, in our case `producer_plugin_impl`.
Before this change, many functions were defined in `producer_plugin`, directly accessing fields from `producer_plugin_impl` via the `my` pointer.
This PR does not change what the code does, it should be 100% equivalent to what was there before, however it moves most of the member functions implementation within the `producer_plugin_impl` class.
I wouldn't mind doing a even fuller cleanup, so that **all** the `producer_plugin` methods forward to `producer_plugin_impl` and are grouped together at the bottom of the file, but it might make the change even harder to follow. Please let me know what you think.
PS: most of the changes are `white space` changes, to make formatting …
> Cleanup producer_plugin pimpl idiom.

- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Normally, for the pimpl idiom, the implementation resides in the private class, in our case chain_plugin_impl.
Before this change, many functions were defined in chain_plugin, directly accessing fields from chain_plugin_impl through the `my` pointer.
This PR does not change what the code does, it should be 100% equivalent to what was there before, however it moves most of the member functions implementation within the chain_plugin_impl class.
I believe the only behavior change is that `handle_sighup()` was previously called within the try/catch block of plugin_initialize, and now is called outside a try/catch block, but I don't think this matters.
> Cleanup pimpl idiom on chain_plugin

- plugins/state_history_plugin/state_history_plugin.cpp
Normally, for the pimpl idiom, the implementation resides in the private class, in our case state_history_plugin_impl.
Before this change, many functions were defined in state_history_plugin, directly accessing fields from state_history_plugin_impl through the `my` pointer.
This PR does not change what the code does, it should be 100% equivalent to what was there before, however it moves most of the member functions implementation within the state_history_plugin_impl class.
I believe the only behavior change is that handle_sighup() was previously called within the try/catch block of plugin_initialize, and now is called outside a try/catch block, but I don't think this matters.
> Cleanup pimpl idiom for ship.

- plugins/net_plugin/net_plugin.cpp
Continue syncing the next `sync-fetch-span` while apply current range of synced blocks. It is prevented from running too far ahead of `head` by `sync-fetch-span`. It does queue up to double the amount of blocks during syncing than before this PR.
Before this PR:
```
[ sync blks A ]             [ sync blks B ]             [ sync blks C ]
[ apply blocks A.. ... ]    [ apply blocks B.. ... ]    [ apply blocks C.. ... ]
```
After this PR:
```
[ sync blks A ][ sync blks B ][ sync blks C ]       [ sync blks D ]         [ sync blks E ]
[ apply blocks A.. ... ][ apply blocks B.. ... ][ apply blocks C.. ... ][ apply blocks D.. ... ]
```
On my machine syncing into EOS mainnet, I was able to maintain 100% CPU while syncing.
Includes a fix for excessive handshake messages during syncing.
Resolves …
> P2P sync ahead while applying received blocks

- libraries/chain/include/eosio/chain/snapshot_scheduler.hpp
- libraries/chain/snapshot_scheduler.cpp
- plugins/producer_api_plugin/producer_api_plugin.cpp
- plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/test_snapshot_scheduler.cpp
This PR add differentiation between missing and zero-valued parameters in api request for start, end and spacing of blocks, in particular, as it was observed in original issue making start_block_num assignable to "0" in request or directly in snapshot-schedule.json file, such as:
```json
{
"snapshot_requests": [
{
"snapshot_request_id": "0",
"snapshot_description": "Hourly snapshots starting from genesis",
"block_spacing": "7200",
"start_block_num": "0",
"end_block_num": "0"
}
]
}
```
Prior implementation treated zero start as missing value and replaced it with "now" block num
Resolves https://github.com/AntelopeIO/leap/issues/1152
> Extended snapshot scheduler to better handle missing and zero params

- tests/TestHarness/Node.py
Some tests terminate some nodes but not all.  The `atexit` routine intended to be the final catchall for cleaning up a cluster would fail to terminate all nodes if it tried to terminate a node which had been shut down via `interruptAndVerifyExitStatus` first.  Tolerate terminated nodes and if the global `Debug` flag is set, log double kills. (The log message should be converted to a custom `TRACE` level when the code is converted to the Python `logging` module.)
> Avoid trying to kill a node twice to prevent orphaned processes.

- tests/test_snapshot_scheduler.cpp
A recent change introduced in https://github.com/AntelopeIO/leap/pull/1220 changed snapshot scheduling logic in a way that when start block is not specified, snapshot is getting scheduled ASAP. Depending on exact moment of scheduling in tester it can be either current or next block. And the test was failing when next block was selected.
Python tests use api call instead of direct interface function and that API call safely schedules to + 1 block, so there is no issue in any of the python tests.
> Improve robustness of snapshot unit test

- libraries/chain/include/eosio/chain/thread_utils.hpp
- plugins/producer_plugin/producer_plugin.cpp
This change comes about due to investigation of #1216: for some reason in those logs the ROtrx threads were taking a very long time to start and the previous implementation would error out if the threads weren't started within a second.
afaict the only reason to allow a maximum of 1 second previously was simply a proxy to make sure they all started up successfully (a `chain.init_thread_local_data()` that threw would have not run `++num_threads_started`). 
Refactor `named_thread_pool::start()` to simply wait forever for all the threads to complete their init (no matter if `chain.init_thread_local_data()` threw or not); and then if any init _did_ throw, rethrow one of those exceptions inside of `named_thread_pool::start()`.
Unfortunately it's worth noting during my testing of this change I …
> [4.0] allow ROtrx threads unlimited time to start

- libraries/chain/include/eosio/chain/thread_utils.hpp
- plugins/producer_plugin/producer_plugin.cpp
main merge of #1221 
> This change comes about due to investigation of #1216: for some reason in those logs the ROtrx threads were taking a very long time to start and the previous implementation would error out if the threads weren't started within a second.
> 
> afaict the only reason to allow a maximum of 1 second previously was simply a proxy to make sure they all started up successfully (a `chain.init_thread_local_data()` that threw would have not run `++num_threads_started`).
> 
> Refactor `named_thread_pool::start()` to simply wait forever for all the threads to complete their init (no matter if `chain.init_thread_local_data()` threw or not); and then if any init _did_ throw, rethrow one of those exceptions inside of `named_thread_pool::start()`.
> 
> Unfortunately it's worth …
> [4.0 -> main] allow ROtrx threads unlimited time to start

- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/plugin_config_test.cpp
Fix the handling of `state_history_plugin` option `state-history-log-retain-blocks` which was broken in 4.0.
Resolves #1217
> [4.0] SHiP: Fix state-history-log-retain-blocks option handling

- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/plugin_config_test.cpp
Fix the handling of `state_history_plugin` option `state-history-log-retain-blocks` which was broken in 4.0.
Merges `release/4.0` #1241 into `main`
Resolves #1217
> [4.0 -> main] SHiP: Fix state-history-log-retain-blocks option handling

- scripts/pinned_toolchain.cmake
Resolves #1238 
see [Relocation Read-Only (RELRO) doc](https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro).
Added back the same code that was in EOSIO 2.0, and verified that the pinned build works with this option on an ubuntu 22.04 VM.
```
...
123/129 Test   #96: snapshot_unit_test_eos-vm-oc .......................   Passed   23.22 sec
124/129 Test  #114: wasm_unit_test_eos-vm-oc ...........................   Passed   36.74 sec
125/129 Test   #18: api_unit_test_eos-vm-oc ............................   Passed   45.76 sec
126/129 Test   #13: test_resmon_plugin .................................   Passed   67.01 sec
127/129 Test  #111: wasm_config_unit_test_eos-vm-oc ....................   Passed   83.64 sec
128/129 Test #2046: trx_generator_tests …
```
> Add harden flags to pinned builds

- programs/leap-util/actions/blocklog.cpp
This PR addresses https://github.com/AntelopeIO/leap/issues/1239, in particular fact that multiple sub-commands under "blocklog" produce output in output-dir and it has no default value, so it should be mandatory to request this value from user.
> [3.2] Output-dir should be required for extract-blocks subcommand of leap-util

- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
fix `i256` key type conversion by initialize buffer before usage
`export_bits` doesn't fill every byte in the buffer, need to ensure that 'buffer' is initialized before usage:
https://github.com/boostorg/multiprecision/blob/5f81a78cdb38ea35f98ef7a655d2535773c1261b/include/boost/multiprecision/cpp_int/import_export.hpp#L236
> fix `i256` key type conversion by initialize buffer before usage

- programs/leap-util/actions/blocklog.cpp
This PR addresses https://github.com/AntelopeIO/leap/issues/1239, in particular fact that multiple sub-commands under "blocklog" produce output in output-dir and it has no default value, so it should be mandatory to request this value from user.
In 4.0 two more subcommands added that suffer from same bug, this is fixed in separate commit in this pr
> [3.2 -> 4.0] Output-dir should be required for block-log subcommands of leap-util

- plugins/net_plugin/net_plugin.cpp
Normally, for the pimpl idiom, the implementation resides in the private class, in our case `net_plugin_impl`.
Before this change, `plugin_initialize` and `plugin_startup` were defined in `net_plugin`, dereferencing members from `net_plugin_impl` through the `my` pointer.
This PR does not change what the code does, it should be 100% equivalent to what was there before (besides `handle_sigup()` being out of the try/catch block which I believe is inconsequential), however it moves the two member functions implementation within the `net_plugin_impl` class.
Also cleaned up `connection::_close()` which doesn't need to be static.
> Cleanup pimpl idiom for `net_plugin`

- programs/leap-util/actions/blocklog.cpp
This PR addresses https://github.com/AntelopeIO/leap/issues/1239, in particular fact that multiple sub-commands under "blocklog" produce output in output-dir and it has no default value, so it should be mandatory to request this value from user.
> [4.0 -> main] Output-dir should be required for block-log subcommands of leap-util

- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Thanks @learnforpractice. Back port of #1252 to `release/3.2`
fix `i256` key type conversion by initialize buffer before usage
`export_bits` doesn't fill every byte in the buffer, need to ensure that 'buffer' is initialized before usage:
https://github.com/boostorg/multiprecision/blob/5f81a78cdb38ea35f98ef7a655d2535773c1261b/include/boost/multiprecision/cpp_int/import_export.hpp#L236
> [3.2] fix `i256` key type conversion by initialize buffer before usage

- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Thanks @learnforpractice. Back port of #1252 & #1264 to `release/4.0` via merge of `release/3.2` into `release/4.0`.
fix `i256` key type conversion by initialize buffer before usage
`export_bits` doesn't fill every byte in the buffer, need to ensure that 'buffer' is initialized before usage:
https://github.com/boostorg/multiprecision/blob/5f81a78cdb38ea35f98ef7a655d2535773c1261b/include/boost/multiprecision/cpp_int/import_export.hpp#L236
> [3.2 -> 4.0] fix i256 key type conversion by initialize buffer before usage

- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
Two main issues resolved by this PR.
* "Infinite" loop of `notice_message` <-> `handshake_message` when clock skew. The clock skew caused peer to keep trying to inform other that it has the blocks already.
* Handshakes were being sent to every peer anytime any peer connection was closed. This was introduced in 4.0.1 by #1171. This PR handles this case better by resetting `sync_next_expected_num` on rejected block instead of spamming all connections with handshakes.
These issues were already fixed in `main` by work on #1072.
Additional fixes in this PR backported from #1072 work:
* Includes fix for using `nanoseconds` resolution for `time_message`.
* Update known head block on `catch_up` `notice_message`. The information is provided might as well use it instead of waiting for a …
> [4.0] P2P excessive logging caused by message spamming

- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- tests/nodeos_forked_chain_test.py
Use provided `block_state` on `state_history_plugin` `send_update` since `forkdb` may not have the block marked as validated yet and therefore will not be found by `state_history_plugin` when searching by block number.
See #1275 for details on why `forkdb` does not always "contain" the block.
Updated `nodeos_forked_chain_test.py` to use SHiP since it easily reproduced this failure.
Resolves #1272
> [4.0] SHiP: fix intermittent empty get_block_result

- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- tests/nodeos_forked_chain_test.py
Use provided `block_state` on `state_history_plugin` `send_update` since `forkdb` may not have the block marked as validated yet and therefore will not be found by `state_history_plugin` when searching by block number.
See #1275 for details on why `forkdb` does not always "contain" the block.
Updated `nodeos_forked_chain_test.py` to use SHiP since it easily reproduced this failure.
Merges `release/4.0` into `main` including #1276.
Resolves #1272
> [4.0 -> main] SHiP: fix intermittent empty get_block_result

- tests/test_snapshot_scheduler.cpp
This PR addresses instability of snapshot scheduler test and specifically it's part that executes "asap" scheduling with no start block.
> Made snapshot test more robust in case of asap scheduling

- libraries/chain/block_log.cpp
- libraries/chain/controller.cpp
- unittests/snapshot_tests.cpp
When running with an empty block log, `--block-log-retain-blocks 0`, it was not possible to load a snapshot. Implement `empty_block_log::reset` to correctly handle provided `first_block_num`.
Resolves #1228
> [4.0] Fix for loading snapshot with empty block log

- .github/workflows/pinned_build.yaml
Creating a shell of the initial `pinned_build.yaml` workflow to be merged quickly allowing development of actual workflow in follow-on branch & PR.
Need to have workflow file merged before github will allow triggering it in a development branch.
> Create initial workflow file for Pinned Builds.

- libraries/chain/block_log.cpp
- libraries/chain/controller.cpp
- unittests/snapshot_tests.cpp
When running with an empty block log, `--block-log-retain-blocks 0`, it was not possible to load a snapshot. Implement `empty_block_log::reset` to correctly handle provided `first_block_num`.
Merges `release/4.0` into `main` including #1285 
Resolves #1228
> [4.0 -> main] Fix for loading snapshot with empty block log

- plugins/chain_api_plugin/chain_api_plugin.cpp
- tests/plugin_http_api_test.py
- tests/read_only_trx_test.py
It appears that logic for handling transaction as part of get_transaction_id request was different in cleos and chain_api_plugin. Resolves https://github.com/AntelopeIO/leap/issues/1197
This PR makes a change to a logic of get_transaction_id handler as such:
- if actions.data & actions.hex_data provided, use the hex_data, test added
- if actions not present or not an array, will throw "Invalid transaction", test added
- if transaction is not parse-able, will throw "Invalid transaction" 
caveat here that there is a few lines of code duplication between chain_api_plugin and cleos, but this is probably safest way to address initial issue without dangers of changing abi serializer
> [4.0] if actions.data & actions.hex_data provided, use the hex_data in api call get_transaction_id

- libraries/libfc/src/log/logger_config.cpp
It appears that fresh checkout of main fails to build on BSD (and possibly other non-linux-es) due to FC_USE_PTHREAD_NAME_NP not defined and fc::to_string being called.
Replaced fc::to_string -> std::to_string, builds fine now.
uname -a
FreeBSD Z820 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64
> Fix for a build on FreeBSD 13.2

- libraries/chain/controller.cpp
- tests/nodeos_forked_chain_test.py
- tests/nodeos_irreversible_mode_test.py
- tests/ship_streamer.cpp
Additional test cases and fix for loading a snapshot without a block log. When loading a snapshot with a block log, the block log and fork database can be replayed if they start at or before the snapshot. If no block log exists, for example running with `--block-log-retain-blocks 0`, then the fork database can't be consider valid.
Includes a fix for new test introduced in https://github.com/AntelopeIO/leap/pull/1276 which failed during ci/cd. `ship_streamer.cpp` updated to correctly handle forks.
Corner case related to #1228
> [4.0] Fix for loading a snapshot with an empty block log but an existing fork database

- libraries/chain/controller.cpp
- tests/nodeos_forked_chain_test.py
- tests/nodeos_irreversible_mode_test.py
- tests/ship_streamer.cpp
Additional test cases and fix for loading a snapshot without a block log. When loading a snapshot with a block log, the block log and fork database can be replayed if they start at or before the snapshot. If no block log exists, for example running with `--block-log-retain-blocks 0`, then the fork database can't be consider valid.
Includes a fix for new test introduced in https://github.com/AntelopeIO/leap/pull/1276 which failed during ci/cd. `ship_streamer.cpp` updated to correctly handle forks.
Corner case related to #1228
Merges `release/4.0` into `main` including #1299
> [4.0 -> main] Fix for loading a snapshot with an empty block log but an existing fork database

- tests/test_snapshot_scheduler.cpp
Resolves https://github.com/AntelopeIO/leap/issues/1286. Unfortunately previous fix still (rarely) failed due to fact that scheduling without specifying start block can still lead to +1 or +2 in pending snapshot depending on environment factors and implemented mitigation logic was not sufficient. This time it is bulletproof :)
> Improve snapshot test reliability

- libraries/chain/include/eosio/chain/thread_utils.hpp
- libraries/chain/platform_timer_asio_fallback.cpp
- libraries/chain/platform_timer_kqueue.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- libraries/libfc/CMakeLists.txt
- libraries/libfc/include/fc/log/logger_config.hpp
- libraries/libfc/src/log/gelf_appender.cpp
- libraries/libfc/src/log/logger_config.cpp
- plugins/resource_monitor_plugin/resource_monitor_plugin.cpp
- plugins/trace_api_plugin/store_provider.cpp
This refactors the thread name stuff a bit to make it simpler (have gotten bitten here a few times lately such as #1283 and #1058)
* remove having both a `set_os_thread_name()` and `set_thread_name()` -- there is no reason setting the thread name shouldn't just set the OS thread name, having both of these (was `set_thread_name()` even used?) is just confusing
* add freebsd & macos thread name support
* remove the `HAVE_PTHREAD_SETNAME_NP` check; I think this was added at some point to resolve building on musl which didn't have `pthread_getname_np()` but while it does now,
* remove usage of `pthread_getname_np()` -- just not necessary to use this instead of referring to the existing `thread_local thread_name`
> remove `FC_USE_PTHREAD_NAME_NP` & `pthread_getname_np()` usage

- libraries/libfc/include/fc/network/listener.hpp
On macOS, asio will internally immediately `setsockopt(SO_NOSIGPIPE)` right after `accept()`ing a connection before dispatching the accept callback to user code (us). Googling around some will suggest that it may be possible for this call to fail with `EINVAL` if the connection has already failed. But, [more carefully constructed research](https://github.com/wahern/cqueues/blob/master/PORTING.md#so_nosigpipe-f_setnosigpipe) suggests that while `EINVAL` can occur from this call, it is not possible to occur in our use case: right after `accept()`.
Nevertheless, on macOS 13 `main`'s keosd is broken because for some reason an `EINVAL` is, best I can tell _spuriously_, occurring on this `setsockopt(SO_NOSIGPIPE)` call for the unix socket connection. Based on syscall traces, cleos makes a …
> on macOS do not consider `EINVAL` a fatal accept error in fc's listener; fixing keosd on macOS

- plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
- plugins/net_plugin/net_plugin.cpp
Use `std::chrono` types instead of `tstamp` so that magnitude is maintained. Fixes issue with heartbeat calculation being off on some machines causing pre-mature close of what it thought was a idle connection.
Resolves #1315
> [4.0] P2P: Use magnitude safe time types

- plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
- plugins/net_plugin/net_plugin.cpp
Use `std::chrono` types instead of `tstamp` so that magnitude is maintained. Fixes issue with heartbeat calculation being off on some machines causing pre-mature close of what it thought was a idle connection.
Merges `release/4.0` into `main` including #1316 
Resolves #1315
> [4.0 -> main] P2P: Use magnitude safe time types

- plugins/producer_plugin/producer_plugin.cpp
So we restart a speculative block to retry it immediately, instead of waiting to receive a new block.
Resolves #1247.
> [3.2] Report transaction failed if trx was exhausted in non-producing mode

- .github/workflows/build.yaml
Combine 3 libtester test cases into one using matrix.
> libtester ci matrix

- tests/TestHarness/TestHelper.py
- tests/cluster_launcher.py
The `cluster_launcher.py` test script is a convenient way to start up a local cluster for testing using the `--leave-running` flag.  This PR adds a `--plugin` command line option which can be repeated as necessary and will be passed to all nodes as `extraNodeosArgs`.
Required completing support for AppArgs 'action'.
> Add support for '--plugin' to cluster_launcher.py

- .github/workflows/pinned_build.yaml
- scripts/pinned_build.sh
Pinned builds run in GitHub Actions
Resolves: https://github.com/AntelopeIO/leap/issues/735
> [3.1 -> 3.2] Pinned Builds manual dispatch workflow in CI

- libraries/libfc/include/fc/mutex.hpp
- plugins/net_plugin/CMakeLists.txt
- plugins/net_plugin/net_plugin.cpp
Resolves #1230 
Newer versions of clang support a Google developed tool called "Thread Safety Analysis". Here is the [doc](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html).
Thread safety analysis works very much like a type system for multi-threaded programs. In addition to declaring the type of data (e.g. int, float, etc.), the programmer can (optionally) declare how access to that data is controlled in a multi-threaded environment. For example:
```
#include "mutex.h"
class BankAccount {
private:
Mutex mu;
int   balance GUARDED_BY(mu);
void depositImpl(int amount) {
balance += amount;       // WARNING! Cannot write balance without locking mu.
}
void withdrawImpl(int amount) REQUIRES(mu) {
balance -= amount;       // OK. Caller must have locked mu.
}
public:
void withdraw(int …
```
> Update net_plugin to support clang Thread Safety Analysis features

- .github/workflows/pinned_build.yaml
- scripts/pinned_build.sh
Pinned builds run in GitHub Actions
Resolves: https://github.com/AntelopeIO/leap/issues/735
> [3.2 -> 4.0] Pinned Builds manual dispatch workflow in CI

- tests/nodeos_retry_transaction_test.py
Verify bios node relaunch which was failing. The test was passing because nodeos would relaunch so fast as to never go out of sync. Added a small 1 second sleep so that nodeos is down long enough for transactions to actually be dropped and retried. 
Resolves #1244
> Test fix: nodeos_retry_transaction_test

- tests/large-lib-test.py
The test Cluster.py now uses `defproducera` as the producer after cluster launch. Updated test to expect `defproducera` instead of `eosio` by removing the relaunch with `-p eosio`.
Resolves #1246
> Test fix: large-lib-test

- plugins/net_plugin/net_plugin.cpp
P2P `notice_message.known_trx` `catch_up` does not report `head_num`, so do not update `head_num` reporting. `none` message does. Regardless only update `head_num` if a valid value.
Resolves #1328
> [4.0] P2P: fix head_num reporting

- plugins/net_plugin/net_plugin.cpp
P2P `notice_message.known_trx` `catch_up` does not report `head_num`, so do not update `head_num` reporting. `none` message does. Regardless only update `head_num` if a valid value.
Merges `release/4.0` into `main` including #1345 
Resolves #1328
> [4.0 -> main] P2P: fix head_num reporting

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- plugins/chain_plugin/chain_plugin.cpp
Add additional help to `transaction-retry-interval-sec` & `transaction-retry-max-expiration-sec`
```
--transaction-retry-interval-sec arg (=20)
How often, in seconds, to resend an 
incoming transaction to network if not 
seen in a block.
Needs to be at least twice as large as 
p2p-dedup-cache-expire-time-sec.
--transaction-retry-max-expiration-sec arg (=120)
Maximum allowed transaction expiration 
for retry transactions, will retry 
transactions up to this value.
Should be larger than 
transaction-retry-interval-sec.
```
Resolves #1302
> [4.0] Docs: Additional nodeos --help info

- libraries/chain/block_log.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_log.hpp
- tests/block_log.cpp
Minor refactor to make code cleaner/clearer. Return empty optional when block log does not have a current head.
Resolves #1289
> Blocklog: Return std::optional for head_id 

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- plugins/chain_plugin/chain_plugin.cpp
Add additional help to `transaction-retry-interval-sec` & `transaction-retry-max-expiration-sec`
```
--transaction-retry-interval-sec arg (=20)
How often, in seconds, to resend an 
incoming transaction to network if not 
seen in a block.
Needs to be at least twice as large as 
p2p-dedup-cache-expire-time-sec.
--transaction-retry-max-expiration-sec arg (=120)
Maximum allowed transaction expiration 
for retry transactions, will retry 
transactions up to this value.
Should be larger than 
transaction-retry-interval-sec.
```
Merges `release/4.0` into `main` including #1350 
Resolves #1302
> [4.0 -> main] Docs: Additional nodeos --help info

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
Compile contracts in order executed except for `eosio.*` contracts. Prioritize `eosio.*` accounts to be executed next.
> OC tierup compile in order

- .github/workflows/ph_backward_compatibility.yaml
Creating a shell of the initial `ph_backward_compatibility.yaml` workflow to be merged quickly allowing development of actual workflow in follow-on branch.
Need to have workflow file merged before github will allow triggering it in a development branch.
Relates to: https://github.com/AntelopeIO/leap/issues/1156
> Create stub workflow ph_backward_compatibility.yaml

- .github/workflows/performance_harness_run.yaml
Creating a shell of the initial performance harness run workflow to be merged quickly allowing development of actual workflow in follow-on branch.
Need to have workflow file merged before github will allow triggering it in a development branch.
> [PH] Create stub workflow for manual dispatch performance harness runs

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- plugins/chain_plugin/chain_plugin.cpp
Issue #980 restored `read-mode = speculative` but maintained the `DEPRECATED` statement in the help. Remove the `DEPRECATED` statement as `speculative` mode is a useful option for producer nodes. See https://github.com/AntelopeIO/leap/issues/1349#issuecomment-1615341482.
> [4.0] Removed "deprecated" from help for speculative read-mode

- docs/01_nodeos/03_plugins/chain_plugin/index.md
- plugins/chain_plugin/chain_plugin.cpp
Issue #980 restored `read-mode = speculative` but maintained the `DEPRECATED` statement in the help. Remove the `DEPRECATED` statement as `speculative` mode is a useful option for producer nodes. See https://github.com/AntelopeIO/leap/issues/1349#issuecomment-1615341482.
Merges `release/4.0` into `main` including #1368
> [4.0 -> main] Removed "deprecated" from help for speculative read-mode

- libraries/chain/abi_serializer.cpp
- libraries/libfc/include/fc/time.hpp
- unittests/abi_tests.cpp
When serializing a `std::optional` field, and a value is not provided for the `std::optional`, we need to add into the serialization the flag specifying that a missing value is serialized. Prior to this PR, the flag was missing.
> [3.2] Fix incorrect serializing of std::optional when value is not provided - (GH #1189)

- libraries/chain/abi_serializer.cpp
- unittests/abi_tests.cpp
When serializing a std::optional field, and a value is not provided for the std::optional, we need to add into the serialization the flag specifying that a missing value is serialized. Prior to this PR, the flag was missing.
> [3.2 -> 4.0] Fix incorrect serializing of std::optional when value is not provided - (GH #1189)

- libraries/chain/abi_serializer.cpp
- libraries/libfc/include/fc/time.hpp
- unittests/abi_tests.cpp
Resolves #1189 .
When serializing a std::optional field, and a value is not provided for the std::optional, we need to add into the serialization the flag specifying that a missing value is serialized. Prior to this PR, the flag was missing.
> [4.0 -> main] Fix incorrect serializing of std::optional when value is not provided - (GH #1189)

- plugins/net_plugin/net_plugin.cpp
More paranoid socket shutdown when closing and `async_read` with a closed socket. Also cleanup logic on connection duplicate check. Reset `org` as it needs to be reset on close so new connection will `send_time` message correctly.
Resolves #1349
> [4.0] Close connection on aysnc_read with a closed socket

- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/session_test.cpp
- tests/TestHarness/Cluster.py
- tests/TestHarness/testUtils.py
- tests/ship_streamer.cpp
- tests/ship_streamer_test.py
Support `state_history_plugin` clients when starting from snapshot. Allow clients to connect and receive full delta of a snapshot without consuming any additional blocks. 
Does not send `get_block_result_v0` messages for requested blocks that are not available. Previously it would send `get_blocks_result_v0` with empty `this_block` repeatably. Instead SHiP will send first available block that is available within requested range or wait for request block to become available to send to client.
Resolves #1340
> [4.0] SHiP: Support snapshot start with full deltas

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
- unittests/protocol_feature_tests.cpp
Before protocol feature `replace_deferred` is activated the trx id of the scheduled transaction can differ from the packed_transaction that is executed. This PR restores the behavior of tracking and reporting in transaction traces the scheduled transaction id instead of the packed_transaction id. This was not a consensus error but rather the wrong trx id was being reported in transaction traces for scheduled transactions before the on-chain activation of `replaced_deferred`. This manifested itself by confusing SHiP in recording the scheduled transactions reported in a block.
Resolves #1354
> [3.2] Emit correct trace id for deferred trx before replace_deferred protocol feature activation

- CMakeLists.txt
- CMakeModules/EosioTester.cmake.in
- CMakeModules/EosioTesterBuild.cmake.in
Since EOSIO 1.0 tcmalloc (from gperftools) would be used if it was found during cmake configuration. Despite that, we've never once had tcmalloc enabled in any sort of CI. I know in certain historical configurations, such as Ubuntu 16.04, the tcmalloc available from the standard package repo caused a dead lock in one of the unit tests (of course, the fault certainly could be have in the test, hard to say).
The benefit of using tcmalloc is supposed improved performance, but we don't have any recent data (or maybe any data ever) to back up that claim.
It seems a little reckless to eagerly enable features like this that we don't actually test ourselves. So move tcmalloc usage behind a cmake option that is defaulted to `off`. Using tcmalloc is still useful for leap developers due to its …
> no longer eagerly use tcmalloc if it's found

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
- unittests/protocol_feature_tests.cpp
Before protocol feature `replace_deferred` is activated the trx id of the scheduled transaction can differ from the packed_transaction that is executed. This PR restores the behavior of tracking and reporting in transaction traces the scheduled transaction id instead of the packed_transaction id. This was not a consensus error but rather the wrong trx id was being reported in transaction traces for scheduled transactions before the on-chain activation of `replaced_deferred`. This manifested itself by confusing SHiP in recording the scheduled transactions reported in a block.
Merges `release/3.2` into `release/4.0` including #1379 
Resolves #1354
> [3.2 -> 4.0] Emit correct trace id for deferred trx before replace_deferred protocol feature activation

- libraries/chain/include/eosio/chain/log_catalog.hpp
Startup of `state_history_plugin` was very slow when large number of SHiP logs were in the `retain` directory. Almost all the performance slowness was due to use of `boost::flat_map` as it sorts and inserts into a `vector` on each insert. Changing to use a `std::map` provides much more reasonable performance on startup. Also included in this PR are additional small performance improvements to the scanning of the log/indexs during startup. For my test case, improved from 76 seconds to 7 seconds.
Resolves #1331
> [4.0] SHiP: Improve startup when large number of SHiP logs in retain directory

- tests/nodeos_contrl_c_test.py
- tests/nodeos_startup_catchup.py
Reduced the number of generated/expected trxs to decrease load on ci/cd. The tests just need some trxs flowing, they do not require in particular amount of trxs.
Resolves #1357
> [4.0] Test: Reduce load on ci/cd

- tests/nodeos_contrl_c_test.py
- tests/nodeos_startup_catchup.py
Reduced the number of generated/expected trxs to decrease load on ci/cd. The tests just need some trxs flowing, they do not require in particular amount of trxs.
Merges `release/4.0` into `main` including #1387 
Resolves #1357
> [4.0 -> main] Test: Reduce load on ci/cd

- tests/ship_streamer_test.py
`state_history_plugin` test `ship_streamer_test.py` was not waiting on the correct transaction to be included in a block.
Resolves #1383
> [4.0] Test: Fix ship test to wait on correct transaction

- tests/ship_streamer_test.py
`state_history_plugin` test `ship_streamer_test.py` was not waiting on the correct transaction to be included in a block.
Merges `release/4.0` into `main` including #1388 
Resolves #1383
> [4.0 -> main] Test: Fix ship test to wait on correct transaction

- libraries/chain/webassembly/runtimes/eos-vm.cpp
This PR contains security updates to fix a denial of service vulnerability affecting all previous versions of Leap.
> [3.2 -> 4.0] Merge memory issue fix from release/3.2 to release/4.0

- libraries/chain/webassembly/runtimes/eos-vm.cpp
This PR contains security updates to fix a denial of service vulnerability affecting all previous versions of Leap.
> [4.0 -> main] Merge memory issue fix from release/4.0 to main

- tests/performance_tests/genesis.json
All other integration tests use 475ms for genesis `max_transaction_cpu_usage`. Update performance tests to use the same value. Sometimes `setcode` of eosio system contract would fail in ci/cd as 150ms was not enough time to set the contract and abi.
Resolves #1390
> Test Fix: performance test - use 475ms for max_transaction_cpu_usage

- programs/nodeos/main.cpp
Log all non-default command line options and `config.ini` options on startup and on program exit.
Example:
```
info  2023-07-17T16:59:13.936 nodeos    main.cpp:154                  operator()           ] nodeos version v4.1.0-dev v4.1.0-dev-d243f8569d5f8baf55bfb787a481530998a15d93-dirty
info  2023-07-17T16:59:13.936 nodeos    main.cpp:61                   log_non_default_opti ] Non-default options: data-dir = d, config-dir = mainconfig, enable-stale-production, producer-name = eosio, signature-provider = ***, chain-state-db-size-mb = 65536, p2p-peer-address = peer.main.alohaeos.com:9876, p2p-peer-address = p2p.eosargentina.io:9876, p2p-peer-address = p2p.genereos.io:9876, p2p-peer-address = eos.defibox.xyz:9876, p2p-peer-address = eos.edenia.cloud:9876, p2p-peer-address = …
```
> Print non-default options on startup/shutdown

- libraries/chain/CMakeLists.txt
- libraries/chain/apply_context.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/wasm_interface.hpp
- libraries/chain/include/eosio/chain/wasm_interface_collection.hpp
- libraries/chain/include/eosio/chain/wasm_interface_private.hpp
- libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp
- libraries/chain/wasm_interface.cpp
- libraries/chain/wasm_interface_collection.cpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
- libraries/testing/tester.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/producer_plugin/test/CMakeLists.txt
- tests/CMakeLists.txt
- tests/read_only_trx_test.py
- tests/test_read_only_trx.cpp
- unittests/test_utils.hpp
When `eos-vm-oc-enable` is `auto` or `all` revert back to non-oc tier up when oc compile of read-only trx not ready.
* Refactors `eosvmoc_tier` into `wasm_interface_collection` so that all threads share the same `eosvmoc_tier` instead of having one per `wasm_interface`.
* Removes unneeded eos-vm fast shutdown.
* Fixes `substitute_apply` so it does not have to be set on each thread.
Resolves #1119
> Revert back to non-oc execution for read-only trxs

- tests/TestHarness/launcher.py
Change the default genesis `max_transaction_cpu_usage` from 150ms to 475ms to allow for slow ci/cd. All the integration tests already used 475ms for `max_transaction_cpu_usage`. This PR changes the performance tests to use the same value. Also changed `max_block_cpu_usage` from 200ms to 500ms since it has to be larger than `max_transaction_cpu_usage`. This also matches the value used for integration tests.
Note #1401 was not sufficient because the value in the performance `genesis.json` was being overwritten by `launcher.py`.
Resolves #1416
> Test Fix: Change default max-transaction-cpu-usage for tests

- .github/workflows/build.yaml
When installing .deb packages in CI, it can be hard to know in advance which package will also want to install the `tzdata` package which by default interactively prompts for the current time zone. We skip this prompt by setting environment variables `DEBIAN_FRONTEND` & `TZ`. But those variables were only set for one step in the libtester job, so if the `tzdata` package came along in a different step -- like it did in https://github.com/AntelopeIO/leap/actions/runs/5645037759/job/15291662020 -- it would result in the job getting stuck.
Move these variables to be defined globally during the entire libtester job.
> set `DEBIAN_FRONTEND` & `TZ` globally during libtester job

- .github/workflows/build_base.yaml
- CMakeLists.txt
- package.cmake
A leap-dev.deb package is currently generated alongside the leap.deb package when performing a `make package` (as our README suggests). This leap-dev.deb, similarly to the `make dev-install` target, contains the files required for "native contract unit testing" a.k.a. libtester. afaik we don’t document this leap-dev.deb, nor do we include it as part of leap’s release assets. Instead, it’s used for punting around libtester in various Antelope CI use cases so that leap doesn’t need to always be rebuilt; for example, eos-system-contracts CI uses leap-dev.deb for its unit tests so that it doesn’t need to build leap just to run the system contract unit tests.
Unfortunately adding boost to leap-dev.deb is increasing the time it takes to perform `make package` significantly: from 30 seconds to 7 …
> Disable building leap-dev.deb package by default

- programs/nodeos/main.cpp
For the options that `nodeos` expects and just reports: `help`, `version`, `full-version`, `print-default-config`, do not log the non-default options and version.
Resolves #1446
> Do not print version and non-default args for help

- .github/workflows/build.yaml
- .github/workflows/ph_backward_compatibility.yaml
Upgrade to asset-artifact-download-action@v3. More details can be found at AntelopeIO/asset-artifact-download-action#2; the main benefit from existing usage here is removal of the `token` line and reduced API usage when `target` is manually specified to a branch
> Upgrade to asset-artifact-download-action@v3 in CI workflows

- plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
`remote_endpoint()` call was generating error `Transport endpoint is not connected`. This call is only used for logging of the remote endpoint. Ignore the error and log `unknown` for the remote endpoint. This prevents an uncaught exception in 3.2 and an exit of the http thread pool in 4.0+.
Already fixed in 4.0+ via: https://github.com/AntelopeIO/leap/pull/1175
Resolves #1418
> [3.2] Ignore http error on remote_endpoint() causing terminate

- .gitignore
*.s extension is:
> An S file is a generic source code file that contains the source for a computer program. It may be written in a number of different programming languages, but is commonly used for storing Assembly code.
Not sure why it was in the git ignore list.
Thanks to @Parth2412 for pointing this out: https://github.com/AntelopeIO/leap/pull/1361#issuecomment-1618521836
Resolves #1457
> Remove *.s from .gitignore

- plugins/trace_api_plugin/test/test_data_handlers.cpp
- plugins/trace_api_plugin/test/test_responses.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
- tests/TestHarness/testUtils.py
- tests/plugin_http_api_test.py
- tests/trace_plugin_test.py
The exception handler for the `trace_api_plugin` data handler now rethrows any exceptions so they can be reported to the API caller of `/v1/trace_api/get_block` and `/v1/trace_api/get_transaction_trace`.
`trace_api_plugin` will now report
```
./cleos --verbose --print-response get block_trace 20
RESPONSE:
---------------------
{
"code": 500,
"message": "Internal Service Error",
"error": {
"code": 2,
"name": "timeout_exception",
"what": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
"details": [{
"message": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
"file": "trace_api_plugin.cpp",
"line_number": 288,
"method": "operator()"
}
]
}
}
---------------------
error 2023-07-25T20:19:49.445 cleos     main.cpp:4498                 operator()           ] Failed with error: 2 …
```
> [3.2] Modify trace_api_plugin to report serialization errors to user

- plugins/trace_api_plugin/test/test_data_handlers.cpp
- plugins/trace_api_plugin/test/test_responses.cpp
- plugins/trace_api_plugin/trace_api_plugin.cpp
- tests/TestHarness/testUtils.py
- tests/plugin_http_api_test.py
- tests/trace_plugin_test.py
The exception handler for the `trace_api_plugin` data handler now rethrows any exceptions so they can be reported to the API caller of `/v1/trace_api/get_block` and `/v1/trace_api/get_transaction_trace`.
`trace_api_plugin` will now report
```
./cleos --verbose --print-response get block_trace 20
RESPONSE:
---------------------
{
"code": 500,
"message": "Internal Service Error",
"error": {
"code": 2,
"name": "timeout_exception",
"what": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
"details": [{
"message": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
"file": "trace_api_plugin.cpp",
"line_number": 288,
"method": "operator()"
}
]
}
}
---------------------
error 2023-07-25T20:19:49.445 cleos     main.cpp:4498                 operator()           ] Failed with error: 2 …
```
> [3.2 -> 4.0] Modify trace_api_plugin to report serialization errors to user

- unittests/misc_tests.cpp
`bad_alloc_test` causes ASAN to complain,
> ERROR: AddressSanitizer: requested allocation size 0x1ffffffffffffffc (0x2000000000001000 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
We can disable this rule globally via `allocator_may_return_null=1`, but it's better to just disable this simple test when ASAN is enabled. Unfortunately disabling it ends up being a little verbose since GCC & clang indicate its enablement differently.
> skip `bad_alloc_test` when ASAN enabled

- unittests/api_tests.cpp
- unittests/producer_schedule_tests.cpp
- unittests/resource_limits_test.cpp
- unittests/wasm_tests.cpp
Re-enable unittests which have been commented out since pre-launch of EOS.
Resolves #1111
> Tests: Add back old commented out unittests

- libraries/testing/contracts.cpp.in
- libraries/testing/contracts.hpp.in
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- tests/chain_plugin_tests.cpp
- tests/get_table_seckey_tests.cpp
- tests/get_table_tests.cpp
- tests/test_chain_plugin.cpp
- tests/test_snapshot_information.cpp
- unittests/api_tests.cpp
- unittests/bootseq_tests.cpp
- unittests/crypto_primitives_tests.cpp
- unittests/currency_tests.cpp
- unittests/delay_tests.cpp
- unittests/eosio.token_tests.cpp
- unittests/eosio_system_tester.hpp
- unittests/forked_tests.cpp
- unittests/get_block_num_tests.cpp
- unittests/params_tests.cpp
- unittests/payloadless_tests.cpp
- unittests/protocol_feature_tests.cpp
- unittests/ram_tests.cpp
- unittests/read_only_trx_tests.cpp
- unittests/snapshot_tests.cpp
- unittests/state_history_tests.cpp
- unittests/test_contracts.hpp.in
- unittests/wasm_config_tests.cpp
- unittests/wasm_tests.cpp
- unittests/whitelist_blacklist_tests.cpp
When the unittests get the ABI for a test contract,
https://github.com/AntelopeIO/leap/blob/339d98eed107b9fd94736988996082c7002fa52a/unittests/test_contracts.hpp.in#L13-L17
`fc::read_file_contents` will read the file's contents in to `s`. There is no null terminator at the end of the file since it's just a JSON text file, so `s` contains no null terminator in its set data. C++11 of course does define that `s.data()` is null terminated, and `*(s.begin() + s.size()) == '\0'`, but when `std::vector<char>(s.begin(), s.end())` is called, a vector is constructed with `s`'s contents without that implicit null terminator; just the set data of `s` which does not have the null terminator.
Later on, this function may be called like
https://github.com/AntelopeIO/leap/blob/339d98eed107b9fd9473698899608 …
> return `string` from test contract's `_abi()` call instead of `vector` to avoid non-null terminated `char*` access

- libraries/libfc/include/fc/crypto/base64.hpp
- libraries/libfc/src/crypto/base64.cpp
- libraries/libfc/src/variant.cpp
- libraries/libfc/test/test_base64.cpp
- libraries/libfc/test/variant/test_variant.cpp
Remove the invalid addition of "=" to all base64 encoded strings from `fc::variant`.
Also update base64 implementation from: https://github.com/ReneNyffenegger/cpp-base64
Resolves #1461
> Fix base64 encoding

- .github/workflows/build.yaml
As we start to add some hand rolled assembly that can detect and utilize optional CPU instruction sets at runtime (#1071), maybe it would be worthwhile checking that the CI runners are able to run all potential implementation combinations.
> check for existance of BMI2 & ADX instructions on CI workers

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/apply_context.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/transaction_context.cpp
- libraries/chain/webassembly/authorization.cpp
- libraries/chain/webassembly/crypto.cpp
- libraries/chain/webassembly/permission.cpp
- libraries/chain/webassembly/privileged.cpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
- unittests/delay_tests.cpp
- unittests/dry_run_trx_tests.cpp
Add requirement for dry-run/compute transactions to require authorization.
Add tests for dry-run/compute transactions.
Also some minor cleanup to unneeded includes.
Resolves #1083
> Require dry-run trxs to have authorization and add tests

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/memory.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp
- plugins/producer_plugin/producer_plugin.cpp
A part of https://github.com/eosnetworkfoundation/product/issues/149.
Per the design in https://github.com/eosnetworkfoundation/product/blob/main/transactions/read-only/memory.md, to conserve virtual memory to support more threads, we need to reduce the threshold where EOS VM OC transitions from mirroring to `mprotect()`.
We plan to keep 528 pages (528 slices) for the main-thread memory (currently used for anything other then read-only transaction threads); this ensures maximum performance for EVM transactions. For each read-only thread, we set 10 pages (11 slices) (10 pages covers 99% native actions and 56% EVM actions, from data collected by in https://github.com/AntelopeIO/leap/issues/1159). 
With maximum 256 read-only threads , virtual memory required by OC is 26 TB (OC's main thread …
> Set EOS VM OC max mirroring pages to a small number for read-only threads

- unittests/resource_limits_test.cpp
> fix a couple sign-compare warnings in resource_limits_test

- plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_block_timing_util.cpp
Change: Start speculative blocks every block interval but not more often. Fixes a corner case of rapid start-block/abort block burst for speculative blocks. Also create speculative blocks even when state is stale (over 5 seconds old).
Before this PR, block deadline was set for speculative blocks the same as production blocks for block production time. Because of when blocks are processed this could result in small block speculative windows. When a block came in close to deadline it would cause us to repeatedly start block with a very small deadline, abort block because of deadline, start another block and immediately abort again until the block time window was passed.
In addition, speculative blocks were not started on "stale" state (head block older than 5 seconds). Note this would be …
> Smarter block deadlines for speculative blocks

- libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp
`executor`'s ctor creates a shared mapping to the code cache file it is passed,
https://github.com/AntelopeIO/leap/blob/e9ace457e46898e377df1e0a6d1fb8049d8cb5e2/libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp#L146-L151
but its dtor doesn't unmap that mapping. That's sloppy and leaky. Easy enough to fix.
I'm not considering this for stable since realistically nodeos only ever creates one of these per thread for the entire lifetime of the application anyways.
> fix leaky EOS VM OC executor code mapping

- .cicd/platforms/ubuntu20.Dockerfile
- CMakeLists.txt
I missed this change with the C++20 switch.
> Update gcc version check in CMakeLists.txt.

- libraries/chain/webassembly/console.cpp
- libraries/wasm-jit/Source/WAST/ParseNumbers.cpp
Negating the minimum value of a signed integer is undefined behavior since the resulting value cannot be represented by the type (results in a signed overflow). However, casting to an unsigned and then negating that _is_ defined behavior, and I believe the appropriate solution here, as both of those operations are well defined for all inputs.
> negate after converting to unsigned to avoid UB on minimum signed value

- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/chain_pacemaker.cpp
- libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- libraries/hotstuff/test/test_pacemaker.cpp
- Moved everything in qc_chain.hpp that is not an interface to private:
- Fixed test_hotstuff to use get_state() instead of accessing various (now) private fields
- Fixed test_pacemaker to use get_id() instead of accessing (now) private _id field
- Added get_proposal() helper method to finalizer_state struct in chain/hotstuff.hpp since finalizer_state is now used in tests, etc.
- Made qc_chain class lock-free; all thread synchronization is now done externally
- Solved concurrency get_finalizer_state vs. qc_chain updates by caching chain_pacemaker::get_state(); zero overhead on qc_chain state updating, low overhead on external state read (no global/write locks acquired on cache hits)
This addresses part of #1541 (get_state() caching) and in the process of doing that I had to solve the …
> IF: Fix threading 1/2 (#1541) & qc_chain private:

- libraries/hotstuff/chain_pacemaker.cpp
- libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- plugins/chain_plugin/chain_plugin.cpp
- programs/nodeos/logging.json
This PR sets up FC logging for hotstuff component such that logging can be controlled dynamically and is consistent with nodeos' other components. More refinements might be needed.
It
* creates a specific logging category for `hotstuff`,
* uses `fc_elog` for errors,
* uses `fc_tlog` for everything was inside `QC_CHAIN_TRACE_DEBUG`
* uses `fc_dlog` for the rest of the original `ilog`.
> IF: Use FC logging framework for better management and consistency

- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Specifying `--http_port` didn't work because the script would always use 8000 as base port.
This PR fixes this.
> Fix `http_port` in boot script

- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Change `quorum_certificate` to use a `std::string` bitset representation instead of `unsigned_int` to move from 32 supported finalizers to unlimited.
Resolves #1547
> IF: Support larger number of finalizers

- plugins/chain_plugin/chain_plugin.cpp
- tests/nodeos_under_min_avail_ram.py
This updates the chainbase submodule to include the [memory reduction optimization](https://github.com/AntelopeIO/chainbase/pull/19). Description copied below.
This PR will reduce the chainbase memory usage
* `_parent`, `_left`, `_right`, `_color` consume 32 bytes together (8 bytes each).
* `_parent`, `_left`, `_right`, `_color` consume 16 bytes (42 + 42 + 42 + 2 bits) together.
*  use -2 (instead of 2) as `erased_flag` since _color is a 2 bit signed int.
* offset pointers `_parent`, `_left` & `_right` only have signed 42-bit each (so 41-bit absolute value), shifted by two bits thanks to alignment, implying a maximum of chainbase size of 2^43 = 8TB.
* `offset_node_base` objects must always be allocated within the same segment due to the 42-bit offset limit. Using a stack variable of …
> Update chainbase to tip (reduce memory usage)

- libraries/chain/authority.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/authority.hpp
- libraries/chain/include/eosio/chain/producer_schedule.hpp
- libraries/libfc/include/fc/crypto/private_key.hpp
- libraries/libfc/include/fc/crypto/public_key.hpp
- libraries/libfc/src/crypto/private_key.cpp
- libraries/libfc/src/crypto/public_key.cpp
- libraries/libfc/test/crypto/test_cypher_suites.cpp
- libraries/state_history/include/eosio/state_history/serialization.hpp
- plugins/chain_plugin/account_query_db.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/wallet_plugin/wallet.cpp
- plugins/wallet_plugin/wallet_manager.cpp
- programs/cleos/main.cpp
- tests/trx_generator/trx_generator.hpp
- tests/wallet_tests.cpp
- unittests/abi_tests.cpp
- unittests/auth_tests.cpp
- unittests/chain_tests.cpp
- unittests/misc_tests.cpp
- unittests/state_history_tests.cpp
This started as a PR to remove `operator<<` from `public_key` as `to_string()` which optionally takes a `yield` function should be used instead. In the process noticed some conversion operators that could be removed. Some of these changes are a bit opinionated, but this PR actually ends up making what I think is a good case for not using conversion operators. Note there are a few optimizations that were not obvious because the conversion operators "magically" provided a less than ideal implementation.
This PR does not remove `operator<<` from `public_key`  as that breaks tests in `libtester`. There are however, enough improvements that this PR is still worthwhile in my opinion.
I didn't add spaceship operators because this PR already changed more than I originally anticipated.
> Remove some conversion operators

- libraries/chain/CMakeLists.txt
- libraries/chain/controller.cpp
- libraries/chain/finalizer_set.cpp
- libraries/chain/include/eosio/chain/config.hpp
- libraries/chain/include/eosio/chain/finalizer_authority.hpp
- libraries/chain/include/eosio/chain/finalizer_set.hpp
- libraries/chain/webassembly/privileged.cpp
- Rename `finalizer_set` `version` to `generation`.
- Changed `finalizer_set` `bls_public_key` to Jacobian little-endian encoding.
- Remove `generation` from `set_finalizers` host function parameter struct type.
- Add `hs_finalizer_set_extension` for block header extension.
- Move implementation of `finalizer_authority` and `finalizer_set` to source file to avoid including `bls12-381` headers into `libtester`.
> IF: Modify set_finalizer host function struct type

- libraries/libfc/CMakeLists.txt
`INCLUDE_DIRECTORIES` is clearly the more generic property to set in this case as it isn't specific to gcc/clang command line arguments.
> switch out `COMPILE_FLAGS` for `INCLUDE_DIRECTORIES` in fc's rapidjson cmake

- libraries/libfc/include/fc/io/cfile.hpp
latest glibc adds a `__nonnull` attribute on `fclose()` which ends up causing a bunch of warnings,
```
libraries/libfc/include/fc/io/cfile.hpp:22:65: warning: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Wignored-attributes]
22 |    using unique_file = std::unique_ptr<FILE, decltype( &fclose )>;
```
Not really sure the best way of fixing this. Simply wrapping the call like this gets rid of the warning.
> wrap `cfile`'s `fclose()` to avoid warning on latest glibc

- programs/leap-util/CMakeLists.txt
- programs/leap-util/actions/bls.cpp
- programs/leap-util/actions/bls.hpp
- programs/leap-util/main.cpp
- tests/CMakeLists.txt
- tests/leap_util_bls_test.py
Resolves https://github.com/AntelopeIO/leap/issues/1525
Add leap-util subcommands to create key pairs and pop (proof of possession), and tests.
Help looks like
```
./leap-util bls create --help-all
Create various items
Usage: bin/leap-util bls create [OPTIONS] SUBCOMMAND
Options:
-h,--help              Print this help message and exit
--help-all             Show all help
Subcommands:
├  key                    Create a new keypair and print the public and private keys
│
└  pop                    Create proof of possession for the corresponding public key of a given private key
./leap-util bls create key --help-all
Create a new keypair and print the public and private keys
Usage: bin/leap-util bls create key [OPTIONS]
Options:
-h,--help              Print this help message and exit …
```
> IF: Generate bls key pair

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/intrinsic_mapping.hpp
- libraries/chain/webassembly/runtimes/eos-vm.cpp
this is needed for corresponding cdt changes
https://github.com/AntelopeIO/cdt/issues/210
> add set_finalizers to host functions list

- libraries/libfc/src/crypto/bls_public_key.cpp
- libraries/libfc/src/crypto/bls_signature.cpp
- libraries/libfc/test/test_bls.cpp
Resolved https://github.com/AntelopeIO/leap/issues/1596.
Use raw Affine little-endian format for BLS public key and signature.
> use raw Affine little-endian form of g1/g2 for encoding to BLS public key and signature

- libraries/libfc/src/crypto/bls_public_key.cpp
- libraries/libfc/src/crypto/bls_signature.cpp
When a string is converted to a public key or signature, check if the string is invalid.
> IF: Check if input strings are invalid in conversion to public key or signature

- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/chain_pacemaker.cpp
- libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/signature_provider_plugin/include/eosio/signature_provider_plugin/signature_provider_plugin.hpp
- plugins/signature_provider_plugin/signature_provider_plugin.cpp
- Provides finalizer key map to `qc_chain`. 
- `qc_chain` not updated to use the keys as part of this PR.
- Bumped the version of fork database to provide a better error message since we do not currently support reading pre-5.0 fork databases. See #1601
> IF: Add support to producer_plugin to load BLS finalizer keys

- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/chain_pacemaker.cpp
- libraries/hotstuff/include/eosio/hotstuff/base_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/include/eosio/hotstuff/test_pacemaker.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_pacemaker.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- connection ID of hs message sender (net plugin -> IF engine)
- connection ID to exclude when propagating (IF engine -> net plugin)
- added callback to warn of bad HS messages from a connection (IF engine -> net plugin)
- added sample use of the warning callback for discarded proposals and votes
- helpers on qc_chain to allow for easy message propagation (no propagation decisions added)
- no-ops for this feature added to test_pacemaker (which does not have multi-hop)
Closes #1605
Obsoletes PR #1583, which can be closed as a message propagation strategy (for closing #1548) will be decided and then implemented on top of the code in this PR (suggestion https://github.com/AntelopeIO/leap/pull/1583/files/e1cc627a75853e2929df25cbcc3ee4f76066ba37#r1316210590 can be implemented when we remove …
> IF: Infrastructure for hs message filtering

- plugins/net_plugin/net_plugin.cpp
Resolved https://github.com/AntelopeIO/leap/issues/1546
Replace https://github.com/AntelopeIO/leap/pull/1617 to base on `main` instead.
Instant finality or private chains make it likely peers think their lib and head are not in sync but in reality they are only within small difference. To avoid unnecessary catchups, a minimal distance between lib and head is introduced. `min_blocks_distance` must be reached before catchup starts.
`min_blocks_distance` is defined as the number of blocks produced during the half keep alive interval (how long a node waits before contacting its peer).
> Prevent unnecessary lib<->head catchup transition changes

- libraries/libfc/include/fc/crypto/bls_private_key.hpp
- libraries/libfc/src/crypto/bls_private_key.cpp
- programs/leap-util/actions/bls.cpp
- tests/leap_util_bls_test.py
Fixed https://github.com/AntelopeIO/leap/issues/1525 to use BLS library `pop_prove` to generate POP.
* Added `get_pop_str` to libfc `bls_private_key` using `pop_prove`;
* Modified leap-util to use `get_pop_str`;
* Updated the test.
> IF: Use bls12_381::pop_prove to generate POP and add get_pop_str method to libfc

- libraries/libfc/CMakeLists.txt
When using boost integrated via a submodule + cmake, iostreams' cmake files correctly discover the dependent compression libraries instead of just blindly doing `-llzma`. We no longer need this workaround.
> remove now unneeded macOS z/bz2/lzma/zstd boost iostreams workaround

- benchmark/modexp.cpp
This adds a number of new cases in the modexp benchmark:
* more widths (I was curious to see behavior at smaller sizes)
* even vs odd modulus (very, very, critical performance difference for some modexp impls)
* base being greater vs less than modulus (for some impls results in minor difference in code path taken)
> add some additional test cases in modexp benchmark

- tests/PerformanceHarness/log_reader.py
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
Read only transactions are not logged in trace for cpu usage since they are not billed as such, thus use the elapsed time for the transaction processing to get the cpu usage overall.
Because read only transactions don't make it into blocks in the block log, need to add the transactions from the log file into the data block transaction counter for use in tps stats calculations in performance harness.
Relates to: https://github.com/AntelopeIO/leap/issues/1634
> [PH] Fix issues with processing read-only transactions.

- libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp
- libraries/wasm-jit/Include/IR/Operators.h
WAVM's parser casts `Opcode` and `OpcodeAndImm<>` to pointers _at arbitrary bytes_ within the WASM byte stream. For example,
https://github.com/AntelopeIO/leap/blob/6132e3be2225fe1de088ca31625238bc07f65636/libraries/wasm-jit/Include/IR/Operators.h#L327-L341
However, `Opcode`  (including the `Opcode` in the `OpcodeAndImm<>` struct), is a `uint16_t` which gives the compiler leeway to use instructions that require 2-byte alignment on access. On x86 and ARM8 this is not a problem but it's still UB to spec, so prudent to resolve.
> avoid unaligned accesses to types casted from byte stream in WAVM's wasm parser

- libraries/chain/webassembly/action.cpp
When action data size is 0, it was possible for a `memcpy` call to contain a source pointer of `nullptr` and length of `0`. This is not defined behavior, but a careful analysis of leap's supported platforms and prior builds shows no evidence this could be a source of indeterminism so this change is not being treated as a security fix.
> avoid possible memcpy with nullptr when action data size is 0

- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
`descriptor_ptr_from_file_start` ends up being 521, but a `uintptr_t` requires 8 byte alignment. Replace with proper `memcpy()`
> resolve misaligned access in OC code cache write out

- libraries/wasm-jit/Include/Inline/Serialization.h
`next` and `end` are initialized to `nullptr`, making the first call to `advance()` something like `if(nullptr + 6 > nullptr)`
> do not perform arithmetic on `nullptr` inside WAVM serialization

- libraries/hotstuff/include/eosio/hotstuff/test_pacemaker.hpp
- libraries/hotstuff/test/test_hotstuff.cpp
- libraries/hotstuff/test/test_pacemaker.cpp
- test_pacemaker allows each test to define a specific connection mesh between nodes
- added a simple unit test that can be used to test a solution for #1548 (just needs to introduce a disconnect between nodes)
- added support to write multi-hop unit tests (with selective message propagation by type)
The hotstuff protocol has "phases", and between two adjacent phases, we are typically using different message types. This allows us to write tests where we loop propagating a specific message type across the network, for as many hops as necessary, until the `dispatch` method on the `test_pacemaker` returns an empty vector, signaling no more message propagation happened. And then, we can start propagating the message type that's expected for the next phase of the protocol (these were generated …
> Add multi-hop network to test_pacemaker

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
When running performance tests on read-only transaction execution, the node generated many errors of `read_header: Connection reset by peer` and didn't make additional progress.
Boost beast http session checks for `http::error::end_of_stream || asio::error::connection_reset` in `on_read` and executes `do_eof()` to shutdown the connection. `on_read_header` was checking for `http::error::end_of_stream` but not `asio::error::connection_reset`. This PR changes `on_read_header` to also check for `asio::error::connection_reset`.
Resolves #1661
> [4.0] HTTP: Check for connection_reset

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
When running performance tests on read-only transaction execution, the node generated many errors of `read_header: Connection reset by peer` and didn't make additional progress.
Boost beast http session checks for `http::error::end_of_stream || asio::error::connection_reset` in `on_read` and executes `do_eof()` to shutdown the connection. `on_read_header` was checking for `http::error::end_of_stream` but not `asio::error::connection_reset`. This PR changes `on_read_header` to also check for `asio::error::connection_reset`.
Merges branch `release/4.0` into `main` including #1663 
Resolves #1661
> [4.0 -> main] HTTP: Check for connection_reset

- tests/TestHarness/testUtils.py
For performance harness and other tests report the full `nodeos` version which includes the commit hash. Recently I was looking at some old reports and it would be very helpful to know the exact commit hash that was run.
> PH: Include full version in performance harness reports

- libraries/libfc/src/crypto/_elliptic_impl_priv.hpp
- libraries/libfc/src/crypto/_elliptic_impl_pub.hpp
- libraries/libfc/src/crypto/elliptic_impl_priv.cpp
- libraries/libfc/src/crypto/elliptic_secp256k1.cpp
secp256k1's documentation states,
```c
/*  If the context is intended to be used for API functions that perform computations
*  involving secret keys, e.g., signing and public key generation, then it is highly
*  recommended to call secp256k1_context_randomize on the context before calling
*  those API functions. This will provide enhanced protection against side-channel
*  leakage, see secp256k1_context_randomize for details. */
```
It seems like it would be wise to perform this defense.
> randomize secp256k1 context used for signing

- libraries/hotstuff/include/eosio/hotstuff/test_pacemaker.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- libraries/hotstuff/test/test_pacemaker.cpp
- qc_chain does not aggregate a signature from a finalizer that has already voted on a proposal
- added test_pacemaker::duplicate()
- added hotstuff_8 unit test to test for duplicate votes
This fix is related to #1548 (lack of duplicate filtering only manifests with message propagation)
> IF: Filter duplicate votes

- libraries/custom_appbase/tests/custom_appbase_tests.cpp
Annoyingly, `std::count_if()` returns a signed type. So.. besides more refactoring and/or casting and/or new assignments.. this change was the best I came up with even though `num_expected` represents something unsigned. Feel free to suggest other approaches though
> fix some different signedness warnings in `custom_appbase_tests`

- tests/trx_generator/trx_provider.cpp
The non-default exception handler was masking the issue and not terminating the process which was causing misleading errors downstream. With default exception handler there is a better exception message as well as termination of the process. This provides better handling upstream in the performance harness.
This was being caused by an http response of `ok` with an empty string response body.
Using the default exception handler, the exception now looks like:
```error 2023-09-28T18:39:00.747 provider_ thread_utils.hpp:127          run_thread           ] Exiting thread provider_connection-0 on exception: 3100010 json_parse_exception: JSON parse exception
Fail to parse JSON from string:
    {"string":""}
    provider_connection-0  trx_provider.cpp:172 operator()
unexpected end of file
    {} …
```
> [PH] Trx Generator - Use default exception handler.

- plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
Remove `prometheus-exporter-address` option as the prometheus plugin can now be configured on a different address via https://github.com/AntelopeIO/leap/pull/1137.
For example:
```
http-server-address   = http-category-address
http-category-address = prometheus,127.0.0.1:9101
```
Includes a bit of include dependency cleanup.
Resolves #1681
> Remove prometheus-exporter-address option

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
- tests/trx_generator/http_client_async.hpp
- tests/trx_generator/trx_provider.cpp
When error conditions (eof) have the `http_plugin` `shutdown_both` on socket. Also call `close()` for good measure. I actually tried this explicit shutdown in the destructor but it seemed to make no difference.
Modify the `trx_generator` to better handle errors from client and also specify no keep alive.
This improved performance as can be seen by comparing:
This branch: https://github.com/AntelopeIO/leap/actions/runs/6356928532  15001 TPS
With main: https://github.com/AntelopeIO/leap/actions/runs/6356929999  14001 TPS
> Improve trx_generator http client

- libraries/chain/block_log.cpp
resolves #1348 
here is my test logs:
```
leap-util block-log --blocks-dir /home/dima/work/leap/build/unittests/snapshots/prod_sched  smoke-test
Smoke test of blocks.log and blocks.index in directory "/home/dima/work/leap/build/unittests/snapshots/prod_sched"
info  2023-10-02T23:37:54.770 leap-util block_log.cpp:1583            smoke_test           ] block log version= 2
info  2023-10-02T23:37:54.770 leap-util block_log.cpp:1584            smoke_test           ] first block= 1
info  2023-10-02T23:37:54.770 leap-util block_log.cpp:1585            smoke_test           ] last block= 5
error 2023-10-02T23:37:54.771 leap-util subcommand.cpp:10             print_exception      ] 3190000 block_log_exception: Block log exception
/home/dima/work/leap/build/unittests/snapshots/prod_sched/blocks.log …
```
> extend leap-util logs for smoke test

- package.cmake
No reason to keep using .tar.gz over .tar.zst. The `TZST` option was added in cmake 3.16, which is now our minimum version having dumped Ubuntu 18 support.
> generate `.tar.zst` out of `cpack` instead of `.tar.gz`

- tests/PerformanceHarness/performance_test_basic.py
The performance harness is evaluating performance of BP nodes or API nodes according to what they can individually handle. There is no need for the validation node or the API node to speculatively execute trxs. This removes load from the overall test rig allowing for better results. Also it better represents real-world API configuration.
> PH: Disable p2p trx execution on validation and api nodes

- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Updates `bios-boot-tutorial.py` with latest protocol features to disallow deferred transactions. 
- DISABLE_DEFERRED_TRXS_STAGE_1 - DISALLOW NEW DEFERRED TRANSACTIONS
- DISABLE_DEFERRED_TRXS_STAGE_2 - PREVENT PREVIOUSLY SCHEDULED DEFERRED TRANSACTIONS FROM REACHING OTHER NODES
Fixes #1720
> Add protocol features to disallow deferred transaction 

- libraries/custom_appbase/include/eosio/chain/application.hpp
- libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
- libraries/custom_appbase/tests/custom_appbase_tests.cpp
- plugins/producer_plugin/producer_plugin.cpp
* Always execute the lambda after pop()ing it from the queue. This is needed as the read_write queue is used to post the lambda that switches to the read window. The read window can then start and begin pushing future tasks to the read_write queue. This allows multiple threads to access the read_write at one time as the original call to switch to the read window is running unlocked, once it finishes it pops from the queue while other threads can access it. Backport of #1718 
* Fix for producer shutdown to prevent segfault and deadlock on shutdown. Backport of 1368ecd0b72f1387f0545c6deef9bd494b1aa7fe
Backport of #1718
Resolves #1490
> [4.0] Fix possible segfault switching between read/write windows

- tests/CMakeLists.txt
- tests/TestHarness/transactions.py
Occasionally `nodeos_extra_packed_data_test.py` test would fail because the setting of the `eosio.system` contract would take longer than the max trx cpu time. I think this test was more likely to fail in this way because it spawns more nodeos than other tests: `tests/nodeos_extra_packed_data_test.py -v -p 8`. There is no reason for this test to spawn so many producers.
Added a retry to `publishContract` to give the `set contract` a few tries before considering it a true failure.
Resolves #1501
> [5.0] Test: Retry set contract on failure

- tests/CMakeLists.txt
- tests/TestHarness/transactions.py
Occasionally `nodeos_extra_packed_data_test.py` test would fail because the setting of the `eosio.system` contract would take longer than the max trx cpu time. I think this test was more likely to fail in this way because it spawns more nodeos than other tests: `tests/nodeos_extra_packed_data_test.py -v -p 8`. There is no reason for this test to spawn so many producers.
Added a retry to `publishContract` to give the `set contract` a few tries before considering it a true failure.
Merges `release/5.0` into `main` including #1728 
Resolves #1501
> [5.0 -> main] Test: Retry set contract on failure

- programs/cleos/help_text.cpp.in
- programs/cleos/httpc.cpp
With the addition of https://github.com/AntelopeIO/leap/pull/1137 different categories of plugins can be configured to different endpoints. Update `cleos` error message to provide a better suggestion when feature is not available at provided endpoint.
Example output:
```
./cleos -u http://127.0.0.1:8081 net peers
Error 3110004: Missing Net API Plugin
Ensure that you have eosio::net_api_plugin added to your node's configuration and enabled on the specified endpoint.
For example:
http-server-address   = http-category-address
http-category-address = net_ro,127.0.0.1:8081
http-category-address = net_rw,[::]:8083
Error Details:
Net API plugin is not enabled on specified endpoint
```
Also updated history_api_plugin error details:
```
./cleos -u http://127.0.0.1:8081 get transaction …
```
> [5.0] Improve cleos error messages

- programs/cleos/help_text.cpp.in
- programs/cleos/httpc.cpp
With the addition of https://github.com/AntelopeIO/leap/pull/1137 different categories of plugins can be configured to different endpoints. Update `cleos` error message to provide a better suggestion when feature is not available at provided endpoint.
Example output:
```
./cleos -u http://127.0.0.1:8081 net peers
Error 3110004: Missing Net API Plugin
Ensure that you have eosio::net_api_plugin added to your node's configuration and enabled on the specified endpoint.
For example:
http-server-address   = http-category-address
http-category-address = net_ro,127.0.0.1:8081
http-category-address = net_rw,[::]:8083
Error Details:
Net API plugin is not enabled on specified endpoint
```
Also updated history_api_plugin error details:
```
./cleos -u http://127.0.0.1:8081 get transaction …
```
> [5.0 -> main] Improve cleos error messages

- tests/TestHarness/Node.py
- tests/TestHarness/queries.py
- tests/TestHarness/transactions.py
#1728 added a retry for `publishContract` (`set contract`), however, the retry never executed because the `waitForTransactionInBlock` would exit on error. Wired in passing `exitOnError` so that a retry could actually run.
Resolves #1501
> [5.0] Test: Pass in exitOnError so that a retry is allowed

- tests/TestHarness/Node.py
- tests/TestHarness/queries.py
- tests/TestHarness/transactions.py
#1728 added a retry for `publishContract` (`set contract`), however, the retry never executed because the `waitForTransactionInBlock` would exit on error. Wired in passing `exitOnError` so that a retry could actually run.
Merges `release/5.0` into `main` including #1739 
Resolves #1501
> [5.0 -> main] Test: Pass in exitOnError so that a retry is allowed

- plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
- plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
- plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/net_plugin/tests/CMakeLists.txt
- plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
- plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
- plugins/prometheus_plugin/metrics.hpp
- tests/CMakeLists.txt
- tests/TestHarness/testUtils.py
- tests/block_log_util_test.py
- tests/p2p_multiple_listen_test.py
- tests/p2p_sync_throttle_test.py
- tests/p2p_sync_throttle_test_shape.json
- tests/plugin_http_api_test.py
- tools/net-util.py
Peer to peer listen ports may now apply a block sync throttle.  Each occurrence of `p2p-listen-endpoint` has an independent throttle specification.  Here's the updated help text:
```
--p2p-listen-endpoint arg (=0.0.0.0:9876:0)
The actual host:port[:<rate-cap>] used
to listen for incoming p2p connections.
May be used multiple times.   The
optional rate cap will limit block sync
bandwidth to the specified rate.  A
number alone will be interpreted as
bytes per second.  The number may be
suffixed with units.  Supported units
are:   'B/s', 'KB/s', 'MB/s, 'GB/s',
'TB/s', 'KiB/s', 'MiB/s', 'GiB/s',
'TiB/s'.  Transactions and blocks
outside of sync mode are not throttled.
Examples:
192.168.0.100:9876:1MiB/s
node.eos.io:9876:1512KB/s
node.eos.io:9876:0.5GB/s …
```
> [5.0 -> main] Support throttling block syncing to peers

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/CMakeLists.txt
- plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
- tests/nodeos_chainbase_allocation_test.py
- unittests/api_tests.cpp
- unittests/delay_tests.cpp
- unittests/protocol_feature_tests.cpp
Resolved https://github.com/AntelopeIO/leap/issues/1730.
Unlinked block error was encountered in a replay of mainnet. It was caused by blocking any deferred trxs by https://github.com/AntelopeIO/leap/pull/1643.
This PR
* restored deferred trxs handling in transaction_context
* updated related tests
I have run replay tests from the mainnet and have passed the failed block 320405089 and trx 527bbf9029f604e7021be729c858fb520001c5c5413cbee2fc08dbcf735534bc,
starting from snapshot-2023-07-12-16-eos-v6-0319983883. The previously failed block was at Jul-14-2023, 10:33:36 PM.
I will do more replay tests over the weekend.
> [5.0] Fix unlinked blocks caused by deferred trx removal

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
- libraries/chain/transaction_context.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/CMakeLists.txt
- plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
- tests/nodeos_chainbase_allocation_test.py
- unittests/api_tests.cpp
- unittests/delay_tests.cpp
- unittests/protocol_feature_tests.cpp
Unlinked block error was encountered in a replay of mainnet. It was caused by disallowing any deferred trxs from changes introduced by https://github.com/AntelopeIO/leap/pull/1643.
This PR
* restores deferred trxs handling in transaction_context
* adds new tests and updates related tests
I have run replay tests from the mainnet and have passed the failed block 320405089 and trx 527bbf9029f604e7021be729c858fb520001c5c5413cbee2fc08dbcf735534bc,
starting from snapshot-2023-07-12-16-eos-v6-0319983883. The previously failed block was at Jul-14-2023, 10:33:36 PM. I also run tests starting from older snapshots and exercised more deferred transactions.
Merges `release/5.0` into `main` for https://github.com/AntelopeIO/leap/pull/1734
Resolves https://github.com/AntelopeIO/leap/issues/1730
> [5.0 -> main] Fix unlinked blocks caused by deferred trx removal

- tests/TestHarness/transactions.py
Recent test failure: https://github.com/AntelopeIO/leap/actions/runs/6476622261 shows that the 5s timeout allowed for a successful `set code` but not enough time for python test to observe the transaction in a block. Increase to 30s to allow for plenty of time for python to parse blocks looking for transaction.
Resolves #1501
> [5.0] Test: larger timeout of set contract

- tests/TestHarness/transactions.py
Recent test failure: https://github.com/AntelopeIO/leap/actions/runs/6476622261 shows that the 5s timeout allowed for a successful `set code` but not enough time for python test to observe the transaction in a block. Increase to 30s to allow for plenty of time for python to parse blocks looking for transaction.
Merges `release/5.0` into `main` including #1747 
Resolves #1501
> [5.0 -> main] Test: larger timeout of set contract

- .github/workflows/build.yaml
The leap repo has a branch protection rule that "All Required Tests Passed" is required to pass. At least I think that's what it's suppose to mean. Now I'm not sure because, mind bogglingly, when that test is skipped (because a dependent job failed) it doesn't block the PR! Consider this example where,
* "NP Tests (ubuntu20)" failed
* "All Required Tests Passed" was skipped, and
* Had 2 approvals
Expected behavior in this case is to not have the "white" merge button (it should be red for admins; and simply not allowed for non-admins).
So... restore this job back to how it was previously via `if: always()` and status checks on the dependent jobs.
Sending to 5.0 because this branch protection rule is important.
> [5.0] fix "All Required Tests Passed" CI Branch Protection

- plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
Fix compiler warning: `lambda capture 'return_failure_traces' is not used`
> [5.0] Fix compiler warning

- plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
Fix compiler warning: `lambda capture 'return_failure_traces' is not used`
Merges `release/5.0` into `main` including #1752
> [5.0 -> main] Fix compiler warning

- plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/prometheus_plugin/metrics.hpp
- tests/nodeos_run_test.py
- tests/p2p_sync_throttle_test.py
- tools/net-util.py
Use the `node_id` as a stable identifier for P2P connections in `prometheus_plugin`. The previous `connid_#`  would change on each disconnect/connect.
Example output:
```
nodeos_p2p_addr{address="localhost:9877 - 539b1ae",connid="539b1ae",ipv6="::ffff:127.0.0.1"} 0
nodeos_p2p_addr{address="localhost:9776 - 9069fa8",connid="9069fa8",ipv6="::ffff:127.0.0.1"} 0
nodeos_p2p_port{connid="539b1ae"} 60836
nodeos_p2p_port{connid="9069fa8"} 9776
nodeos_p2p_connection_number{connid="539b1ae"} 3
nodeos_p2p_connection_number{connid="9069fa8"} 1
nodeos_p2p_accepting_blocks{connid="539b1ae"} 1
nodeos_p2p_accepting_blocks{connid="9069fa8"} 1
nodeos_p2p_last_received_block{connid="539b1ae"} 583
nodeos_p2p_last_received_block{connid="9069fa8"} 316
nodeos_p2p_first_available_block{connid="539b1ae"} 0 …
```
> [5.0 -> main] Prometheus: Add stable identifier for P2P connections

- tests/test_read_only_trx.cpp
As of #1702 read only trxs should only be posted to `read_exclusive` queue. The `test_read_only_trx` test was posting them to the `read_only` queue which caused them to sometimes run during the write window. They were run in the write window because read only transactions are allowed to run on the main thread. It is not clear if this is why test failed but seems we can assume that is the problem unless it fails again. I ran the `test_read_only_trx` many times locally without failure with this fix.
Resolves #1736
> [5.0] Test: read-only trxs should only be posted to read_exclusive queue

- tests/test_read_only_trx.cpp
As of #1702 read only trxs should only be posted to `read_exclusive` queue. The `test_read_only_trx` test was posting them to the `read_only` queue which caused them to sometimes run during the write window. They were run in the write window because read only transactions are allowed to run on the main thread. It is not clear if this is why test failed but seems we can assume that is the problem unless it fails again. I ran the `test_read_only_trx` many times locally without failure with this fix.
Merges `release/5.0` into `main` including #1766
Resolves #1736
> [5.0 -> main] Test: read-only trxs should only be posted to read_exclusive queue

- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- tests/chain_plugin_tests.cpp
The wasm config settings returned by `/v1/chain/get_consensus_parameters` are only valid if the protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled. Only return `"wasm_config"` if protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled.
With protocol activated:
```
./cleos get consensus_parameters
{
"chain_config": {
"max_block_net_usage": 1048576,
"target_block_net_usage_pct": 1000,
"max_transaction_net_usage": 524288,
"base_per_transaction_net_usage": 12,
"net_usage_leeway": 500,
"context_free_discount_net_usage_num": 20,
"context_free_discount_net_usage_den": 100,
"max_block_cpu_usage": 500000,
"target_block_cpu_usage_pct": 1000,
"max_transaction_cpu_usage": 475000,
"min_transaction_cpu_usage": 100,
"max_transaction_lifetime": 3600,
"deferred_trx_expiration_window": 600, …
```
> [4.0] Only return wasm config settings if configurable wasm limits enabled

- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- tests/chain_plugin_tests.cpp
The wasm config settings returned by `/v1/chain/get_consensus_parameters` are only valid if the protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled. Only return `"wasm_config"` if protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled.
With protocol activated:
```
./cleos get consensus_parameters
{
"chain_config": {
"max_block_net_usage": 1048576,
"target_block_net_usage_pct": 1000,
"max_transaction_net_usage": 524288,
"base_per_transaction_net_usage": 12,
"net_usage_leeway": 500,
"context_free_discount_net_usage_num": 20,
"context_free_discount_net_usage_den": 100,
"max_block_cpu_usage": 500000,
"target_block_cpu_usage_pct": 1000,
"max_transaction_cpu_usage": 475000,
"min_transaction_cpu_usage": 100,
"max_transaction_lifetime": 3600,
"deferred_trx_expiration_window": 600, …
```
> [4.0 -> 5.0] Only return wasm config settings if configurable wasm limits enabled

- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- tests/chain_plugin_tests.cpp
The wasm config settings returned by `/v1/chain/get_consensus_parameters` are only valid if the protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled. Only return `"wasm_config"` if protocol feature `CONFIGURABLE_WASM_LIMITS2` is enabled.
With protocol activated:
```
./cleos get consensus_parameters
{
"chain_config": {
"max_block_net_usage": 1048576,
"target_block_net_usage_pct": 1000,
"max_transaction_net_usage": 524288,
"base_per_transaction_net_usage": 12,
"net_usage_leeway": 500,
"context_free_discount_net_usage_num": 20,
"context_free_discount_net_usage_den": 100,
"max_block_cpu_usage": 500000,
"target_block_cpu_usage_pct": 1000,
"max_transaction_cpu_usage": 475000,
"min_transaction_cpu_usage": 100,
"max_transaction_lifetime": 3600,
"deferred_trx_expiration_window": 600, …
```
> [5.0 -> main] Only return wasm config settings if configurable wasm limits enabled

- unittests/chain_tests.cpp
Backport of #1386 hence the small diff.
As indicated in #1275, produced blocks were signaled to plugins after being marked valid and placed in the forkdb but signaled before being marked valid and placed in the forkdb for validated blocks. This PR makes sure that the block is marked valid before being signaled for both produced blocks and validated blocks. Also refactors location of updating `head` for applied blocks, consolidating it in `commit_block`.
This also fixes #1694 as `head` is updated consistently before `accepted_block` is signaled which is what `state_history_plugin` SHiP is using for reporting `head` in `get_status_result_v0` messages.
Merges `release/4.0` into `release/5.0` including #1769 
Resolves #1275 
Resolves #1694
> [4.0 -> 5.0] Signal accepted_block after it is marked valid

- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/chain_plugin/chain_plugin.cpp
On startup recreate the EOS VM OC code cache if it is corrupt. The code cache is strictly a cache and can be recreated at anytime. No reason to stop startup with an error if it is corrupt, simply remove it and start over.
Also when `--replay-blockchain` is specified remove the code cache as it is likely not going to be useful and better to start from a clean slate.
Merges `release/4.0` into `release/5.0` including #1780 
Resolves #1406
> [4.0 -> 5.0] Recreate EOS VM OC code cache if corrupt

- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/chain_plugin/chain_plugin.cpp
On startup recreate the EOS VM OC code cache if it is corrupt. The code cache is strictly a cache and can be recreated at anytime. No reason to stop startup with an error if it is corrupt, simply remove it and start over.
Also when `--replay-blockchain` is specified remove the code cache as it is likely not going to be useful and better to start from a clean slate.
Merges `release/5.0` into `main` including #1780 & #1787
Resolves #1406
> [5.0 -> main] Recreate EOS VM OC code cache if corrupt

- plugins/net_plugin/net_plugin.cpp
When throttling was enabled on a connection, the `net_plugin` would assume the last block of a `peer_requested` was sent and reset the `peer_requested` indicating no other sync blocks need to be sent to the peer.  This caused the block to not be sent or rescheduled to be sent later resulting in the peer not receiving the block. The peer would have to wait for a full timeout before requesting the required block from a different peer.
Resolves #1776
> [5.0] P2P: Fix: Throttling of last block of request caused lost block

- plugins/net_plugin/net_plugin.cpp
When throttling was enabled on a connection, the `net_plugin` would assume the last block of a `peer_requested` was sent and reset the `peer_requested` indicating no other sync blocks need to be sent to the peer.  This caused the block to not be sent or rescheduled to be sent later resulting in the peer not receiving the block. The peer would have to wait for a full timeout before requesting the required block from a different peer.
Merges `release/5.0` into `main` including #1791 
Resolves #1776
> [5.0 -> main] P2P: Fix: Throttling of last block of request caused lost block

- tests/test_read_only_trx.cpp
`--eos-vm-oc-enable` option is only available when EOS VM OC is supported. Using the option when OC is not supported results in this test getting wedged due to an unknown option being used.
This fixes the test getting wedged on ARM, but maybe is not ideal since ultimately it results in the same test being run twice in such a case (since `--eos-vm-oc-enable=none` is always implied). Oh well.
But while in here I noticed something else sus: there is a `with_3_read_only_threads` & `with_3_read_only_threads_no_tierup`, and then a `with_8_read_only_threads` & `with_8_read_only_threads_no_tierup`. But `--eos-vm-oc-enable=none` is passed for _both_ "8" cases! I think the intention was `--eos-vm-oc-enable=none` should be passed for `3_no_tierup` and `8_no_tierup`, so I've tweaked it to be that way …
> [5.0] only use `--eos-vm-oc-enable` option in tests when OC is available, and tweak/fix location of its usage

- tests/test_read_only_trx.cpp
> [5.0 -> main] only use `--eos-vm-oc-enable` option in tests when OC is available, and tweak/fix location of its usage

- libraries/state_history/include/eosio/state_history/log.hpp
#1779 opens the index file in r/w mode. A `seek_end(0)` is need to make sure the index file is appended to.
Fixes issue introduced by #1779.
> [4.0] SHiP: Make sure we append to index file

- libraries/state_history/include/eosio/state_history/log.hpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/session_test.cpp
- tests/ship_streamer_test.py
Includes three SHiP `state_history_plugin` fixes:
* Fix for stack overflow due to recursive call to `send()`. Fixed by posting to the SHiP thread on new `send()`s.
* Fix for accessing wrong data after log splitting.
* Fix for accessing wrong file after log splitting.
Merges `release/4.0` into `release/5.0` including #1779 & #1801
Resolves #1677
> [4.0 -> 5.0] SHiP: Fixes: Stack overflow, invalid index, split file access

- libraries/state_history/include/eosio/state_history/log.hpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/state_history_plugin/tests/session_test.cpp
- tests/ship_streamer_test.py
Includes three SHiP `state_history_plugin` fixes:
* Fix for stack overflow due to recursive call to `send()`. Fixed by posting to the SHiP thread on new `send()`s.
* Fix for accessing wrong data after log splitting.
* Fix for accessing wrong file after log splitting.
Merges `release/5.0` into `main` including #1779 & #1801 & #1798
Resolves #1677
> [5.0 -> main] SHiP: Fixes: Stack overflow, invalid index, split file access

- .github/workflows/release.yaml
The `experimental-binaries` package is where we stash away some versioned packages that are not fully supported but we want indefinitely (they would eventually expire as a workflow artifact). Historically we've used this for `leap-dev.deb` which is used in CI, and ARM packages for DUNE -- both packages we don't fully support thus don't want them highly visible as a release asset.
Now that we're no longer creating ARM packages for DUNE, we can go ahead and automatically create the `experimental-binaries` package that solely stores `leap-dev.deb`. This is a rather obtuse procedure that has been done manually so automating it is a great improvement.
Clearly one of the problems with reviewing this is.. how to test it?! I don't have a good answer for that. I developed and tested it manually in …
> [5.0] automatically create `experimental-binaries` package on release

- .github/workflows/release.yaml
> [5.0 -> main] automatically create `experimental-binaries` package on release

- plugins/net_plugin/net_plugin.cpp
- tests/p2p_sync_throttle_test.py
Instead of calculating throttle limit from time of connection establishment, calculate over the specific enqueue sync window.
See https://github.com/AntelopeIO/leap/pull/1741 for original implementation. 
Update the throttle test to use more reasonable values.
Resolves #1808
> [5.0] P2P: Throttle over sync window

- plugins/net_plugin/net_plugin.cpp
- tests/p2p_sync_throttle_test.py
Instead of calculating throttle limit from time of connection establishment, calculate over the specific enqueue sync window.
See https://github.com/AntelopeIO/leap/pull/1741 for original implementation. 
Update the throttle test to use more reasonable values.
Merges `release/5.0` into `main` including #1811 
Resolves #1808
> [5.0 -> main] P2P: Throttle over sync window

- tests/test_read_only_trx.cpp
When `activate_protocol_features_set_bios_contract` => `set_code` => `push_input_trx` => `trx_future.get()` would throw it would cause the `app_thread` to deadlock because it would call `app_thread.join()` without first calling `app->quit()`. 
Introduced by https://github.com/AntelopeIO/leap/commit/3b2227ec9dbea7209bf63d7ff2f0a15b7422c1d8 of #1442. The terminate was actually better than dead lock, but with the `app->quit()` it exits with a nice error:
```
debug 2023-10-24T19:46:06.787 plugin_te producer_plugin.cpp:2081      log_trx_results      ] [TRX_TRACE] Block 4 for producer eosio is REJECTING tx: 8d44f8b6804a185d82af492cdd9866377548cc24cfbeda9be8e3ebb896bd46bb, auth: eosio, action: eosio:setcode, transaction 8d44f8b6804a185d82af492cdd9866377548cc24cfbeda9be8e3ebb896bd46bb was …
```
> [5.0] Test Fix: Avoid deadlock on app_thread

- plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp
Several resource monitor plugin tests use native `/tmp` as a monitored directory for testing. However, subdirectories in `/tmp` on test machine can be removed during a test run, causing `file_space_handler::add_file_system` to assert when doing `get_stat` on a removed directory, as shown by following failure:
`/__w/leap/leap/plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp(147): fatal error: in "resmon_plugin_tests/startupNormal": unexpected exception thrown by plugin_startup({"/tmp"})
`
I manually simulated a removed directory and reproduced the same failure.
This PR
* uses a fixed temp directory provided by `fc::temp_directory` instead of `/tmp`.
* removes a non-necessary no-value provided test. 
Resolves https://github.com/AntelopeIO/leap/issues/1824
> [5.0] make resource monitor plugin tests deterministic by using fixed fc::temp_directory instead of dynamic /tmp

- libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp
This may resolve #1823 & #1794 based on core dump analysis of an `oc-monitor` crash.
A single OC monitor process is created at launch of a parent process which plans to use OC (nodeos, a unit test application, etc). Critically, a single io_context is used in this single monitor process. As `code_cache`s are created on the parent process, `compile_monitor_session`s are created in the monitor process for each of those `code_cache` instances.
When a `code_cache` needs to compile a contract, it sends a message to its out of process `compile_monitor_session`. This will then call off to _another_ process -- the OC trampoline -- but the most important actions here to note is that the `compile_monitor_session` notes in its `current_compiles` a socket to receive a reply on from the trampoline, …
> [5.0] don't run EOS VM OC's monitor compile task callback when socket being dtored

- plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp
Several resource monitor plugin tests use native `/tmp` as a monitored directory for testing. However, subdirectories in `/tmp` on test machine can be removed during a test run, causing `file_space_handler::add_file_system` to assert when doing `get_stat` on a removed directory, as shown by following failure:
`/__w/leap/leap/plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp(147): fatal error: in "resmon_plugin_tests/startupNormal": unexpected exception thrown by plugin_startup({"/tmp"})
`
I manually simulated a removed directory and reproduced the same failure.
This PR
* uses a fixed temp directory provided by `fc::temp_directory` instead of `/tmp`.
* removes a non-necessary no-value provided test.
Merges release/5.0 into main including …
> [5.0 -> main] make resource monitor plugin tests deterministic by using fixed fc::temp_directory instead of dynamic /tmp

- tests/test_read_only_trx.cpp
`max-transaction-time` in read_only_trxs tests was originally set to 10000us. That's before `activate_protocol_features_set_bios_contract` was added. `activate_protocol_features_set_bios_contract` calls `set_code` to set bios contracts which can take more than 10000us; this causes the tests to fail.
This PR
* Increase max-transaction-time
* Refactor tests to use common command line arguments
Resolves #1816
> [5.0] Increase max-transaction-time for read_only_trx unit tests

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/chain_plugin/chain_plugin.cpp
Resolves #1764 
The reason I initially added this `revert_to_private_mode()` (so we'd load a snapshot in `mapped` mode, and revert to `mapped_private` mode after the snapshot is loaded), was that I hoped that we would only touch a few pages in normal `mapped_private` functioning.
The snapshot loading seemed a bad case where all state db pages containing data would be touched.
However, even in normal syncing, most of the pages are dirty after a few minutes, so the remap optimization is not worth it I believe.
> [5.0] Undo the temporary switch to `mapped` mode when loading a snapshot in `mapped_private` mode.

- tests/test_read_only_trx.cpp
`max-transaction-time` in read_only_trxs tests was originally set to 10000us. That's before `activate_protocol_features_set_bios_contract` was added. `activate_protocol_features_set_bios_contract` calls `set_code` to set bios contracts which can take more than 10000us; this causes the tests to fail.
This PR
* Increase max-transaction-time
* Refactor tests to use common command line arguments
Merges release/5.0 into main including https://github.com/AntelopeIO/leap/pull/1819
Resolves #1816
> [5.0 -> main] Increase max-transaction-time for read_only_trx unit tests

- plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
- plugins/state_history_plugin/tests/session_test.cpp
Fix new warnings so we have a clean rc3 build
```
plugins/net_plugin/tests/rate_limit_parse_unittest.cpp:23:4:   required from here
libraries/boost/libs/test/include/boost/test/tools/old/impl.hpp:107:17: warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Wsign-compare]
...
plugins/state_history_plugin/tests/session_test.cpp:488:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const uint32_t’ {aka ‘const unsigned int’} [-Wsign-compare]
488 |       for (int i = 0; i < head; ++i) {
|                       ~~^~~~~~
```
Resolves #1835
> [5.0] fix new signedness warnings to have a clean build for rc3

- plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
- plugins/state_history_plugin/tests/session_test.cpp
Replace https://github.com/AntelopeIO/leap/pull/1838 as base branch was wrong.
Fix new warnings so we have a clean rc3 build
```
plugins/net_plugin/tests/rate_limit_parse_unittest.cpp:23:4:   required from here
libraries/boost/libs/test/include/boost/test/tools/old/impl.hpp:107:17: warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Wsign-compare]
...
plugins/state_history_plugin/tests/session_test.cpp:488:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const uint32_t’ {aka ‘const unsigned int’} [-Wsign-compare]
488 |       for (int i = 0; i < head; ++i) {
|                       ~~^~~~~~
```
Merges release/5.0 into main including https://github.com/AntelopeIO/leap/pull/1836
Resolves #1835
> [5.0 -> main] fix new signedness warnings to have a clean build for rc3

- plugins/producer_plugin/producer_plugin.cpp
#1481 changed speculative block creation so that speculative blocks would always have a current block time. However, it didn't correctly handle the case where the configured producer was the scheduled producer but could not produce (e.g. incorrect configured private key). This PR simplifies the implementation to just use the producer schedule as configured by `produce-block-offset-ms` regardless if the block is speculative or a producer block. This normalizes block production time for speculative and producer blocks. I think this normalization is better than maintaining different block intervals for speculative vs producer nodes.
Resolves #1837
> [5.0] Normalize speculative & producer block intervals

- plugins/producer_plugin/producer_plugin.cpp
#1481 changed speculative block creation so that speculative blocks would always have a current block time. However, it didn't correctly handle the case where the configured producer was the scheduled producer but could not produce (e.g. incorrect configured private key). This PR simplifies the implementation to just use the producer schedule as configured by `produce-block-offset-ms` regardless if the block is speculative or a producer block. This normalizes block production time for speculative and producer blocks. I think this normalization is better than maintaining different block intervals for speculative vs producer nodes.
Merges `release/5.0` into `main` including #1840 
Resolves #1837
> [5.0 -> main] Normalize speculative & producer block intervals

- plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_block_timing_util.cpp
- tests/TestHarness/Node.py
- tests/distributed-transactions-test.py
Simplify and fix issues with #1481 block deadline calculation. Remove the concept of a hard deadline as producers want to produce a block even if the deadline has passed for the block. This uses a conservative calculation for producer wake up time, but does verify it is in the future.
Resolves #1831
> [5.0] Minimize abort/start block for speculative blocks

- plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/producer_plugin/test/test_block_timing_util.cpp
- tests/TestHarness/Node.py
- tests/distributed-transactions-test.py
Simplify and fix issues with #1481 block deadline calculation. Remove the concept of a hard deadline as producers want to produce a block even if the deadline has passed for the block. This uses a conservative calculation for producer wake up time, but does verify it is in the future.
Merges `release/5.0` into `main` including #1845 
Resolves #1837
> [5.0 -> main] Minimize abort/start block for speculative blocks

- CMakeLists.txt
- tests/CMakeLists.txt
- unittests/CMakeLists.txt
- unittests/wasm-spec-tests/generated-tests/CMakeLists.txt
Some of our tests require `--catch_system_errors=no` to properly operate, but there is another compelling reason to blanket this option on _all_ tests: gathering core dumps. Default behavior (`--catch_system_errors=yes`) will block core dump creation for those tests should they fail. Instead of needing to remember to sprinkle `--catch_system_errors=no` in all the various `add_test()` declarations (prone to missing some), we have some other options,
* set `BOOST_TEST_CATCH_SYSTEM_ERRORS` environment variable in CI. This allows CI to gobble up core dumps from any test, but introduces a difference in CI vs non-CI behavior
* plumb the option in boost test's C++ initialization (but this requires manual plumbing for every test)
* set the `BOOST_TEST_DEFAULTS_TO_CORE_DUMP` preprocessor macro
* …
> [5.0] globally (effectively) `--catch_system_errors=no` all boost-test based unit tests

- .github/actions/parallel-ctest-containers/action.yml
- .github/workflows/build.yaml
- .github/workflows/build_base.yaml
- .github/workflows/ph_backward_compatibility.yaml
Core dumps will now be uploaded from crashing tests in CI. Resolves #640. Example of failure and uploaded files can be found here,
https://github.com/AntelopeIO/leap/actions/runs/6724910321
(I trimmed the run down to just Tests & NP Tests on a single platform)
While I didn't change anything on the ENF runners to accomplish this, it's worth noting that this probably only works with ENF runners because of their behavior to put core dumps in to `/var/lib/systemd/coredump`. Something like Github's runners don't do that. While I like to keep the workflows runner-agnostic so that forks could potentially work in the future, afaik this won't break the workflow on other runners; you'll just miss out on the core dumps.
Coming along for the ride in some separate commits were a couple modifications …
> upload core dumps from failed tests in CI

- tests/PerformanceHarness/log_reader.py
- tests/PerformanceHarness/performance_test_basic.py
- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
- Performance harness tests were failing because the last few trxs from the `trx_generator` were being dropped. Modified the `trx_generator` to wait for all writes to finish before terminating.
- Modify the performance harness to wait for the complete test time for the trxs in blocks.
- Update the performance harness to `--print-missing-transactions` by default as this is very useful for debugging why the test failed.
- Updated Cluster.py to support `--produce-block-offset-ms 0` for older versions of `nodeos`.
Still need to run a complete test run on a quiescent machine.
Issue #1690
> [5.0] PH: Reliability improvements

- .github/actions/parallel-ctest-containers/action.yml
- .github/workflows/build.yaml
- .github/workflows/build_base.yaml
- .github/workflows/ph_backward_compatibility.yaml
- CMakeLists.txt
- tests/CMakeLists.txt
- unittests/CMakeLists.txt
- unittests/wasm-spec-tests/generated-tests/CMakeLists.txt
#1849 & #1850 were intended to go in 5.0 but.. whoops! This cherry-picks the commits from those two PRs that went in to `main` on to 5.0 since it brings enough utility that we'd like it in the 5.0 branch
> [5.0] backport: upload core dumps from failed tests in CI

- tests/PerformanceHarness/log_reader.py
- tests/PerformanceHarness/performance_test_basic.py
- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
- Performance harness tests were failing because the last few trxs from the `trx_generator` were being dropped. Modified the `trx_generator` to wait for all writes to finish before terminating.
- Modify the performance harness to wait for the complete test time for the trxs in blocks.
- Update the performance harness to `--print-missing-transactions` by default as this is very useful for debugging why the test failed.
- Updated Cluster.py to support `--produce-block-offset-ms 0` for older versions of `nodeos`.
Still need to run a complete test run on a quiescent machine.
Merges `release/5.0` into `main` including #1814 
Issue #1690
> [5.0 -> main] PH: Reliability improvements

- plugins/producer_plugin/producer_plugin.cpp
Using the chain thread pool improves TPS (eosio.token transfer per second) significantly. From ~25K to ~31K. Since this is a rather simple change targeting it for 5.0. With this PR the sequence is net-thread => chain-thread => producer-thread => main-thread.
An improved version of this code that avoids a thread hop will target 6.0; net-thread => chain-thread => main-thread.
Removing 2 thread hops is also possible by recovering the keys on the net thread, however that overwhelms the main thread; net-thread => main-thread. That improvement would require throttling the net threads so they do not overwhelm the main thread. The current mechanism of a limit on the number of active trxs works as a protection but is not ideal for performance measurement as it drops trxs instead of just delaying …
> [5.0] Recover keys in chain thread pool

- plugins/producer_plugin/producer_plugin.cpp
Using the chain thread pool improves TPS (eosio.token transfer per second) significantly. From ~25K to ~31K. Since this is a rather simple change targeting it for 5.0. With this PR the sequence is net-thread => chain-thread => producer-thread => main-thread.
An improved version of this code that avoids a thread hop will target 6.0; net-thread => chain-thread => main-thread. See #1859
Merges `release/5.0` into `main` including #1846 
Issue #1690
> [5.0 -> main] Recover keys in chain thread pool

- docs/01_nodeos/03_plugins/producer_plugin/index.md
- libraries/chain/include/eosio/chain/transaction_metadata.hpp
- libraries/chain/transaction_metadata.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/PerformanceHarness/README.md
- tests/PerformanceHarness/performance_test.py
- tests/PerformanceHarness/performance_test_basic.py
- tests/PerformanceHarnessScenarioRunner.py
- tests/p2p_high_latency_test.py
Remove the use of a `std::future` and `wait` in producer thread pool. Now after signature recovery is complete the chain thread posts directly to the main application thread. This improves the eosio token transfer per second (TPS) tests from ~31K TPS to ~36K TPS.
Transaction now transitions from net-thread => chain-thread => main-thread.
Removing the thread hop to chain-thread and performing key recovery on the net thread is possible (net-thread => main-thread), but testing shows it easily overwhelms the main-thread. Instead I think we need to create a memory pool of trxs that the main thread can pull from instead of pushing low priority tasks for trx execution to the main thread. That would greatly reduce the contention on the app post call and on the main thread priority queue. See …
> Remove thread hop to producer thread for trx signature recovery

- .github/workflows/release.yaml
I probably renamed asset-artifact-download-action's new input from `wait-for-exact-target-workflow` to `wait-for-exact-target` at the last moment, and neglected to update it here for this new usage of it.
Documentation of asset-artifact-download-action's inputs is here,
https://github.com/AntelopeIO/asset-artifact-download-action#inputs
> [5.0] fix release workflow's artifact download to `wait-for-exact-target` not `wait-for-exact-target-workflow`

- .github/workflows/release.yaml
main merge of #1867 fixing the release workflow for experimental-binaries
> [5.0 -> main] fix release workflow's artifact download to `wait-for-exact-target` not `wait-for-exact-target-workflow`

- tests/trx_generator/http_client_async.hpp
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
Update async http client to use one strand like the multi-threaded boost example.
Improve error reporting so an un-caught exception is not generated.
The core file of #1858 did not reveal anything useful. Do a bit of cleanup and hope for the best.
Maybe Resolves #1858
> [5.0] PH: Improve error handling and use one strand

- tests/trx_generator/http_client_async.hpp
- tests/trx_generator/trx_provider.cpp
- tests/trx_generator/trx_provider.hpp
Update async http client to use one strand like the multi-threaded boost example.
Improve error reporting so an un-caught exception is not generated.
The core file of #1858 did not reveal anything useful. Do a bit of cleanup and hope for the best.
Merges `release/5.0` into `main` including #1866 
Maybe Resolves #1858
> [5.0 -> main] PH: Improve error handling and use one strand

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/config.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_protocol.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/LLVMJIT.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/LLVMJIT.h
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp
- libraries/testing/include/eosio/testing/tester.hpp
- unittests/eosvmoc_limits_tests.cpp
When EOS VM OC is used in unit tests, contract actions are not dispatched until EOS VM OC has finished compilation. If a unit test violates EOS VM OC's subjective compilation limits, the unit test will fail. This is most notably problematic for EOS EVM because EOS EVM's exhaustive tests run afoul of OC's subjective limits. Another problem with OC's subjective limits  are they prevent ASAN from being used, because ASAN's 16TB of virtual memory usage is flagged by OC's subjective limits.
This PR disables OC subjective limits: `cpu limits`, `vm limits`, `stack size limit`, and `generated code size limit` in unit tests. It also adds unit tests to make sure limits to work properly.
Merges `release/5.0` into main including https://github.com/AntelopeIO/leap/pull/1843
Resolves …
> [5.0 -> main] Disable EOS VM OC's subjective compilation limits in unit tests

- plugins/net_plugin/net_plugin.cpp
- tests/p2p_sync_throttle_test.py
Make sure a valid and unique connection id is provided to prometheus. If not connected, then use a temporary id until the connection is established and a handshake is received.
Resolves #1871
> [5.0] Prometheus: Ensure valid unique_conn_node_id

- plugins/net_plugin/net_plugin.cpp
- tests/p2p_sync_throttle_test.py
Make sure a valid and unique connection id is provided to prometheus. If not connected, then use a temporary id until the connection is established and a handshake is received.
Merges `release/5.0` into `main` including #1879 
Resolves #1871
> [5.0 -> main] Prometheus: Ensure valid unique_conn_node_id

- tests/db_modes_test.sh
Add `mapped_private` to `db_modes_test.sh`.
> [5.0] Add additional tests for mapped_private

- libraries/libfc/include/fc/crypto/base64.hpp
- libraries/libfc/src/crypto/base64.cpp
- libraries/libfc/src/variant.cpp
- libraries/libfc/test/test_base64.cpp
- libraries/libfc/test/variant/test_variant.cpp
Reverts #1482 as it causes issues with backward compatibility with older version of nodeos. See #1883.
An alternative fix will be provided in a follow-on PR.
Re-open #1461
Resolves #1883
> [5.0] Revert "Fix base64 encoding"

- libraries/libfc/src/variant.cpp
All previous versions of nodeos required a trailing `=` for base64 encoded strings. `fc::variant` appends an extra `=` for all of its base64 encoded strings. However, non-fc base64 encoders do not add an extra `=` when one is not needed. This PR modifies `fc::variant` to support non-fc base64 encoded strings that do not have the extra `=`. 
In 5.0, `fc::variant` was updated to not add the extra `=` to base64 encoded strings. See #1888. This PR allows `nodeos` to support the new 5.0 version of base64 encoded strings.
Issue #1461
> [3.2] Do not require trailing `=` for base64 encoded strings

- libraries/libfc/include/fc/crypto/base64.hpp
- libraries/libfc/src/crypto/base64.cpp
- libraries/libfc/src/variant.cpp
- libraries/libfc/test/test_base64.cpp
- libraries/libfc/test/variant/test_variant.cpp
Reverts #1482 as it causes issues with backward compatibility with older version of nodeos. See #1883.
An alternative fix will be provided in a follow-on PR.
Merges `release/5.0` into `main` including #1886 
Re-open #1461
Resolves #1883
> [5.0 -> main] Revert "Fix base64 encoding"

- libraries/chain/include/eosio/chain/database_utils.hpp
- libraries/libfc/include/fc/crypto/base64.hpp
- libraries/libfc/src/crypto/base64.cpp
- libraries/libfc/src/crypto/bigint.cpp
- libraries/libfc/src/crypto/elliptic_webauthn.cpp
- libraries/libfc/src/variant.cpp
- libraries/libfc/test/test_base64.cpp
- libraries/libfc/test/variant/test_variant.cpp
- tests/nodeos_run_test.py
#1482 fixed base64 encoding by removing the unneeded extra `=` that variant added to base64 encoded data. However, it also updated the base64 library with a stricter one. This PR leaves the old base64 encoding/decoding library but does remove the extra `=` from the base64 encoded data so non-fc base64 decoders will not claim the data is invalid.
This change still breaks backward compatibility with 3.2 & 4.0 `cleos/nodeos`. PRs to 3.2 (#1889) and 4.0 will be created that will allow them to work with this new base64 encoding (they will no longer expect the invalid `=` character).
PR #1886 reverts #1482. This PR provided an alternative fix for #1461.
Included in this PR is an optimization to the existing `base64_decode` to avoid a copy for our use-cases by returning a `vector<char>` instead …
> [5.0] Fix base64 encoding - take 2

- libraries/libfc/src/variant.cpp
All previous versions of nodeos required a trailing `=` for base64 encoded strings. `fc::variant` appends an extra `=` for all of its base64 encoded strings. However, non-fc base64 encoders do not add an extra `=` when one is not needed. This PR modifies `fc::variant` to support non-fc base64 encoded strings that do not have the extra `=`. 
In 5.0, `fc::variant` was updated to not add the extra `=` to base64 encoded strings. See #1888. This PR allows `nodeos` to support the new 5.0 version of base64 encoded strings.
Merges `release/3.2` into `release/4.0` including #1889 
Issue #1461
> [3.2 -> 4.0] Do not require trailing `=` for base64 encoded strings

- libraries/chain/include/eosio/chain/database_utils.hpp
- libraries/libfc/include/fc/crypto/base64.hpp
- libraries/libfc/src/crypto/base64.cpp
- libraries/libfc/src/crypto/bigint.cpp
- libraries/libfc/src/crypto/elliptic_webauthn.cpp
- libraries/libfc/src/variant.cpp
- libraries/libfc/test/test_base64.cpp
- libraries/libfc/test/variant/test_variant.cpp
- tests/nodeos_run_test.py
#1482 fixed base64 encoding by removing the unneeded extra `=` that variant added to base64 encoded data. However, it also updated the base64 library with a stricter one. This PR leaves the old base64 encoding/decoding library but does remove the extra `=` from the base64 encoded data so non-fc base64 decoders will not claim the data is invalid.
This change still breaks backward compatibility with 3.2 & 4.0 `cleos/nodeos`. PRs to 3.2 (#1889) and 4.0 will be created that will allow them to work with this new base64 encoding (they will no longer expect the invalid `=` character).
PR #1886 reverts #1482. This PR provided an alternative fix for #1461.
Included in this PR is an optimization to the existing `base64_decode` to avoid a copy for our use-cases by returning a `vector<char>` instead …
> [5.0 -> main] Fix base64 encoding - take 2

- benchmark/CMakeLists.txt
- benchmark/alt_bn_128.cpp
- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/blake2.cpp
- benchmark/bls.cpp
- benchmark/hash.cpp
- benchmark/key.cpp
- benchmark/main.cpp
- benchmark/modexp.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
Add benchmarking of BLS host functions into `Leap` Benchmark suites. Those host functions are directly benchmarked without using CDT wrappers.
Use `benchmark/benchmark -f bls` to benchmark. A sample result looks like
```
function                    runs        average       minimum       maximum
bls:
bls_g1_add                  1,000       2,736 ns       2,607 ns      10,048 ns
bls_g2_add                  1,000       6,766 ns       6,461 ns      13,983 ns
bls_g1_mul                  1,000     193,676 ns     191,533 ns     204,904 ns
bls_g2_mul                  1,000     486,744 ns     480,722 ns     516,755 ns
bls_pairing 1 pair          1,000   1,284,147 ns   1,263,355 ns   1,521,806 ns
bls_pairing 3 pairs         1,000   2,095,239 ns   2,060,983 ns   2,448,659 ns
bls_g1_exp 1 point …
```
> [5.0] Benchmark BLS host functions

- programs/cleos/main.cpp
Cleos `set code` and `set abi` have not worked since `release/3.2`. The root cause is the common code `set_code_callback` for `set contract` and `set code` assumes `contract-dir` argument which is only applicable to `set contract`; and the common code `set_code_callback` for `set abi` and `set code` assumes `contract-dir` argument too.
This PR fixes the problem.
The fix has been tested manually. CI tests will be added to `release/5.0` to minimize changes to 4.0.
Merges release/3.2 into release/4.0 including [#1897](https://github.com/AntelopeIO/leap/pull/1897)
Resolves https://github.com/AntelopeIO/leap/issues/1868.
> [3.2 -> 4.0] Fix non-working cleos set code and set abi commands

- benchmark/CMakeLists.txt
- benchmark/alt_bn_128.cpp
- benchmark/benchmark.cpp
- benchmark/benchmark.hpp
- benchmark/blake2.cpp
- benchmark/bls.cpp
- benchmark/hash.cpp
- benchmark/key.cpp
- benchmark/main.cpp
- benchmark/modexp.cpp
- libraries/chain/include/eosio/chain/transaction_context.hpp
Merging `release/5.0` into `main` including #1889 & #1892 (all empty commits superseded by #1888) and #1884.
========================
Add benchmarking of BLS host functions into `Leap` Benchmark suites. Those host functions are directly benchmarked without using CDT wrappers.
Use `benchmark/benchmark -f bls` to benchmark. A sample result looks like
```
function                    runs        average       minimum       maximum
bls:
bls_g1_add                  1,000       2,736 ns       2,607 ns      10,048 ns
bls_g2_add                  1,000       6,766 ns       6,461 ns      13,983 ns
bls_g1_mul                  1,000     193,676 ns     191,533 ns     204,904 ns
bls_g2_mul                  1,000     486,744 ns     480,722 ns     516,755 ns
bls_pairing 1 pair          1,000   1,284,147 …
```
> [5.0 -> main] Benchmark BLS host functions, Do not require trailing = for base64 encoded strings

- plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
- plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/net_plugin/tests/CMakeLists.txt
- plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
- plugins/net_plugin/tests/main.cpp
- plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
- Remove the include of `net_plugin.cpp` in `rate_limit_parse_unittest.cpp` by moving functions to `net_utils.hpp`
- Combine all `net_plugin` tests into one test executable
> [5.0] Test: net_plugin test cleanup

- programs/cleos/main.cpp
- tests/CMakeLists.txt
- tests/TestHarness/transactions.py
- tests/nodeos_run_test.py
Cleos `set code` and `set abi` have not worked since `release/3.2`. The root cause is the common code `set_code_callback` for `set contract` and `set code` assumes `contract-dir` argument which is only applicable to `set contract`; and the common code `set_code_callback` for `set abi` and `set code` assumes `contract-dir` argument too.
Merges fix from `release/5.0` into `main` including [#1909](https://github.com/AntelopeIO/leap/pull/1909).
In addition to the fix, tests are added in this PR for `release/5.0` and `main`.
Resolves https://github.com/AntelopeIO/leap/issues/1868.
> [5.0 -> main] Fix non-working cleos set code and set abi commands, and add tests

- libraries/libfc/include/fc/io/raw.hpp
- libraries/libfc/test/network/test_message_buffer.cpp
- pack parameters were passed by value causing unneeded copies.
- packing a `char*` was unnecessarily allocating a temp `std::string`.
- added `std::tuple` support for `pack`, so that we can provide lists longer than pairs, so we don't have to do [this](https://github.com/AntelopeIO/leap/blob/4b34cf572886dda4641c650d36a142bd2aeea3bc/libraries/chain/include/eosio/chain/hotstuff.hpp#L17-L18).
> Fix a couple perf issues in `fc::raw::pack` and add tuple support.

- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/chain_pacemaker.cpp
- libraries/hotstuff/include/eosio/hotstuff/base_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/include/eosio/hotstuff/test_pacemaker.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- libraries/hotstuff/test/test_pacemaker.cpp
This addresses the first part (1 of 2) of #1910 
The "new block" message implements the separation between proposers and leaders, which is not supported in Leap 6, so it is being removed.
Also removed some dead code.
> IF: Remove the Hotstuff "new block" message

- libraries/chain/block_header_state.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- unittests/block_header_state_tests.cpp
Part 1 of https://github.com/AntelopeIO/leap/issues/1912. It implements `block_header_state_core` (to hold hotstuff core information associated with each block) and its state transitions.
Extensive unit tests are added.
Part 2 for qc_chain to track the state will be in a separate PR.
> IF: implement block_header_state_core and its state transition

- libraries/chain/include/eosio/chain/hotstuff.hpp
- libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
- libraries/hotstuff/qc_chain.cpp
- libraries/hotstuff/test/test_hotstuff.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- chained_mode variable removed
- removed (chained_mode == false) code path in qc_chain::process_vote()
- fixed asserts in test_hotstuff.cpp to reflect chained mode outcome, without modifying test logic (this reduces test coverage, which will be restored later)
This is part of the work for #1910 . It's not a blocker for solving the whole issue, but I wanted this to be a discrete PR.
> IF: remove event-driven mode 

- libraries/chain/webassembly/privileged.cpp
- libraries/testing/tester.cpp
- unittests/api_tests.cpp
`fthreshold` should be `>` to ensure Byzantine fault tolerance of at least one.
Issue #1916
> IF: Fix set_finalizers fthreshold check

- libraries/chain/webassembly/privileged.cpp
- libraries/libfc/include/fc/crypto/bls_public_key.hpp
- libraries/libfc/include/fc/crypto/bls_signature.hpp
- libraries/libfc/src/crypto/bls_public_key.cpp
- libraries/libfc/src/crypto/bls_signature.cpp
- libraries/libfc/test/test_bls.cpp
Merge `main` as of 12-05-2023 into `hotstuff_integration` includes bls12-381 update for proof of possession in affine non-montgomery form.
Use affine non-montgomery base64 encoding for `bls_public_key` and `bls_signature`.
Update host function `set_finalizers` to expect `bls_public_key` in affine non-montgomery form.
> IF: Merge main 12-05-2023 - affine non-montgomery bls public key and signature

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/merkle.hpp
- libraries/chain/merkle.cpp
- unittests/merkle_tree_tests.cpp
Use merkle calculation for `transaction_mroot` and `action_mroot` that does not use bitflip implementation after hotstuff activation.
Resolves #1942
> IF: merkle calculation for transaction_mroot and action_mroot

- libraries/chain/include/eosio/chain/contract_table_objects.hpp
- libraries/chain/include/eosio/chain/database_utils.hpp
- libraries/state_history/include/eosio/state_history/serialization.hpp
- libraries/state_history/include/eosio/state_history/types.hpp
- unittests/state_history_tests.cpp
> [3.2 -> 4.0] consolidated security fixes for 4.0.5

- .github/workflows/pinned_build.yaml
`pinned_build.yaml` was removed in 5.0 (and thus main) since the pinned builds are performed together with the non-pinned builds that normally occur in `build.yaml`; i.e. this separate workflow is no longer needed. But that means it's no longer possible to manually kick off this workflow for pre-5.0 branches -- something we need for 3.x & 4.0 releases.
Add back a stub workflow that allows the `pinned_build.yaml` to be manually run for 3.x & 4.0, for now.
> add a stub `pinned_build.yaml` on main so the pinned build can be performed in CI for 3.x/4.0

- libraries/chain/include/eosio/chain/contract_table_objects.hpp
- libraries/chain/include/eosio/chain/database_utils.hpp
- libraries/state_history/include/eosio/state_history/serialization.hpp
- libraries/state_history/include/eosio/state_history/types.hpp
- unittests/state_history_tests.cpp
Merges up #1964 from 4.0; originally #1961 from 3.2
> [4.0 -> 5.0] consolidated security fixes for 5.0.0-rc3

- libraries/libfc/test/crypto/test_webauthn.cpp
add some tests exploring the validity of various webauthn parsing
> add some addtional webauthn tests

- .github/workflows/release.yaml
The release workflow to create `experimental-binaries` failed to run on the 5.0.0-rc3 release because a ghcr image tag must be lowercase and `AntelopeIO` isn't,
https://github.com/AntelopeIO/leap/actions/runs/7135123841
Lowercase the repository owner for the image tag name.
> [5.0] fix `experimental-binaries` creation on releases: lowercase org name in image tag

- libraries/chain/block_header_state_legacy.cpp
- libraries/chain/block_state_legacy.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
- libraries/chain/include/eosio/chain/block_state_legacy.hpp
- plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
- plugins/chain_plugin/test/test_trx_retry_db.cpp
- plugins/trace_api_plugin/test/include/eosio/trace_api/test_common.hpp
- unittests/unapplied_transaction_queue_tests.cpp
Rename `pending_block_header_state` to `pending_block_header_state_legacy`.
Resolved https://github.com/AntelopeIO/leap/issues/1940
> Rename pending_block_header_state to pending_block_header_state_legacy

- .github/workflows/release.yaml
> [5.0 -> main] fix `experimental-binaries` creation on releases: lowercase org name in image tag

- libraries/chain/controller.cpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- SHiP - Added block id to `this_block` output of `pushing result` log message.
```
info  2023-12-12T14:55:21.213 ship-0    session.hpp:547               send_update          ] pushing result {"head":{"block_num":397},"last_irreversible":{"block_num":57},"this_block":{"block_num":397, "block_id":0000018d5fb988342f29ac31a55ada90d20cb993f344fc4ee3f9963451b69a7b}} to send queue
```
- controller - Added applied and removed block ids to `successfully switched fork` log message. Note that most fork switches are much smaller than this example from a test that purposely creates a large fork.
```
info  2023-12-12T14:47:54.008 nodeos    controller.cpp:2424           maybe_switch_forks   ] successfully switched fork to new head 0000007b225de24730b455eef258f77689976ac8533a0f7482f1ee008e8e7db1, …
```
> [5.0 -> main] Extra info level logging

- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Replace `BLS_PRIMITIVES` with `BLS_PRIMITIVES2`.
> [5.0] Add BLS_PRIMITIVES2 to bios-boot-tutorial.py

- .github/workflows/build.yaml
By far the primary purpose of the libtester tests are to ensure we didn't goof proper referencing or installation of a libtester dependency since they aren't handled automatically. It's easy to break in one of the three ways we support.
Testing libtester on all the supported Ubuntu versions is a distant second purpose. But I am not sure I can think of cases where this has gone awry recently, and there is nothing in libtester's cmake complexity that is different for different Linux distros.
Due to #1936 let's just remove libtester testing on ubuntu20 for now. While I'm sure it's possible (even easy) to fix the underlying issue of needing to use a newer compiler for these tests on ubuntu20, it's nice not to add more complexity for this case imo. Resolves #1936 indirectly.
> only run libtester tests on ubuntu22

- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Replace `BLS_PRIMITIVES` with `BLS_PRIMITIVES2`.
Merges `release/5.0` into `main` including #1986
> [5.0 -> main] Add BLS_PRIMITIVES2 to bios-boot-tutorial.py

- tests/trx_generator/trx_provider.cpp
Add an `on_except` so `named_thread_pool` does not terminate when connection lost to client. This should fix the core dumps found in ci/cd runs such as https://github.com/AntelopeIO/leap/issues/1865
This is not a fix for #1865, as something caused nodeos to die for the `trx_generator` to lose connection and core dump. This PR however should remove the red herring of the trx_generator core files in ci/cd.
> [5.0] Test: Fix trx_generator handling of connection lost

- libraries/chain/hotstuff/test/test_hotstuff.cpp
- libraries/chain/include/eosio/chain/hotstuff/finalizer_authority.hpp
- libraries/chain/include/eosio/chain/hotstuff/finalizer_policy.hpp
- libraries/chain/webassembly/privileged.cpp
- unittests/api_tests.cpp
No change in functionality, just renaming.
Resolves #1992
> IF: Use `set_finalizer` type names that match `eosio.bios` and CDT

- tests/trx_generator/trx_provider.cpp
Add an `on_except` so `named_thread_pool` does not terminate when connection lost to client. This should fix the core dumps found in ci/cd runs such as https://github.com/AntelopeIO/leap/issues/1865
This is not a fix for #1865, as something caused nodeos to die for the `trx_generator` to lose connection and core dump. This PR however should remove the red herring of the trx_generator core files in ci/cd. 
Merges `release/5.0` into `main` including #2000
> [5.0 -> main] Test: Fix trx_generator handling of connection lost

- plugins/net_plugin/net_plugin.cpp
When running with `block-log-retain-blocks = 0`, many `unlinkable block` exceptions were generated.
Do not attempt to apply blocks that are before LIB. 
Blocks are received before LIB because we always sync from LIB to make sure we see all possible forks. However, between the request and the blocks coming in, LIB can move. When running with no block log, these blocks are not known to have already been processed. However, there is never any reason to attempt to apply blocks that are <= LIB, so just drop them instead of attempting to apply them.
Merges `release/5.0` into `main` including #2007
Resolves #2006
> [5.0 -> main] Fix unlinkable block exceptions when block-log-retain-blocks = 0

- tests/nodeos_startup_catchup.py
Update `nodeos_startup_catchup.py` test to sync with `--block-log-retain-blocks=0` and verify no `unlinkable` blocks.
Test fails before #2007 fix.
Resolves #2006
> [5.0] Test: Check for unlinkable blocks while syncing

- tests/nodeos_startup_catchup.py
Lin was correct on: https://github.com/AntelopeIO/leap/pull/2008#discussion_r1432885079
Test needs a bit more tolerance of a few unlinkable blocks. See https://github.com/AntelopeIO/leap/actions/runs/7280646786/job/19839818772
Resolves #2006
> [5.0] Test: Check for unlinkable blocks while syncing - 2

- tests/nodeos_startup_catchup.py
Update `nodeos_startup_catchup.py` test to sync with `--block-log-retain-blocks=0` and verify no `unlinkable` blocks.
Test fails before #2007 fix.
Merges `release/5.0` into `main` including #2008 & #2015
Resolves #2006
> [5.0 -> main] Test: Check for unlinkable blocks while syncing

- libraries/chain/controller.cpp
- libraries/chain/hotstuff/chain_pacemaker.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/producer_schedule.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_api_plugin/chain.swagger.yaml
- plugins/chain_api_plugin/chain_api_plugin.cpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- plugins/state_history_plugin/state_history_plugin.cpp
- plugins/test_control_plugin/test_control_plugin.cpp
- programs/cleos/httpc.hpp
- programs/cleos/main.cpp
- tests/plugin_http_api_test.py
- tests/test_chain_plugin.cpp
- unittests/block_tests.cpp
- unittests/bootseq_tests.cpp
- unittests/chain_tests.cpp
- unittests/database_tests.cpp
- unittests/eosio_system_tester.hpp
- unittests/forked_tests.cpp
- unittests/producer_schedule_tests.cpp
- unittests/protocol_feature_tests.cpp
- unittests/special_accounts_tests.cpp
- Removed most uses of `controller::head_block_state()`
- Renamed `controller::head_block_state()` to `controller::head_block_state_legacy()` for remaning uses in tests
- Added `controller::had_block_timestamp()`
- Removed `/v1/chain/get_block_header_state`
- Removed `controller::fetch_block_state_by_number()`
- Removed `controller::fetch_block_state_by_id()`
> IF: Remove block_state_legacy access

- .cicd/defaults.json
- .github/workflows/build.yaml
- plugins/net_plugin/net_plugin.cpp
- tests/nodeos_startup_catchup.py
- tests/trx_generator/trx_provider.cpp
Bring in libtester tests with reference contracts instead of eos-system-contracts.
Clean merge.
> IF: Merge main 12-22-2023

- libraries/chain/snapshot.cpp
(at least in gcc 13.2.1's libstdc++, and libc++ 17.0.2 as used in 5.0's pinned builds) calling `ofstream::tellp()` always results in an `lseek(SEEK_CUR)` syscall. Thus, snapshot code was generating a syscall per-row write. This alone is substantial overhead, but libc++ seems to also flush its buffer on these calls resulting in an additional (typically tiny) `write()` call once write per row. These tiny write calls cause builds with libc++ (the pinned builds) to perform substantially worse creating snapshots -- easily 5x+ slower than with libstdc++ in my tests. I suspect there are certain configurations that are well above 10x slower.
I can't find any reasonable explanation for the current code's existing defensive pattern. Sure, if a row fails to write it'd rewind future writes to be on …
> [5.0] remove per-row `tellp()` during snapshot creation boosting performance

- libraries/chain/snapshot.cpp
merges to main #2026 performance improvement for creating snapshots
> [5.0 -> main] remove per-row `tellp()` during snapshot creation boosting performance

- CMakeModules/EosioTesterBuild.cmake.in
- libraries/chain/CMakeLists.txt
- libraries/chain/abi_serializer.cpp
- libraries/chain/controller.cpp
- libraries/chain/hotstuff/chain_pacemaker.cpp
- libraries/chain/hotstuff/instant_finality_extension.cpp
- libraries/chain/include/eosio/chain/abi_serializer.hpp
- libraries/chain/include/eosio/chain/block_header.hpp
- libraries/chain/include/eosio/chain/hotstuff/finalizer_policy.hpp
- libraries/chain/include/eosio/chain/hotstuff/instant_finality_extension.hpp
- libraries/chain/include/eosio/chain/hotstuff/proposer_policy.hpp
- unittests/api_tests.cpp
- unittests/block_header_tests.cpp
* replaced `finalizer_policy_extension` and `proposal_info_extension` with `instant_finality_extension`
* added tests for `instant_finality_extension`
Resolved https://github.com/AntelopeIO/leap/issues/1911
> IF: Block header extension -- replace finalizer_policy_extension and proposal_info_extension with instant_finality_extension

- plugins/net_plugin/net_plugin.cpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
appbase plugins are constructed no matter if they are enabled or not. This meant no matter whether the `prometheus_plugin` was enabled it would install its handlers in to `http_plugin`, `net_plugin`, etc. These handlers always `post()` to `prometheus_plugin`'s strand. But when `prometheus_plugin` isn't enabled its strand is never serviced leading to an endlessly growing queue that is never drained. Each HTTP request would add on to this queue, for example.
Move the handler registration to `plugin_initialize()` so handlers will only be registered when the plugin is enabled ergo when the strand will be pumped. (this is actually how it was prior to #1074, which makes me wonder if there was a need for this change, but I am not immediately seeing one)
Resolves #2030
> [5.0] only register prometheus handlers when `prometheus_plugin` enabled; fixing memory leak

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/net_plugin/net_plugin.cpp
Pause `net_plugin` while generating snapshot. With the threads of the `net_plugin` continuing to run they queue up many blocks to be processed consuming large amounts of RAM.
Verification testing in progress.
Resolves #2021
Resolves #1128
> [5.0] P2P: Pause net_plugin during snapshot write

- plugins/net_plugin/net_plugin.cpp
- plugins/prometheus_plugin/prometheus_plugin.cpp
main merge of #2038 to fix leak when prometheus not enabled; resolves #2030
> [5.0 -> main] only register prometheus handlers when `prometheus_plugin` enabled; fixing memory leak

- libraries/chain/controller.cpp
https://github.com/AntelopeIO/leap/issues/2028 reports `transaction_mroot` difference between when it is first calculated and when it is recreated in `create_block_state_i`. The difference  is caused by the way how `hs_active` is determined for mroot calculation. When `transaction_mroot`  is first created, `hs_lib > 0` is used as an indication of `hs_active`; in `create_block_state_i`, only presence of `instant_finality_extension` is used.
This inconsistency causes integration test failures too.
This PR changes to use  the same `hs_lib > 0` as the indication.
Resolved https://github.com/AntelopeIO/leap/issues/2028
> IF: use the same way to determine if instant finality is active

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/config.hpp
- unittests/eosvmoc_limits_tests.cpp
EOS VM OC's subjective limits were not actually disabled in tests as expected in #1843 due to unexpected deserialization behavior of `eosio::chain::eosvmoc::config`.
> [5.0] fix disabling EOS VM OC subjective limits in tests

- libraries/chain/block_header_state_legacy.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
- unittests/api_tests.cpp
- unittests/producer_schedule_hs_tests.cpp
Add finalizer policy to block header extension. Needed for reference contract tests.
> IF: finalizer policy to block header extension

- plugins/producer_plugin/producer_plugin.cpp
- plugins/signature_provider_plugin/signature_provider_plugin.cpp
- tests/TestHarness/launcher.py
BLS public keys are base64 encoded which include trailing `=`. Update the `signature-provider` parsing to expect these "extra" `=`s. 
Shutdown on startup for malformed `signature-provider` arguments. Previously nodeos would log an error and continue.
Resolves #2060
> IF: Update signature-provider parsing for base64 BLS public keys

- libraries/chain/block_header_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- libraries/chain/include/eosio/chain/block_header_state_utils.hpp
- libraries/chain/include/eosio/chain/block_state_legacy.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/hotstuff/instant_finality_extension.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/net_plugin/net_plugin.cpp
- unittests/block_header_tests.cpp
- unittests/chain_tests.cpp
- unittests/producer_schedule_tests.cpp
- Implement proposer policy change design: https://hackmd.io/@9xzIZ7ZaRwegCHgQW02r3Q/BkQ4Oc4Up
- Producer schedule is changed after `set_proposed_producer` in the next, next producer round.
- For example: Producer A [ b1, b2, .. b12 ], Producer B [ b1, b2, .. b12 ], Producer X [ b1, b2, .. b12 ]
- If `set_proposed_producer` is called in trx in any blocks of Producer A [ b1, b2, .. b12], the schedule change happens at Producer X [b1]. 
- public controller `pending_producers()` and `proposed_producers` renamed to `_legacy`.
- Added `next_producers()` for use by external enties.
> IF: Implement proposer policy change

- docs/block_production/lifecycle.md
- libraries/chain/block_header_state.cpp
- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/hotstuff/chain_pacemaker.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/chain/include/eosio/chain/block_state_legacy.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
- libraries/chain/resource_limits.cpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/CMakeLists.txt
- tests/TestHarness/Cluster.py
- unittests/api_tests.cpp
- unittests/block_tests.cpp
- unittests/chain_tests.cpp
- unittests/forked_tests.cpp
- unittests/producer_schedule_hs_tests.cpp
- unittests/protocol_feature_tests.cpp
- unittests/unapplied_transaction_queue_tests.cpp
- Transition from dpos to instant-finality on the block after `set_finalizer` host function call. This is a temporary method of transition until we work out the algorithm to use in production.
- `fork_database` switched over after block with `set_finalizer` call.
- Add `block_token` as a wrapper of `block_state_ptr` and `block_state_legacy_ptr`.
- `block_state` no longer used outside of chain library except for leap-util `blocklog_actions::read_log` which will be fixed by #2083 
- Enable `instant-finality` `nodeos_run_test.py` integration test which tests transition.
- Performance improvement via `controller::block_exists` instead of always pulling the complete block out of the block log.
- Fixes producer schedule switch bug after instant-finality is enabled.
- LIB does not advance after …
> IF: Transition from dpos to instant-finality

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
During the destruction of `beast_http_session`,
https://github.com/AntelopeIO/leap/blob/04774eb7726ae95a6cb795b493fcf0f25021bc5f/plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp#L270-L281
there are accesses to `plugin_state_` which is simply a reference to an object that lives in `http_plugin_impl`,
https://github.com/AntelopeIO/leap/blob/04774eb7726ae95a6cb795b493fcf0f25021bc5f/plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp#L86
Additionally, notice that `beast_http_session`'s `socket_` has been constructed with the io_context from `http_plugin_impl::plugin_state`'s `thread_pool`. So destruction of the `socket_` will also require valid access to the `plugin_state` object.
But it is possible for a `beast_http_session` to outlive `http_plugin` which …
> [5.0] extend life of `http_plugin_state` to ensure no invalid memory accesses during nodeos shutdown

- libraries/chain/block_state.cpp
- libraries/chain/hotstuff/hotstuff.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
If `pending_qc` does not have a valid QC, return valid_qc. Otherwise, extract the valid QC from `pending_qc`. Compare that to `valid_qc` to determine which is better: Strong beats Weak. Break tie with `valid_qc`.  Return the better one.
Resolved https://github.com/AntelopeIO/leap/issues/2075
> IF: Unification: Implement get_best_qc in block_state

- libraries/chain/controller.cpp
This is the remaining work for adding block header extension:  finding the most recent ancestor block that has a QC.
Resolved https://github.com/AntelopeIO/leap/issues/1911
> IF: Unification: Add block header extension (last part)

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/hotstuff/hotstuff.cpp
- libraries/chain/hotstuff/qc_chain.cpp
- libraries/chain/hotstuff/test/hotstuff_tools.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
- plugins/net_plugin/net_plugin.cpp
- unittests/block_state_tests.cpp
Process vote messages received from net plugin:
* aggregated the vote signature into the pending QC for the block the vote corresponds to
* added tests
Changing `proposal_id` to `block_id` in vote message and removing `proposal_digest` from pending_quorum_certificate will be done after unification as they should be part of the bigger cleaning up effort: https://github.com/AntelopeIO/leap/issues/2072
Resolved https://github.com/AntelopeIO/leap/issues/2046
Replaced https://github.com/AntelopeIO/leap/pull/2067
> IF:Unification: Process received Vote message

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
* Controller signs `finalizer_digest` of received block and emits a signal to net plugin
* Net plugin broadcasts the vote on receiving the signal
Note: 
* This PR only signs strong finalizer_digest.
* Calling of `create_and_send_vote_msg` will be in another final PR.
Resolved https://github.com/AntelopeIO/leap/issues/2069
> IF: Unification: Sign finalizer_digest of received block header and send out vote

- plugins/producer_plugin/producer_plugin.cpp
Make this check more robust to handle the esoteric config pattern in #2104
Tests needed?
> [5.0] more robust `chain_api_plugin` check in `producer_plugin`

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_helpers.hpp
- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/memfd_helpers.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp
Two small tweaks,
When `memfd_create()` was first used in EOSIO 2.0, RHEL7 was a targeted platform. Despite RHEL7's kernel shipping with memfd support, its glibc did not as it was too old. So instead, a direct `syscall()` was used. Now that we don't care about RHEL7 any longer we can just use `memfd_create()` proper; both Ubuntu 18.04 and RHEL8 have a new enough glibc that includes support.
As of Linux 6.3 the kernel starts to log a warning about nodeos,
```
nodeos[266224]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set
```
This warning has actually been walked back and completely removed as of Linux 6.7. Still, using the new `MFD_NOEXEC_SEAL` seems like good behavior for future proofing as environments may one day set the new `memfd_noexec` knob to enforce …
> minor cleanups to `memfd_create()`

- plugins/producer_plugin/producer_plugin.cpp
main merge of #2106 resolving #2104
> [5.0 -> main] more robust `chain_api_plugin` check in `producer_plugin`

- unittests/eosio.system_tests.cpp
- unittests/producer_schedule_if_tests.cpp
Fix comparison of different signedness warnings in `eosio.system_tests.cpp` and `producer_schedule_if_tests.cpp`
> IF: fix comparison of different signedness warnings in eosio.system_tests.cpp and producer_schedule_if_tests.cpp

- libraries/chain/authorization_manager.cpp
- libraries/chain/include/eosio/chain/authority_checker.hpp
- unittests/misc_tests.cpp
Periodically I've seen significant overhead handling exceptions in nodeos while it's live on EOS. It can even approach nearly 10% of main thread time in some of the worst cases. And these exceptions come about even when just applying blocks -- not processing speculative transactions.
What appears to be happening is contracts performing a `send_inline` causing the `authority_checker` to in some situations generate a fury of exceptions for missing `eosio.code` as it counts up weights.
This refactors the `authority_checker` to not lean on an exception to indicate a non-existing permission, a nullptr is returned indicating a non-existing permission instead.
> improve `authority_checker`'s performance: don't use exceptions as flow control for non-existing permissions

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
- unittests/block_state_tests.cpp
* Validate the claim in a block header extension for instant finality about the block number of the last block in its ancestry for which it has seen a QC. 
* Validate the claim as to whether this QC was strong or weak.
* Reject the block if the claims cannot be validated.
* Advance LIB if the QC is strong.
Resolved https://github.com/AntelopeIO/leap/issues/2071
> IF: Reject blocks with unsupported claims of last QC in block header extension

- plugins/net_plugin/net_plugin.cpp
If you are starting to sync with a node then you expect to be in `lib_catchup`. Need to switch to `lib_catchup` even if you are in `head_catchup`. Observed node not syncing when LIB was stuck in an integration test. The node would remain in `head_catchup` and never switch to `lib_catchup`. Since the `sync-fetch-span` was set to 5, it would keep syncing the same 5 blocks and never leave `head_catchup`.
Merges `release/5.0` into `main` including #2133
> [5.0 -> main] Also need to switch to lib_catchup if in head_catchup when starting to sync

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- libraries/chain/webassembly/privileged.cpp
* If the QC claim in the to-be-assembled block is the same (same block number and strong/weak status) as the QC claim in the previous block, then the QC should not be included in the block extension. `is_needed` was removed by https://github.com/AntelopeIO/leap/pull/2111 due to test failure. There was actually a bug in the original use of `is_needed`. It should have been used against parent block. This PR brings back `is_needed` and fixes the bug.
* If the sum of weights is less than threshold, the quorum will never be met. This PR asserts that the sum of the weights is greater than or equal to the threshold within the setfinalizers host function, 
Resolved https://github.com/AntelopeIO/leap/issues/2136
> IF: Bring back is_needed to avoid adding redundant QCs to blocks; enforce sensible finalizer policy in setfinalizers host function

- .github/workflows/build.yaml
- .github/workflows/build_base.yaml
Upgrade to `actions/upload-artifact@v4`. This has a couple nice benefits (as advertised by v4),
Upload performance is substantially better than v3, so much so that we can get rid of my `upload-artifact-large-chunks-action` and just rely on the canonical `upload-artifact` going forward.
More interestingly, artifacts are viewable and downloadable before the workflow completes. This has long been an annoyance to me so great to see this resolved. It's nice to, for example, grab the build or the leap-dev or some logs before the entire workflow has completed (i.e. before LR tests take.. a long time to complete). It'll also be hugely beneficial to usages of `asset-artifact-download-action` for similar reasons. For example, a workflow that's still in progress but has a leap-dev.deb completed can …
> upgrade to `actions/upload-artifact@v4`

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
This PR resolved additional comments by @heifner on https://github.com/AntelopeIO/leap/pull/2120. 
Thanks Kevin!
* moved `integrate_received_qc_to_block` to `push_block` so that it is thread safe, 
* searched the claimed QC block on the branch of `id` not head id, 
* and added block number to all error messages for easier identifying offending block.
Resolved #2071
> IF: Further work of validating QC claim 

- plugins/chain_plugin/chain_plugin.cpp
- plugins/http_plugin/http_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/trx_generator/trx_provider.cpp
Report `read-only transactions execution not enabled on API node. Set read-only-threads > 0` to caller when `/v1/chain/send_read_only_transaction` is not supported because of no configured `read-only-threads`. Note this is handled correctly in 4.0.x.
Includes some misc fixes found while debugging this issue.
- Log http errors before calling the callback `cb`, as `cb` may throw; e.g. `cb` not set.
- Add missing `}` in a `producer_plugin` error log, so the error is reported correctly.
- Add the response to the `trx_provider` error log when the `http` call fails.
> [5.0] Report read-only API not enabled to caller

- plugins/chain_plugin/chain_plugin.cpp
- plugins/http_plugin/http_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/trx_generator/trx_provider.cpp
Report `read-only transactions execution not enabled on API node. Set read-only-threads > 0` to caller when `/v1/chain/send_read_only_transaction` is not supported because of no configured `read-only-threads`. Note this is handled correctly in 4.0.x.
Includes some misc fixes found while debugging this issue.
- Log http errors before calling the callback `cb`, as `cb` may throw; e.g. `cb` not set.
- Add missing `}` in a `producer_plugin` error log, so the error is reported correctly.
- Add the response to the `trx_provider` error log when the `http` call fails.
Merges `release/5.0` into `main` including #2148
> [5.0 -> main] Report read-only API not enabled to caller

- plugins/producer_plugin/producer_plugin.cpp
#2106 caused failure on `hotstuff_integration` branch as `producer_plugin` was initialized before `chain_api_plugin`. Search `options` instead of querying of `appbase`. 
Merges `release/5.0` into `main` including #2152 
Resolves #2104
> [5.0 -> main] More robust `chain_api_plugin` check in `producer_plugin`; take 2

- libraries/testing/tester.cpp
- unittests/api_tests.cpp
Extend Boost test to show finality advances after transition to Instant Finality. This is achieved by configuring finalizer private keys on the Controller to allow a finalizer to vote on blocks.
Resolved https://github.com/AntelopeIO/leap/issues/2095
> IF: extend Boost test to show finality LIB advancing

- plugins/net_plugin/net_plugin.cpp
Reduce logging of `net_plugin` by reducing the what is logged for a `vote_message`.
Example output:
```
debug 2024-01-30T01:00:36.452 net-1     net_plugin.cpp:1191           operator()           ] ["localhost:9878 - 57d0855" - 3 127.0.0.1:60778] handle vote_message
debug 2024-01-30T01:00:36.452 net-1     net_plugin.cpp:3692           handle_message       ] ["localhost:9878 - 57d0855" - 3 127.0.0.1:60778] received vote: block #55:691415f356fb918e.., strong, key qXP11UuMRiJLRFGF..
debug 2024-01-30T01:00:36.452 net-2     net_plugin.cpp:1191           operator()           ] ["localhost:9878 - 57d0855" - 3 127.0.0.1:60778] handle vote_message
debug 2024-01-30T01:00:36.452 net-2     net_plugin.cpp:3692           handle_message       ] ["localhost:9878 - 57d0855" - 3 127.0.0.1:60778] received …
```
> IF: Reduce what is logged for a `vote_message`

- libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp
It has been relatively rare, but sometimes we've seen an unexplained `failed to compile wasm` error in EOS VM OC unittests. We've also seen at least [one report](https://t.me/antelopedevs/337899) from a user with a similar error. Up until now we've chalked this up to OC's subjective limits being inappropriately enabled during testing, as subjective limits could certainly explain this particular failure case where OC's sandbox fails to produce a response. These subjective limits are now disabled on `release/5.0` and `main` so we can no longer attribute failures to that.
After upgrading the CI image to the latest Linux kernel -- 6.7.1 at this time -- we've seen an explosion in the number of `failed to compile wasm` errors. I can also reproduce this issue locally with 6.7.x as well, as long …
> [5.0] always set OC's sandbox socket to blocking mode fixing random OC errors seen in CI & maybe elsewhere

- libraries/chain/snapshot_scheduler.cpp
Provide the full path of the snapshot file that can't be renamed if the rename fails. This provides useful information to the user so they can investigate r/w capabilities of the reported paths.
> [5.0] Report snapshot rename location on failure

- .github/workflows/build.yaml
- tests/CMakeLists.txt
- unittests/api_tests.cpp
- unittests/producer_schedule_if_tests.cpp
- set_finalizer_test
- verify_producer_schedule_after_instant_finality_activation
- nodeos_short_fork_take_over_if_test
- restart-scenarios-if-test-resync
- auto_bp_peering_if_test
- nodeos_high_transaction_if_lr_test
Note this requires commenting out all our instant-finality unittests.
#2175 will track adding them back.
> IF: Temporarily disable failing tests

- libraries/chain/snapshot_scheduler.cpp
Provide the full path of the snapshot file that can't be renamed if the rename fails. This provides useful information to the user so they can investigate r/w capabilities of the reported paths.
Merges `release/5.0` into `main` including #2177
> [5.0 -> main] Report snapshot rename location on failure

- libraries/chain/controller.cpp
Thanks @spoonincode for getting us the core backtrace and @heifner for suggesting the fix.
A reference of `control` caught by a lamda in `process_vote_message` lived past its destruction and caused the crash.
Resolved https://github.com/AntelopeIO/leap/issues/2184
> IF: Fix sigsegv in the use of process_vote_message

- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- plugins/chain_plugin/chain_plugin.cpp
- tests/CMakeLists.txt
- tests/nodeos_under_min_avail_ram.py
- tests/trx_finality_status_forked_test.py
Fix for deadlock caused by holding a fork database lock while posting tasks to chain thread pool which also tried to access fork database.
- log_irreversible
- Grabs fork database lock in `fork_db.apply`
- In the apply, posts a task to chain thread pool
- Waits on task via `future.get()`
- Meanwhile a vote comes in that posts a task to chain thread pool that tries to access the fork database
- If you use up all your thread pool threads trying to get a lock on fork database then you deadlock
There is a reason I am not a fan of recursive mutexes. https://github.com/AntelopeIO/leap/pull/2113#discussion_r1459796518
I should have listened to my own advice. Recursive mutexes are an indication that your design is wrong. In this case it provided a crutch that let us hit a deadlock in a much more …
> IF: Fix fork database deadlock

- unittests/producer_schedule_if_tests.cpp
As SIGSEGV was fixed by https://github.com/AntelopeIO/leap/pull/2185, re-enable `verify_producer_schedule_after_instant_finality_activation` Boost unit test (disabled by https://github.com/AntelopeIO/leap/pull/2176).
Resolved one of 6 tasks in https://github.com/AntelopeIO/leap/issues/2175
> IF: Reenable verify_producer_schedule_after_instant_finality_activation

- tests/CMakeLists.txt
- tests/ship_streamer_test.py
Enable:
- distributed-transactions-if-test
- restart-scenarios-if-test-resync
- nodeos_high_transaction_if_lr_test
These should pass after fixes: #2185 and #2182
> IF: Enable integration tests

- tests/TestHarness/Cluster.py
- tests/TestHarness/TestHelper.py
- tests/trace_plugin_test.py
Python does not call `atexit` on error. Revert back to calling `shutdown` explicitly from `TestHelper.shutdown`.
`trace_plugin_test.py` was the only test not already explicitly calling `TestHelper.shutdown`.
Resolves #2165
> Tests: Explicit shutdown since atexit not called on error

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
4xx response codes are for errors caused by the client where 5xx is for errors on the server side. The server exceeding its configured resource quota should be a 5xx error not a 4xx error. Change this from 429 to 503 (which is what it was in 2.0, fwiw). A 5xx error in this condition makes it easier for failover tooling, among other things. Resolves #2129
> [3.2] change HTTP code on exceeding `http-max-bytes-in-flight-mb` or `http-max-in-flight-requests` to 503

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
merge #2199 in to 4.0.
> 4xx response codes are for errors caused by the client where 5xx is for errors on the server side. The server exceeding its configured resource quota should be a 5xx error not a 4xx error. Change this from 429 to 503 (which is what it was in 2.0, fwiw). A 5xx error in this condition makes it easier for failover tooling, among other things. Resolves #2129
> [3.2 -> 4.0] change HTTP code on exceeding`http-max-bytes-in-flight-mb` or `http-max-in-flight-requests` to 503

- unittests/producer_schedule_if_tests.cpp
Add new tests for producer schedule using the new proposer policy.
Resolved https://github.com/AntelopeIO/leap/issues/2167
> IF: Update producer (proposer) schedule tests using the new IF proposer policy

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Merges #2199 & #2205 in to 5.0,
> 4xx response codes are for errors caused by the client where 5xx is for errors on the server side. The server exceeding its configured resource quota should be a 5xx error not a 4xx error. Change this from 429 to 503 (which is what it was in 2.0, fwiw). A 5xx error in this condition makes it easier for failover tooling, among other things. Resolves #2129
> [4.0 -> 5.0] change HTTP code on exceeding `http-max-bytes-in-flight-mb` or `http-max-in-flight-requests` to 503

- plugins/http_plugin/http_plugin.cpp
- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Merges #2199, #2205 & #2206 in to main
> 4xx response codes are for errors caused by the client where 5xx is for errors on the server side. The server exceeding its configured resource quota should be a 5xx error not a 4xx error. Change this from 429 to 503 (which is what it was in 2.0, fwiw). A 5xx error in this condition makes it easier for failover tooling, among other things. Resolves #2129
> [5.0 -> main] change HTTP code on exceeding `http-max-bytes-in-flight-mb` or `http-max-in-flight-requests` to 503

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
When `verify_max_requests_in_flight()` indicates we've exceeded max requests in flight, `send_busy_response()`, via `send_response()`, queues up an `async_write()` on the socket. But once this `async_write()` returns, `do_eof()` would be called which closes the socket while operations are pending. This causes bad things to happen.
Instead, set the `keep_alive(false)` on the response, which flags `needs_eof()` so that,
https://github.com/AntelopeIO/leap/blob/3394e0be5c59dc701b3fdd1e72130f50c9dd39e5/plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp#L478
will be set to `true`, which means the socket will be properly disposed of once the `async_write()` completes,
https://github.com/AntelopeIO/leap/blob/3394e0be5c59dc701b3fdd1e72130f50c9dd39e5/plugins/http_plugin/include/eos …
> [5.0] fix crash/UB when exceeding `http-max-requests-in-flight`

- plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
> [5.0 -> main] fix crash/UB when exceeding `http-max-requests-in-flight`

- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- unittests/api_tests.cpp
* Add a new set_finalizer which takes  threshold, weight and local finalizers as arguments
* Using the new function, add tests `threshold_equal_to_half_weight_sum_test`, `votes_equal_to_threshold_test`, `votes_greater_than_threshold_test`, and `votes_less_than_threshold_test`.
Resolved https://github.com/AntelopeIO/leap/issues/2193
> IF: Add a new set_finalizer (with weights, threshold, and local finalizer) to libtester and add more tests using it

- plugins/http_plugin/include/eosio/http_plugin/common.hpp
- plugins/http_plugin/tests/unit_tests.cpp
> [5.0 -> main] add tests for http's `max-*-in-flight` configs

- plugins/http_plugin/tests/CMakeLists.txt
- plugins/state_history_plugin/tests/CMakeLists.txt
- tests/trx_generator/CMakeLists.txt
Any test that listens on a localhost socket is required to be in NP tests currently. Resolves #2213
> [5.0] move some tests that open localhost sockets to NP tests

- plugins/net_plugin/net_plugin.cpp
- tests/CMakeLists.txt
- tests/bridge_for_fork_test_shape.json
- tests/lib_advance_test.py
Block producers drop blocks when producing. If a block producer is syncing when they start producing blocks, they will drop blocks causing unlinkable blocks on blocks processed after block production is complete. 
Reset sync on unlinkable blocks allowing node to more quickly recover.
Adds new `lib_advance_test.py` which fails without PR changes. 
Related #2159 & #2133
Resolves #2215
> P2P: Reset syncing on unlinkable blocks

- tests/CMakeLists.txt
- tests/trx_finality_status_forked_test.py
Update test to split finalizers across a bridge node to allow fork to be created.
Resolves #2189
> IF: Test: Simplify and fix trx_finality_status_forked_test.py

- libraries/chain/block_header_state.cpp
- tests/CMakeLists.txt
- tests/TestHarness/Cluster.py
- tests/TestHarness/Node.py
- tests/transition_to_if.py
- unittests/producer_schedule_if_tests.cpp
- Adds integration test that verifies transition to instant-finality works with multiple producers producing before transition
- Adds integration test for `setprods` after transition to instant-finality
- Fix issue found with `setprods` to activate new proposer policy at correct block (the first block of the producer)
Resolves #1512
> IF: Test: Transition to instant-finality with multiple producers

- plugins/http_plugin/tests/unit_tests.cpp
For unknown reasons, sometimes when `http_plugin_test_fixture` is destroyed `http_plugin`'s `listener`s are not destroyed despite `http_plugin` itself being destroyed. When this occurs the port that `listener` was listening on gets tied up for the remainder of `http_plugin_unit_tests` causing failures for the remaining test cases.
It's not clear to me why this is occurring. I suspect either some `static` somewhere or something I don't expect holding `listener`'s `shared_ptr`.
In the mean time just don't reuse the same port numbers among all the different test cases. It is rather curious that the `valid_category_addresses` test case already avoided 8888 that the prior `http_plugin_unit_tests` test case used.
> [5.0] improve reliability of `http_plugin_unit_tests` via port workaround

- plugins/http_plugin/tests/unit_tests.cpp
> [5.0 -> main] improve reliability of `http_plugin_unit_tests` via port workaround

- libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
Removed remaining unused definitions and methods: `view_number`, `quorum_certificate_message`, `hs_proposal_message`, `hs_message`, `hs_message_warning`.
> IF: Clean up hotstuff.hpp by removing remaining unused type definitions

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
- unittests/finality_test_cluster.cpp
- unittests/finality_test_cluster.hpp
- unittests/finality_tests.cpp
Prior to https://github.com/AntelopeIO/leap/pull/2135, weak votes and strong votes were signed using the same digest. The weak votes related tests in finality_tests.cpp were constructed based on the same digest; those tests had to be disabled to get #2135 to move ahead.
This PR fixes the issue. All disabled tests have been re-enabled.
Resolved https://github.com/AntelopeIO/leap/issues/2193
> IF: reenable weak vote related tests

- libraries/chain/block_header_state.cpp
- libraries/chain/block_header_state_legacy.cpp
- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_header_state.hpp
- libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
- libraries/chain/include/eosio/chain/block_header_state_utils.hpp
- libraries/chain/include/eosio/chain/block_state.hpp
- unittests/protocol_feature_tests.cpp
Sign `block_id` of proposed blocks and verify signatures on validation nodes.
- Also adds validation of activated protocol features.
- Includes a test that protocol feature activation works after instant_finality is enabled.
- Existing tests cover block signing validation. Many tests failed when I signed with the wrong producer key.
Resolves #2142
> IF: Sign and verify signature or proposed blocks

- plugins/trace_api_plugin/abi_data_handler.cpp
- plugins/trace_api_plugin/request_handler.cpp
- plugins/trace_api_plugin/test/test_data_handlers.cpp
- Use action result type ABI for action return value conversion by ABI.
- Only attempt conversion if an action return value ABI is available.
- Updated tests to verify action return value handling.
Resolves #2228
> [3.2] TraceAPI: Correctly convert return value via ABI

- plugins/trace_api_plugin/abi_data_handler.cpp
- plugins/trace_api_plugin/request_handler.cpp
- plugins/trace_api_plugin/test/test_data_handlers.cpp
- Use action result type ABI for action return value conversion by ABI.
- Only attempt conversion if an action return value ABI is available.
- Updated tests to verify action return value handling.
Note: No replay of data is needed. `trace_api_plugin` was storing the data correctly on disk.
Merges `release/3.0` into `release/4.0` including #2246 
Resolves #2228
> [3.2 -> 4.0] TraceAPI: Correctly convert return value via ABI

- plugins/trace_api_plugin/abi_data_handler.cpp
- plugins/trace_api_plugin/request_handler.cpp
- plugins/trace_api_plugin/test/test_data_handlers.cpp
- Use action result type ABI for action return value conversion by ABI.
- Only attempt conversion if an action return value ABI is available.
- Updated tests to verify action return value handling.
Note: No replay of data is needed. `trace_api_plugin` was storing the data correctly on disk.
Merges `release/5.0` into `main` including #2246 & #2247 & #2248
Resolves #2228
> [5.0 -> main] TraceAPI: Correctly convert return value via ABI

- libraries/chain/controller.cpp
See comment in code. There isn't really a problem with the existing code being there afaik, so I suppose this is just adding an indicator to remove this workaround completely once the LLVM requirement is strictly 9+
> don't do `set_new_handler()` workaround for LLVM 9+ where it's unnecessary

- libraries/chain/block_header_state.cpp
- libraries/chain/block_header_state_legacy.cpp
- libraries/chain/controller.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
- plugins/chain_plugin/chain_plugin.cpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/lib_advance_test.py
- Instead of dropping blocks when producing, incorporate blocks received while producing into the fork database.
- Potentially fork switch to newly incorporated blocks before producing a block
- Use block id instead of block number for irreversible so that correct fork branch is made irreversible
Resolves #2159
> IF: Don't drop late blocks

- libraries/chain/controller.cpp
- libraries/chain/hotstuff/finalizer.cpp
Vote on blocks that are not yet validated. The rule for now is:
1. Get the `core.final_on_strong_qc_block_num` for the block you are considering to vote on and use that to find the actual block ID of the ancestor block that has that block number.
2. If that block ID is not an ancestor of the current head block, then do not vote for that block.
3. Otherwise, consider voting for that block according to the `decide_vote` rules.
Resolves #2125
> IF: Vote before applying/validating block if possible

- .cicd/platforms/asserton.Dockerfile
- .github/workflows/build.yaml
- .github/workflows/build_base.yaml
- tests/CMakeLists.txt
A demo run with an `assert()` failure is at
https://github.com/AntelopeIO/leap/actions/runs/8150929931
> add a CI "platform" with `assert()`s enabled (`NDEBUG` not defined)

- libraries/chain/controller.cpp
- libraries/chain/fork_database.cpp
- libraries/chain/include/eosio/chain/fork_database.hpp
- unittests/finalizer_vote_tests.cpp
- unittests/fork_db_tests.cpp
Resolves #2283 .
Removes `fork_database::get_block_header` and simplifies `create_block_state_i`.
The only difference between `fork_database::get_block_header` and `fork_database::get_block` was that the former checked the `root`. It was also relying on the fact that `block_state` is `public block_header_state` to return the same pointer downcasted.
I have added an optional `check_root` parameter to `fork_database::get_block` instead.
This allowed to make `create_block_state_i` a template instead of having two separate implementations.
New disk format and compatibility mode will be addressed in #2285 .
> IF: Change Fork_db root to store block state

- tests/nodeos_startup_catchup.py
The `nodeos_startup_catchup_if_lr_test` test has 15 connections. A node can receive a current block from all the connections at the same time and get an `unlinkable` block for each one because it is syncing at the time. Allow for an `unlinkable` from each of the connections while syncing. 
Resolves #2266
> IF: Test: nodeos_startup_catchup_if_lr_test relax constraint

- libraries/chain/snapshot.cpp
`./nodeos --data-dir dd --config-dir mainconfig --snapshot snapshot-2024-02-08-04-eos-v6-0356339018.bin.zst`
Before:
```
warn  2024-03-08T13:37:03.489 nodeos    chain_plugin.cpp:1102         plugin_initialize    ] 3240000 snapshot_exception: Snapshot exception
Binary snapshot validation threw IO exception (Snapshot exception)
{"what":"Snapshot exception"}
nodeos  snapshot.cpp:261 validate
appbase: exception thrown during plugin "" initialization.
Snapshot exception
```
With this PR:
```
warn  2024-03-08T13:39:02.560 nodeos    snapshot.cpp:260              validate             ] 3240000 snapshot_exception: Snapshot exception
Binary snapshot has unexpected magic number!
{}
nodeos  snapshot.cpp:249 validate
warn  2024-03-08T13:39:02.561 nodeos    chain_plugin.cpp:1102 …
```
> [5.0] Better error reporting on snapshot load exceptions

- libraries/chain/snapshot.cpp
`./nodeos --data-dir dd --config-dir mainconfig --snapshot snapshot-2024-02-08-04-eos-v6-0356339018.bin.zst`
Before:
```
warn  2024-03-08T13:37:03.489 nodeos    chain_plugin.cpp:1102         plugin_initialize    ] 3240000 snapshot_exception: Snapshot exception
Binary snapshot validation threw IO exception (Snapshot exception)
{"what":"Snapshot exception"}
nodeos  snapshot.cpp:261 validate
appbase: exception thrown during plugin "" initialization.
Snapshot exception
```
With this PR:
```
warn  2024-03-08T13:39:02.560 nodeos    snapshot.cpp:260              validate             ] 3240000 snapshot_exception: Snapshot exception
Binary snapshot has unexpected magic number!
{}
nodeos  snapshot.cpp:249 validate
warn  2024-03-08T13:39:02.561 nodeos    chain_plugin.cpp:1102 …
```
> [5.0 -> main] Better error reporting on snapshot load exceptions

- libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/config.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp
- unittests/eosvmoc_limits_tests.cpp
Brings in,
AntelopeIO/abieos#25
AntelopeIO/appbase#31
AntelopeIO/bn256#20
AntelopeIO/eos-vm#22
along with some other noted changes below.
> grab bag of small UB fixes

- plugins/net_plugin/net_plugin.cpp
`net_plugin_impl` currently destroys its `named_thread_pool` before a number of users of it such as `expire_timer`. Those users can, and do, access their executor on their destruction which in this case is accessing an already destroyed executor.
Move the `named_thread_pool` up to the top so it's destroyed last. A nice side effect of this is being able to clean up a number of the `unique_ptr`s to just being a plain member.
> fix `net_plugin_impl` destruction order: destroy thread_pool's executor after users of it

- libraries/chain/include/eosio/chain/chainbase_environment.hpp
- plugins/chain_plugin/chain_plugin.cpp
- programs/leap-util/actions/chain.cpp
See comment. We should change CB's header to not have this problem next time there is work in area.
> custom `chainbase::environment` `to_variant()` to workaround invalid unaligned access

- tests/gelf_test.py
`gelf_test.py` listens on 127.0.0.1,
https://github.com/AntelopeIO/leap/blob/aef4329efa9a860b7b46b690876ded088189684e/tests/gelf_test.py#L71-L74
but then configured its `logging.json` to use `localhost`. In 5.0, gelf will use IPv6 and on by box `localhost` will resolve to `::1` thus this test would fail locally for me since the gelf messages wouldn't arrive on the expected address.
Explicitly configure `127.0.0.1` in logging.json so it's always IPv4->IPv4
> [5.0] fix IPv4 vs IPv6 mismatch in `gelf_test`

- .cicd/platforms/ubsan.Dockerfile
- .github/workflows/build.yaml
While there are still a few remaining violations (see comments below), I think we're in a good spot to enable UBSAN in CI builds. UBSAN is expected to generate no false positives so requiring it to pass is reasonable.
An example run with failures is here,
https://github.com/AntelopeIO/leap/actions/runs/8252261490
> add CI "platform" running UBSAN

- tests/gelf_test.py
main merge of #2288
> `gelf_test.py` listens on 127.0.0.1,
> https://github.com/AntelopeIO/leap/blob/aef4329efa9a860b7b46b690876ded088189684e/tests/gelf_test.py#L71-L74
> 
> but then configured its `logging.json` to use `localhost`. In 5.0, gelf will use IPv6 and on by box `localhost` will resolve to `::1` thus this test would fail locally for me since the gelf messages wouldn't arrive on the expected address.
> 
> Explicitly configure `127.0.0.1` in logging.json so it's always IPv4->IPv4
> [5.0 -> main] fix IPv4 vs IPv6 mismatch in `gelf_test`

- libraries/chain/include/eosio/chain/incremental_merkle.hpp
In PR #2314, I asked why we were using overly complex code to do what was basically a log base 2.
Gnome mentioned that the original code was in `incremental_merkle_tree.hpp`.
So I propose this simplification. The replacement provides exactly the same result as the previous implementation, as the following test program demonstrates:
```c++
#include <cmath>
#include <cstdlib>
static uint64_t next_power_of_2(uint64_t value) {
value -= 1;
value |= value >> 1;
value |= value >> 2;
value |= value >> 4;
value |= value >> 8;
value |= value >> 16;
value |= value >> 32;
value += 1;   return value;
}
constexpr uint64_t clz_power_2(uint64_t value) {
int lz = 64;
if (value) lz--;
if (value & 0x00000000FFFFFFFFULL) lz -= 32;
if (value & 0x0000FFFF0000FFFFULL) lz -= 16;
if (value & …
```
> Replace hacky version of `calculate_max_depth` with simpler one.

- tests/p2p_sync_throttle_test.py
See https://github.com/AntelopeIO/leap/actions/runs/8347816731/job/22848869684
Failed because it didn't wait on an error and quickly exhausted error limit.
```
debug 2024-03-19T18:09:31.199 http-1    beast_http_session.hpp:480    send_response        ] Response: localhost:8891 HTTP/1.1 200 OK  Connection: close  Server: nodeos/v5.1.0-dev  Content-Type: text/plain  Content-Length: 7638    # HELP nodeos_http_requests_total number of HTTP requests # TYPE nodeos_http_requests_total counter nodeos_http_requests_total{handler="/v1/prometheus/metrics"} 5 # HELP nodeos_p2p_failed_connections total number of failed out-going p2p connections # TYPE nodeos_p2p_failed_connections counter nodeos_p2p_failed_connections 2 # HELP nodeos_p2p_dropped_trxs_total total number of dropped transactions by net …
```
> IF: Test fix: Delay on error to give time for node to launch

- libraries/chain/transaction_context.cpp
The `vector::reserve(vector::size() + 1)` call which is updated in this PR, with typical `std::vector` implementations, causes the vector to grow by a single element on every reverve, and therefore a memory allocation and full vector copy on every `reserve` call.
This updates the `reserve()` call so that the vector capacity grows quadrically.
> Perf issue: avoid vector copy at each insertion.

- plugins/producer_api_plugin/producer_api_plugin.cpp
`http_max_response_time` is a variable declared on that stack as part of `plugin_startup()`
https://github.com/AntelopeIO/leap/blob/c301152420c381a08aadf1f4d1f2b59414110418/plugins/producer_api_plugin/producer_api_plugin.cpp#L94
`CALL_WITH_400` captures all by reference
https://github.com/AntelopeIO/leap/blob/c301152420c381a08aadf1f4d1f2b59414110418/plugins/producer_api_plugin/producer_api_plugin.cpp#L23-L26
`INVOKE_R_R_D` then goes on to use the reference to `http_max_response_time` which is stale as `plugin_startup()` has long since returned once HTTP requests are made
https://github.com/AntelopeIO/leap/blob/c301152420c381a08aadf1f4d1f2b59414110418/plugins/producer_api_plugin/producer_api_plugin.cpp#L65-L66
This problem seemed to have been introduced in 5.0. Since this is in …
> [5.0] avoid using a stack variable after return

- plugins/producer_api_plugin/producer_api_plugin.cpp
Workaround unused compiler warning. Note `[[maybe_unused]]` does not work for lambda captures.
> Avoid unused warning

- tests/trx_finality_status_forked_test.py
Does not fix issue reported in #2310. This PR is to make reporting of errors better.
Use `getBlockNum()` and `getBlockID()` for accessing `get transaction-status` results. 
`IN_BLOCK` status returns `block_number` and `block_id`.
`LOCALLY_APPLIED` status returns `head_number` and `head_id`.
```
cmd={/__w/leap/leap/build/bin/cleos --url http://localhost:8891 --wallet-url http://localhost:9899 --no-auto-keosd get transaction-status fb2a71ec0e490bf8989f1cfaa9f6a16c0367ec8078f8492477026ff7c5029be4}
cout={b'{\n  "state": "IN_BLOCK",\n  "block_number": 199,\n  "block_id": "000000c7bfc26343def2c691bd7fed57880c320a9cef930fa8f16ffbb86e23c1",\n  "block_timestamp": "2024-03-27T17:12:45.000",\n  "expiration": "2024-03-27T17:14:12.000",\n  "head_number": 200,\n  "head_id": …
```
> IF: Test: trx_finality_status_forked_test

- libraries/chain/controller.cpp
- unittests/producer_schedule_if_tests.cpp
When `set_proposed_producers` replaces an existing in-flight producer schedule, use the existing in-flight producer schedule version so that versions are not skipped.
Resolves #2313
> IF: Set correct proposed producer schedule version

- .cicd/platforms/asan.Dockerfile
- .github/workflows/build.yaml
Adds a new "platform" that builds & tests the software with ASAN.
It's possible to enable a single build with UBSAN+ASAN simultaneously, but this further increases both the compile time and run time overhead. So do UBSAN & ASAN separately for now.
And speaking of ASAN build overhead, I was unable to get NP or LR tests to complete in CI without either running out of memory or having some sort of timing problem. I even tried increasing the resources for the run but that still wasn't enough. I think it's likely worthwhile to go ahead with what we've got though as at least we'll still get unit test coverage, and reevaluate whatever the performance problem is later (I was able to complete them successfully locally).
Example run of ASAN failures: …
> add ASAN CI "platform"

- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/state_history/abi.cpp
- libraries/state_history/include/eosio/state_history/serialization.hpp
- libraries/state_history/include/eosio/state_history/types.hpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
- plugins/state_history_plugin/tests/session_test.cpp
- tests/nodeos_forked_chain_test.py
- tests/ship_streamer.cpp
- tests/ship_streamer_test.py
https://github.com/AntelopeIO/leap/pull/2321 added SHiP support for IBC. A new `get_blocks_request_v1` was introduced to include a field `fetch_finality_data`, but existing `get_blocks_result_v0` was reused to return the result of `get_blocks_request_v1`. That can cause confusions to the users, and a client's ABI `bin_to_json()` would add an extra `"finality_data": null` to the JSON output in Legacy (as `finality_data` does not exist).
This PR adds `get_blocks_result_v1` which stores the result of `get_blocks_request_v1`; `get_blocks_result_v0` is restored to its original use: only storing the result of `get_blocks_result_v0`.
`get_blocks_request_v1` adds extra `get_blocks_request_v1` to `get_blocks_request_v0`; `get_blocks_result_v1` adds extra `finality_data` to `get_blocks_result_v0`. …
> IF: add get_blocks_result_v1 support to SHiP

- plugins/net_plugin/net_plugin.cpp
Add additional debug logging around async write.
Make all logs that contain a connection id use a prefix of `- ` so they are easy to grep for in the log.
```
debug 2024-03-28T20:58:09.489 net-2     net_plugin.cpp:2654           operator()           ] socket_is_open true, state connected, syncing false, connection - 4
```
The `- ` matches default output of `peer_*` logging:
```
debug 2024-03-28T20:58:09.489 net-0     net_plugin.cpp:2668           operator()           ] ["localhost:9876 - b648e56" - 4 127.0.0.1:9876] bcast block 7
```
Should help verify issue of #2354 and #2351.
> IF: net: Add extra logging around async write

- libraries/chain/block_state.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
We can set active finalizer policy generation in finality_data without waiting for the completion of finalizer policy change feature.
Resolved https://github.com/AntelopeIO/leap/issues/2352
> IF: set active finalizer policy generation in finality_data for SHiP correctly

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/hotstuff/hotstuff.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
Since bls signature verification can take 6-8ms on ci/cd machines (~2ms on i7 or i9 12th gen), perform the verify while not holding a mutex. This reduces the contention on the `pending_quorum_certificate` mutex.
I believe we still need to do the verify off the `net` thread, but this is a simple improvement we can get in now.
This PR severely aggravated #2289, so added a fix for that issue.
Resolves #2289
> IF: Verify bls signature of vote while not holding a mutex

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
> IF: Calculate IF Genesis Block finality digest correctly

- tests/nodeos_retry_transaction_test.py
The test would wait on the last trx in a set before continuing. However, there is no guarantee that a previous trx is not retried because it didn't fit into a block. The test now verifies the complete set of trx are complete before continuing to the next step.
Resolves #2364
> IF: Test: Verify needed trx processed before continuing

- libraries/testing/include/eosio/testing/tester.hpp
- libraries/testing/tester.cpp
Currently libtester provides a method get_row_by_account() to return a table row by account name.
This PR adds another convenient method to return a row by id. This is to be used by https://github.com/AntelopeIO/reference-contracts/pull/60.
Resolved https://github.com/AntelopeIO/leap/issues/2367.
> IF: Add get_row_by_id to libtester

- unittests/CMakeLists.txt
- unittests/eosio.system_tests.cpp
The OC run of `eosio_system_tests` has become the longest running parallelizable test; to the point that sometimes it bumps up against the maximum test run time. How about split it up in two parts so that it runs in parallel faster. Work on #2369
> split `eosio.system_tests` in two parts to decrease run time

- libraries/state_history/abi.cpp
- libraries/state_history/include/eosio/state_history/types.hpp
The order of message types in the `state_request` variant is part of the binary protocol. I suggest we add the new `get_blocks_request_v1` to the end. Otherwise, unmodified ship clients that both use `get_blocks_ack_request_v0` and do not consume the ABI from the websocket endpoint (I believe abieos or eos-go based readers) will misbehave.
> IF: switch variant index of new `get_blocks_request_v1`

- plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp
It has been reported a few times, for example: https://github.com/EOSIO/eos/issues/10690 that the `trace_api_plugin` performance suffers greatly from the `sync()` call in storing to disk. This has recently caused slow down in ci/cd as well causing tests to fail do to taking so long to write to the trace api log.
We do not `sync()` for the block log or SHiP logs. Seems the trade off of performance for small possibility of corrupted trace api logs is worth it.
Resolves #2331
> TraceAPI: Remove sync() to improve performance

- libraries/chain/block_header_state_legacy.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/controller.hpp
- libraries/chain/webassembly/privileged.cpp
Resolves #2345 
The `finalizer_policy` struct in contracts does not have a `generation` member.
In this PR, when the `set_finalizers` host function is executed, we increment the generation number of the `finalizer_policy` to the the active policy generation number plus one.
> Increment `finalizer_policy`'s `generation` when `set_finalizers` is executed.

- .github/workflows/submod.yaml
This allows for the submodule regression check to run in more environments.
> use github provided token for git in submodule regression check

- plugins/chain_plugin/chain_plugin.cpp
`/v1/chain/compute_transaction` API endpoint should return a failure trace. 
This was accidently changed to false when refactoring send_transaction in 5.0.
See 4.0 impl: https://github.com/AntelopeIO/leap/blob/01dab51ac00aed6730700b82943c30ccfd854fce/plugins/chain_plugin/chain_plugin.cpp#L2562-L2562
Resolves #2281
> [5.0] compute_transaction should return failure trace

- plugins/net_plugin/net_plugin.cpp
In 5.0, P2P added new protocol version to include start/end range in `notice_message`. See https://github.com/AntelopeIO/leap/pull/1215
When that was added, `sync_recv_notice` was not updated to use the correct id for `verify_catchup`. This causes additional handshakes and syncing to resolve syncing up to head. 
This caused `disaster_recovery_2` in [spring](https://github.com/AntelopeIO/spring) to not reach syned up state in time for the test to not fail.
Backport of https://github.com/AntelopeIO/spring/pull/484
Resolves https://github.com/AntelopeIO/spring/issues/390
> [5.0] P2P: Fix handling of known pending block

- libraries/chain/snapshot_scheduler.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/test_snapshot_scheduler.cpp
leap 5's snapshot scheduling implementation changed the meaning of  `end_block_num=0` which breaks both requests that previously worked and any previously scheduled snapshots with that value (the scheduled snapshots will effectively be removed upon upgrade to leap5).
In leap4 requests were submitted as
https://github.com/AntelopeIO/leap/blob/01dab51ac00aed6730700b82943c30ccfd854fce/plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp#L85-L89
This has the important behavior that if a request does not specify `end_block_num` it remains 0 _and is written out to `snapshot-schedule.json` with `"end_block_num":0`._ I believe what happens then is that `end_block_num=0` gets treated as "forever" by it not being removed from the scheduled list here, …
> [5.0] treat a `end_block_num=0` as "forever" in snapshot scheduler for compatibility with leap 4.0 behavior

- libraries/chain/include/eosio/chain/contract_table_objects.hpp
Default parameters for the lower bound of a `uint128[2]` ("`checksum256`") index used for the `get_table` RPC call were uninitialized and might cause unexpected results to be returned. Initialize this to zero.
> [5.0] fix `true_lowest()` for `uint128[2]` index; possibly resolving some secondary table row RPC queries

- libraries/chain/abi_serializer.cpp
Resolves [#2330](https://github.com/AntelopeIO/leap/issues/2330).
The deserialization of arrays involves reading a size, and then the array elements which are `emplace`'d back into a `std::vector`. For normal vectors, since we know the size in advance, it is beneficial to call `std::vector::reserve()` to prevent quadratic reallocations of the vector's buffer as the values are read. Still, limit the size that can be reserved to `1024` `fc::variant` values, or 16KB since `sizeof(fc::variant) == 16`).
> [5.0] Fix issue #2330 by limiting the vector size that can be reserve'd

- plugins/net_plugin/net_plugin.cpp
Resolve address on reconnect.
See https://github.com/AntelopeIO/spring/issues/525
Instead of:
````
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:2797           operator()           ] connection failed to p2p.telos-bad.zenblocks.io:9876, Element not found
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:1461           _close               ] ["p2p.telos-bad.zenblocks.io:9876" - 1 <unknown>:<unknown>] closing
````
Now you get:
```
warn  2024-09-25T21:42:48.642 net-0     net_plugin.cpp:4524           operator()           ] Unable to resolve p2p.telos-bad.zenblocks.io:9876 Host not found (authoritative)
```
> [5.0.3] P2P: Resolve on reconnect

- plugins/net_plugin/net_plugin.cpp
Reverts AntelopeIO/leap#2408
Causing SEGFAULTs in CI/CD runs of the `p2p_sync_throttle_test`.
> Revert "[5.0.3] P2P: Resolve on reconnect"

- libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp
For some background and history see https://github.com/AntelopeIO/leap/issues/1216#issuecomment-1570826884, I'm not going to repeat that research here. But the TLDR of it is that since some CPUs ignore setting the GS register to 0x00, expecting the register to be 0x00 (and printing this warning otherwise) seems dubious: it sounds as if the kernel does not and can not guarantee that upon the start of a new process GS is 0x00.
Now that said, I can't reproduce any cases where GS is not cleared to 0x00 on the start of a new process. I even dug out a Zen 1 CPU, confirmed `/proc/cpuinfo` shows the `null_seg` bug, and still GS is reset to 0x00 on a new process after the parent process sets it to some value. Not sure what nuance I am misunderstanding about this 'bug', maybe some x86 guru can …
> [5.0] remove EOS VM OC's erroneous `GS register is not as expected` message
