.github/workflows/build.yaml

merge to main of #56 which creates a single job we can tie branch protection rules

[3.1 -> main] add a final job that passes if all tests pass making it easier to branch protect on checks

---

tests/trx_generator/CMakeLists.txt
tests/trx_generator/main.cpp
tests/trx_generator/trx_generator.cpp
tests/trx_generator/trx_generator.hpp
tests/trx_generator/trx_generator_tests.cpp
tests/trx_generator/trx_provider.hpp

Took most of the code from trx_generator main.cpp and moved into a separate generator struct for creating transfer transactions for performance testing.

Refactored the trx_generator main code

---

scripts/0001-beast-fix-moved-from-executor.patch
scripts/pinned_build.sh

3.1 merge of #85 that resolves a websocket defect in boost 1.70.

[3.1 -> main] patch pinned build's boost 1.70 to fix websocket defect

---

CMakeLists.txt
programs/cleos/LICENSE.CLI11

This looks like a license that needs to be bundled with binaries.

[3.1] add CLI11 license to install

---

CMakeLists.txt
programs/cleos/LICENSE.CLI11

[3.1 -> main] add CLI11 license to install 

---

tests/performance_tests/log_reader.py
tests/performance_tests/performance_test_basic.py
tests/performance_tests/read_log_data.py

TPS scoring herein includes min, max, average, and standard deviation using measurements of pairs of consecutive blocks over a defined window of blocks during a testing run.

Add TPS scoring

---

scripts/pinned_build.sh

[3.1] always overwrite old downloads in pinned build script

---

scripts/pinned_build.sh

main merge of #155; resolves #131

[3.1 -> main] always overwrite old downloads in pinned build script

---

tests/performance_tests/log_reader.py

Added calculation and reporting for transaction CPU and Net usage statistics:
```
Report:
{
"Analysis": {
"BlockSize": {
"avg": 765308.6315789474,
"emptyBlocks": 0,
"max": 921600,
"min": 614400,
"numBlocks": 57,
"sigma": 61977.370963934154
},
"BlocksGuide": {
"configAddlDropCnt": 2,
"firstBlockNum": 2,
"lastBlockNum": 244,
"leadingEmptyBlocksCnt": 1,
"setupBlocksCnt": 127,
"tearDownBlocksCnt": 22,
"testAnalysisBlockCnt": 57,
"testEndBlockNum": 222,
"testStartBlockNum": 129,
"totalBlocks": 243,
"trailingEmptyBlocksCnt": 32
},
"TPS": {
"avg": 7985.732142857143,
"configTestDuration": 30,
"configTps": 8000,
"emptyBlocks": 0,
"max": 8800,
"min": 7200,
"numBlocks": 57,
"sigma": 325.63588841523534
},
"TrxCPU": {
"avg": 36.26989583333334,
"max": 1081.0,
"min": 23.0,
"samples": 240000,
"sigma": …
```

[PH] Add support for calculating and reporting individual transaction CPU and net time

---

tests/trx_finality_status_forked_test.py

Cleanup and provide more time before fork resolution.
Resolves #274

[3.1] Test fix: trx_finality_status_forked_test.py 

---

tests/trx_finality_status_forked_test.py

Cleanup and provide more time before fork resolution.
Resolves #274 
Merges #307 into `release/3.2`

[3.1 -> 3.2] Test fix: trx_finality_status_forked_test.py

---

tests/trx_finality_status_forked_test.py

Cleanup and provide more time before fork resolution.
Resolves #274 
Merges #307 & #308 into `main`

[3.2 -> main] Test fix: trx_finality_status_forked_test.py

---

plugins/test_control_plugin/test_control_plugin.cpp

Fixed corner case around `test_control_plugin` missing a slot production. Simplified the implementation of `test_control_plugin` by using slot directly instead of counting produced blocks.
Resolves #251

[3.1] Test fix: nodeos_forked_chain_lr_test

---

tests/performance_tests/log_reader.py

Adds a couple of parameters and does a little math to present information to performance harness output.

[PH] Add some additional parameters to performance harness output

---

tests/TestHarness/Node.py

Adds a function that will wait for a list of transactions to appear in a block. Checks incoming blocks for transactions and removes them from the list. Returns upon timeout or when list has all been seen.

[PH] Add method to wait and check blocks for transactions

---

programs/leap-util/actions/blocklog.cpp
programs/leap-util/actions/blocklog.hpp

This is to merge changes related to https://github.com/AntelopeIO/leap/pull/327 into main

[3.2 -> main] Leap util blocklog updates

---

tests/performance_tests/README.md
tests/performance_tests/log_reader.py
tests/performance_tests/performance_test.py
tests/performance_tests/performance_test_basic.py
tests/performance_tests/read_log_data.py

Provide option in both Performance Harness and basic test.
`--quiet True` - will quiet intermediate results and reports being written to stdout stream during test scenarios.
Update docs to reflect argument addition

[PH] Add option to quiet reporting from performance tests.

---

tests/performance_tests/README.md
tests/performance_tests/performance_test.py
tests/performance_tests/performance_test_basic.py

1. Update default test durations to something higher for more reasonable block count to analyze.
2. Include testAnalysisBlockCnt in search scenario summary.
3. Update documentation.

[PH] Perf Harness test updates

---

plugins/prometheus_plugin/CMakeLists.txt
plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
plugins/prometheus_plugin/prometheus_plugin.cpp

Added the ability to do handle Prometheus pull requests.  Added metrics for the prometheus_plugin.

Add pull functionality

---

tests/TestHarness/launcher.py

Write a genesis file for each node.

---

tests/performance_tests/log_reader.py
tests/performance_tests/performance_test_basic.py
tests/performance_tests/read_log_data.py

Consolidate some of the arguments to `log_reader.py`'s `calcAndReport`
Factor related arguments out into classes to cut down on how verbose the method signature is.

[PH] Consolidate some of the arguments to log_reader.py's calcAndReport

---

tests/performance_tests/README.md

Collapse example directory structure.

[PH] README updates

---

plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
plugins/net_plugin/net_plugin.cpp
plugins/prometheus_plugin/prometheus_plugin.cpp

Various updates to the interface to the prometheus_plugin based on feedback

Updates to runtime_metrics / interface between instrumented plugins and prometheus plugin

---

tests/CMakeLists.txt

Remove --dump-error-details from all tests in tests/CMakeLists.txt

---

tests/trx_generator/trx_generator.cpp

Removes a pair of throw chains from transaction generator that were doing nothing besides throwing.

[PH] Performance harness remove unnecessary throw chains

---

tests/trx_generator/trx_generator.cpp
tests/trx_generator/trx_generator_tests.cpp

Fix for some trx_generator warnings.

Fix trx_generator warnings

---

tests/TestHarness/Cluster.py
tests/launcher.py
tests/nodeos_run_test.py

Modify nodeos_run_test to exercise nodeos path specification.

Add support for specifying paths to nodeos in launcher.

---

plugins/net_plugin/net_plugin.cpp

Remove the +1 to the block latency calculation otherwise even 0ms latency indicates 1 block latency instead of 0. The +1 makes the comparisons of `head` and `msg.head` in the `if-else` off by 1 when there is no latency. 
Added additional logging so that issues like #588 are easier to debug.
Before:
```
debug 2022-12-21T21:54:29.938 net-3     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 43 127.0.0.1:52370] Network latency is 0ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
```
After:
```
debug 2023-01-31T00:27:27.386 net-0     net_plugin.cpp:1795           recv_handshake       ] ["localhost:9878 - 978ab39" - 1 127.0.0.1:54362] Network latency is 0ms, 0 blocks discrepancy by network latency, 0 blocks …
```

[3.2 -> main] net_plugin improve block latency calculation

---

plugins/producer_plugin/producer_plugin.cpp
tests/trx_generator/trx_generator.hpp
unittests/misc_tests.cpp

The latest appbase version allows to customize the appbase execution engine by providing an `executor` class.
Besides updating the appbase submodule tip, this PR has a couple small changes to support the new architecture.

Update leap to use new appbase version.

---

tutorials/bios-boot-tutorial/bios-boot-tutorial.py

New protocol features: GET_CODE_HASH, CRYPTO_PRIMITIVES, GET_BLOCK_NUM were added.

Backport to 3.1 of bootstrap new protocol features activation

---

tutorials/bios-boot-tutorial/bios-boot-tutorial.py

New protocol features: GET_CODE_HASH, CRYPTO_PRIMITIVES, GET_BLOCK_NUM were added.

Backport to 3.2 of bootstrap new protocol features activation

---

tutorials/bios-boot-tutorial/bios-boot-tutorial.py

New protocol features: GET_CODE_HASH, CRYPTO_PRIMITIVES, GET_BLOCK_NUM were added.

[3.2 -> main] New protocol features activation was added to the bootstrap process

---

tests/performance_tests/log_reader.py
tests/performance_tests/performance_test.py
tests/performance_tests/performance_test_basic.py

Some previous changes broke nodeos 2.0 compability, this PR fixes those.

[PH] Repair Nodeos 2.0 Compatibility with Performance Tests

---

plugins/state_history_plugin/tests/session_test.cpp

Add a test that verifies restart from genesis not allowed.
See #764

Test: Add a test that verifies restart from genesis not allowed

---

tests/http_plugin_test.py

Relates to https://github.com/AntelopeIO/leap/issues/643 and https://github.com/AntelopeIO/leap/pull/745

Cleanup some missed https support from test that was missed.

---

plugins/producer_plugin/producer_plugin.cpp

This PR merges PR #777 into release/3.2 branch with the following changes
- adds a new configuration option --subjective-account-max-failures-window-size to set the window size in number of blocks for --subjective-account-max-failures option.
- extract the block tracking functionality from `account_failures` class into a `block_time_tracker` class.
Resolves #760

[3.1 -> 3.2] subjective-account-max-failures-window-size

---

plugins/prometheus_plugin/prometheus_plugin.cpp

The PR fixes a bug where it reuses a moved value

fix create_metrics_listener

---

tests/plugin_http_api_test.py

The PR adds an integration test for prometheus plugin

prometheus plugin integeration test

---

tests/nodeos_snapshot_diff_test.py

This PR mitigates rare and annoying issue of the test failing when there is a new block happening in between of scheduling and "now" create_snapshot calls. The fix is to execute create_snapshot first and schedule programmable snapshot at exact same block num. Same as with irreversible one.

[4.0] Increase robustness of snapshot diff python test

---

plugins/producer_plugin/producer_plugin.cpp

Read window and write window run exclusively with each other; they do not run at the same time. A single timer is sufficient to control them and makes code simpler.

[4.0] Use a single timer for read and write windows

---

plugins/producer_plugin/producer_plugin.cpp

Merge https://github.com/AntelopeIO/leap/pull/933 into main.
- update eos-vm-oc threads limit calculation based on the design
- use faster boost deque instead of std:deque

[4.0 -> main] Small improvements for parallelizing read-only transactions and tasks

---

plugins/producer_plugin/test/test_snapshot_scheduler.cpp

This PR improves test stability, in particular tolerance to ordering of snapshot requests in multiindex container.

[4.0] Improved test_snapshot_scheduler stability

---

libraries/custom_appbase/include/eosio/chain/application.hpp

For short running tasks, e.g. token transfer transaction, it is faster to remain in the executor before returning to the `appbase` `exec()` loop. There is a trade-off here on how long to potentially delay a high priority task from executing. This PR uses 3ms. 5ms or even 10ms would be better, but this PR goes with the more conservative delay. Opinions on the delay amount welcome.

Small but measurable improvement to executor queue

---

plugins/chain_api_plugin/chain.swagger.yaml

Update swagger files to include missing doc: 
- get_transaction_status, 
- compute_trasaction, 
- send_transaction2

[4.0] Update swagger files to include missing doc

---

libraries/chain/block_log.cpp
libraries/chain/include/eosio/chain/block_log.hpp
libraries/chain/include/eosio/chain/log_index.hpp
libraries/testing/tester.cpp
plugins/chain_plugin/chain_plugin.cpp
programs/leap-util/actions/blocklog.cpp
tests/CMakeLists.txt
tests/split_blocklog_replay_test.py
unittests/block_log_extract.cpp
unittests/partitioned_block_log_tests.cpp

This PR fixes block replay problem with partitioned block log
Merge PR #1164 into main
Resolves https://github.com/AntelopeIO/leap/issues/1136

[4.0->main] fix replay for partitioned block log

---

.github/workflows/pinned_build.yaml
scripts/pinned_build.sh

Pinned builds run in GitHub Actions
Resolves: https://github.com/AntelopeIO/leap/issues/735

[3.1] Pinned Builds manual dispatch workflow in CI

---

plugins/producer_plugin/producer_plugin.cpp

Report transaction failed if trx was exhausted in non-producing mode, so we restart a speculative block to retry it immediately, instead of waiting to receive a new block.

[4.0 -> main] Report transaction failed if trx was exhausted in non-producing mode (GH 1247) 

---

.cicd/defaults.json
.github/workflows/build.yaml

Resolves: [1104](https://github.com/AntelopeIO/leap/issues/1104)

test libtester usage as part of CI

---

tests/plugin_http_api_test.py

`plugin_http_api_test.py` add `--keep-logs` option and do not clean logs on test failures.
Resolves #1176

Test: plugin_http_api_test.py

---

plugins/net_plugin/net_plugin.cpp

More paranoid socket shutdown when closing and `async_read` with a closed socket. Also cleanup logic on connection duplicate check. 
~Reset `org` as it needs to be reset on close so new connection will `send_time` message correctly.~ (already in `main`)
Merge `release/4.0` into `main` including #1366 
Resolves #1349

[4.0 -> main] Close connection on aysnc_read with a closed socket

---

libraries/chain/webassembly/runtimes/eos-vm.cpp

This PR contains security updates to fix a denial of service vulnerability affecting all previous versions of Leap.

[3.1] Memory issue fix

---

.github/workflows/build.yaml

Resolves: https://github.com/AntelopeIO/leap/issues/1437

Test Fix: libtester test failures in CICD

---

unittests/wasm_tests.cpp

Resolved https://github.com/AntelopeIO/leap/issues/1623.
A test to check the number of memory mappings.

Add a test for memory mappings

---

plugins/net_plugin/net_plugin.cpp

This PR conforms the `net_plugin` logging to meet the objectives set forth in: https://github.com/AntelopeIO/leap/blob/main/docs/01_nodeos/06_logging/01_logging-levels.md
Specifically many `error` level messages were changed to `warn`, `info`, or `debug`.
Merges `release/5.0` into `main` including #1732 
Resolves #1507

[5.0 -> main] P2P: Modify log level for message to avoid confusion

---

.github/workflows/build.yaml
tools/reproducible.Dockerfile

main merge of #1710, closes #1717

[5.0 -> main] integrate reproducible build with CI Build & Test workflow

---

tutorials/bios-boot-tutorial/README.md

Update Tutorial Readme with references to Leap 5.0, CDT 4.0, and System Contracts 3.2. 
Reference Issue #1722

[5.0] Update Tutorial Readme

---

.github/workflows/build.yaml
.github/workflows/release.yaml
libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/eos-vm-oc.h
libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/eos-vm-oc.hpp
libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/memory.hpp
libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/net_plugin/net_plugin.cpp
plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
plugins/producer_plugin/producer_plugin.cpp
plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp
plugins/state_history_plugin/tests/session_test.cpp
tests/p2p_sync_throttle_test.py
tests/test_read_only_trx.cpp
tests/test_snapshot_scheduler.cpp
tools/reproducible.Dockerfile
tutorials/bios-boot-tutorial/README.md

No merge conflicts as a result of merging.

IF: Merge main into hotstuff_integration (10/30/2023)

---

tests/db_modes_test.sh

Add `mapped_private` to `db_modes_test.sh`.
Merges `release/5.0` into `main` including #1887

[5.0 -> main] Add additional tests for mapped_private

---

README.md

Table of Contents proposal

---

.github/workflows/pinned_build.yaml
libraries/chain/block_header_state_legacy.cpp
libraries/chain/block_state_legacy.cpp
libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
libraries/chain/include/eosio/chain/block_state_legacy.hpp
libraries/chain/include/eosio/chain/contract_table_objects.hpp
libraries/chain/include/eosio/chain/database_utils.hpp
libraries/libfc/test/crypto/test_webauthn.cpp
libraries/state_history/include/eosio/state_history/serialization.hpp
libraries/state_history/include/eosio/state_history/types.hpp
plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
plugins/chain_plugin/test/test_trx_retry_db.cpp
plugins/trace_api_plugin/test/include/eosio/trace_api/test_common.hpp
unittests/state_history_tests.cpp
unittests/unapplied_transaction_queue_tests.cpp

Mostly for merging `release/5.0.0 rc3` and  `pending_block_head_state` renaming https://github.com/AntelopeIO/leap/pull/1983.
Merge conflicts resolved by a155d3e69c9e21f17ef5d5698159d4927303cf3e

IF: Merge main into hotstuff_integration branch (12/12/2023)

---

libraries/chain/controller.cpp
plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp

- SHiP - Added block id to `this_block` output of `pushing result` log message.
```
info  2023-12-12T14:55:21.213 ship-0    session.hpp:547               send_update          ] pushing result {"head":{"block_num":397},"last_irreversible":{"block_num":57},"this_block":{"block_num":397, "block_id":0000018d5fb988342f29ac31a55ada90d20cb993f344fc4ee3f9963451b69a7b}} to send queue
```
- controller - Added applied and removed block ids to `successfully switched fork` log message. Note that most fork switches are much smaller than this example from a test that purposely creates a large fork.
```
info  2023-12-12T14:47:54.008 nodeos    controller.cpp:2424           maybe_switch_forks   ] successfully switched fork to new head 0000007b225de24730b455eef258f77689976ac8533a0f7482f1ee008e8e7db1, …
```

[5.0] Extra info level logging

---

.github/workflows/release.yaml
libraries/chain/controller.cpp
plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp

Update with latest `main`. 
Pulls in `bls12-381` with `operator=()`.

IF: Merge main 12/18/2023

---

libraries/chain/hotstuff/chain_pacemaker.cpp

Merge issue between https://github.com/AntelopeIO/leap/pull/1998 & #2003

IF: Fix merge issue on hotstuff_integration

---

plugins/net_plugin/net_plugin.cpp

When running with `block-log-retain-blocks = 0`, many `unlinkable block` exceptions were generated.
Do not attempt to apply blocks that are before LIB. 
Blocks are received before LIB because we always sync from LIB to make sure we see all possible forks. However, between the request and the blocks coming in, LIB can move. When running with no block log, these blocks are not known to have already been processed. However, there is never any reason to attempt to apply blocks that are <= LIB, so just drop them instead of attempting to apply them.
Resolves #2006

[5.0] Fix unlinkable block exceptions when block-log-retain-blocks = 0

---

.cicd/defaults.json
.github/workflows/build.yaml

Will make it easier to iterate on instant finality.

switch to using reference-contracts in libtester tests

---

plugins/http_plugin/http_plugin.cpp
plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp

main merge of #2042 hopefully resolving #2022

[5.0 -> main] extend life of `http_plugin_state` to ensure no invalid memory accesses during nodeos shutdown

---

libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/config.hpp
plugins/http_plugin/http_plugin.cpp
plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
unittests/eosvmoc_limits_tests.cpp

[5.0 -> main] fix disabling EOS VM OC subjective limits in tests

---

libraries/chain/controller.cpp

Goal is having `apply_if` and `apply_dpos` for finality-specific actions.
Also use `apply_if` with a lambda instead of adding `aggregate_vote` as it is used only once.

Trying some code cleanups

---

libraries/chain/block_state.cpp
libraries/chain/controller.cpp
libraries/chain/hotstuff/chain_pacemaker.cpp
libraries/chain/hotstuff/qc_chain.cpp
libraries/chain/hotstuff/test/test_pacemaker.cpp
libraries/chain/hotstuff/test/test_pacemaker.hpp
libraries/chain/include/eosio/chain/block_state.hpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/hotstuff/base_pacemaker.hpp
libraries/chain/include/eosio/chain/hotstuff/chain_pacemaker.hpp
libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
libraries/chain/include/eosio/chain/hotstuff/qc_chain.hpp
libraries/testing/tester.cpp
plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
plugins/net_plugin/net_plugin.cpp
plugins/producer_plugin/producer_plugin.cpp
unittests/block_state_tests.cpp

- `hs_vote_message` => `vote_message`
- `dpos` => `legacy`
- Remove `chain_pacemaker` connections as it is not needed

IF: Misc nomenclature changes

---

libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/testing/include/eosio/testing/tester.hpp
libraries/testing/tester.cpp
plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
plugins/net_plugin/net_plugin.cpp
plugins/producer_plugin/producer_plugin.cpp
unittests/block_tests.cpp
unittests/forked_tests.cpp
unittests/protocol_feature_tests.cpp

- Block handle seems a better name than block token.
-  Thanks @greg7mdp for suggestion
- https://www.quora.com/What-is-the-difference-between-a-token-and-an-object-handle

IF: Rename block_token to block_handle

---

libraries/chain/block_header_state.cpp
libraries/chain/include/eosio/chain/block_header.hpp
unittests/api_tests.cpp
unittests/producer_schedule_if_tests.cpp

IF: confirmed==0 after instant finality enabled

---

plugins/producer_plugin/producer_plugin.cpp

#2106 caused failure on `hotstuff_integration` branch as `producer_plugin` was initialized before `chain_api_plugin`. Search `options` instead of querying of `appbase`. 
Resolves #2104

[5.0] More robust `chain_api_plugin` check in `producer_plugin`; take 2

---

libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/hotstuff/hotstuff.hpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
programs/cleos/httpc.hpp
programs/cleos/main.cpp

Continuing code clean up.
Resolved https://github.com/AntelopeIO/leap/issues/2156

IF: remove /v1/chain/get_finalizer_state RPC API related code

---

libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp

[5.0 -> main] always set OC's sandbox socket to blocking mode fixing random OC errors seen in CI & maybe elsewhere

---

libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp

Includes SEGFAULT fix of `oc` tests.

IF: Merge main 01-31-2024

---

plugins/http_plugin/http_plugin.cpp
plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
plugins/http_plugin/include/eosio/http_plugin/common.hpp
plugins/http_plugin/tests/CMakeLists.txt
plugins/http_plugin/tests/unit_tests.cpp
plugins/producer_plugin/producer_plugin.cpp
plugins/state_history_plugin/tests/CMakeLists.txt
tests/CMakeLists.txt
tests/trx_generator/CMakeLists.txt

IF: Merge main 02-07-2024

---

tests/CMakeLists.txt
tests/liveness_test.py

Add a test to verify loss and recovery of finality liveness are handled correctly.
Resolved https://github.com/AntelopeIO/leap/issues/2147

IF: add a test for loss and recovery of finality liveness 

---

libraries/chain/controller.cpp

Store new proposer policy in `chainbase` instead of on the building block. If a transaction fails because it ran out of block time after it set the new proposer policy on the building block this side-affect was not being rolled back. By storing the new proposer policy in `chainbase` it will be rolled back if the transaction is rolled back.
Use the existing `global_property_object.proposed_schedule` as storage for the new proposer schedule until complete block. At the end of every block the `global_property_object.proposed_schedule` will be empty as it is cleared in complete block or rolled back in abort block.
Resolves #2256

IF: Store new proposer policy in chainbase instead of building block

---

tutorials/bios-boot-tutorial/bios-boot-tutorial.py

PR #2318 added dependancies and changed the INSTANT_FINALITY Protocol Activation 
FROM: 8cb6dd1e5607208331eb5983141e159c75a597413887e80e8a9a4b715a507eb7
TO: 18b790108f5e277cf7141dc626a98f7edeb776912278e4cd14a50b763d1d6390

IF: Update Protocol Activation in Bios Boot Tutorial

---

plugins/producer_api_plugin/producer_api_plugin.cpp

[5.0 -> main] avoid using a stack variable after return

---

libraries/chain/include/eosio/chain/incremental_merkle.hpp
libraries/chain/transaction_context.cpp
plugins/producer_api_plugin/producer_api_plugin.cpp

Needed to get #1536 ci/cd running again.

IF: Merge main 03-27-2024

---

libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
unittests/producer_schedule_if_tests.cpp

Adds ignoring proposed producers during transition.
Resolves #2057

IF: Ignore proposed producers during transition

---

benchmark/benchmark.cpp
benchmark/benchmark.hpp
benchmark/merkle.cpp
unittests/merkle_tree_tests.cpp

Resolves #2371.
Title says all.

IF: Move perf tests to benchmark

---

libraries/chain/snapshot.cpp
plugins/chain_api_plugin/chain.swagger.yaml

[5.0] fix some minor misspellings
